---
sidebar: sidebar 
permalink: concept_about_applications.html 
keywords: applications, asset, cost 
summary: 'La comprensione delle applicazioni utilizzate nell"ambiente aziendale consente di tenere traccia dell"utilizzo e dei costi delle risorse.' 
---
= Monitoraggio dell'utilizzo delle risorse per applicazione
:allow-uri-read: 
:firstname: [.lead]
:author: [.lead]
:authorinitials: [
:authors: [.lead]
:revdate: Understanding the applications used in your company's environment helps you to keep track of asset usage and cost.


Prima di tenere traccia dei dati associati alle applicazioni in esecuzione nel proprio ambiente, è necessario definire tali applicazioni e associarle alle risorse appropriate. È possibile associare le applicazioni alle seguenti risorse: Host, macchine virtuali, volumi, volumi interni, qtree, condivisioni e hypervisor.

In questo argomento viene fornito un esempio di monitoraggio dell'utilizzo delle macchine virtuali che il team di marketing utilizza per la posta elettronica Exchange.

È possibile creare una tabella simile a quella riportata di seguito per identificare le applicazioni utilizzate nel proprio ambiente e prendere nota del gruppo o della business unit che utilizza ciascuna applicazione.

[cols="5*"]
|===


| Tenant | Linea di business | Unità aziendale | Progetto | Applicazioni 


| NetApp | Storage dei dati | Legale | Brevetti | Oracle Identity Manager, Oracle on Demand, PatentWiz 


| NetApp | Storage dei dati | Marketing | Eventi commerciali | Exchange, Oracle Shared Database, BlastOff Event Planner 
|===
La tabella mostra che il team di marketing utilizza l'applicazione Exchange. Vogliamo tenere traccia dell'utilizzo delle macchine virtuali per Exchange, in modo da poter prevedere quando sarà necessario aggiungere ulteriore storage. Possiamo associare l'applicazione Exchange a tutte le macchine virtuali di Marketing:

. Creare un'applicazione denominata _Exchange_
. Accedere a *Query > +Nuova query* per creare una nuova query per le macchine virtuali (oppure selezionare una query VM esistente, se applicabile).
+
Supponendo che tutte le macchine virtuali del team di marketing abbiano un nome contenente la stringa "*mkt*", creare la query per filtrare il nome della macchina virtuale per "mkt".

. Selezionare le macchine virtuali.
. Associare le macchine virtuali all'applicazione _Exchange_ utilizzando *azioni in blocco > Aggiungi applicazioni*.
. Selezionare l'applicazione desiderata e fare clic su *Save* (Salva).
. Al termine, *salvare* la query.

