---
sidebar: sidebar 
permalink: concept_asset_user_data_section.html 
summary: La sezione Dati utente di una pagina di risorse consente di assegnare annotazioni o applicazioni alla risorsa corrente. 
keywords: asset page, user data, applications, annotations 
---
= Sezione dati utente
:hardbreaks:
:allow-uri-read: 


[role="lead"]
La sezione Dati utente di una pagina di risorse visualizza e consente di modificare tutti i dati definiti dall'utente, come applicazioni e annotazioni.



== Utilizzo della sezione Dati utente per assegnare o modificare le applicazioni

È possibile assegnare le applicazioni in esecuzione sul tenant a determinate risorse (host, macchine virtuali, volumi, volumi interni, qtree e hypervisor).  La sezione Dati utente consente di aggiungere, modificare o rimuovere le applicazioni assegnate a una risorsa.  Per tutti questi tipi di asset, ad eccezione dei volumi, è possibile assegnare più di un'applicazione.

.Passi
. Per individuare una pagina di risorse, procedere in uno dei seguenti modi:
+
.. Richiedi un elenco di risorse e selezionane una dall'elenco.
.. In una Dashboard, individua il nome di una risorsa e fai clic su di essa.
.. Esegui una ricerca e scegli una risorsa dai risultati.
+
Viene visualizzata la pagina delle risorse.  La sezione Dati utente della pagina mostra le applicazioni o le annotazioni attualmente assegnate.





Per modificare l'applicazione assegnata o per assegnare un'applicazione o più applicazioni aggiuntive, apri l'elenco a discesa *Applicazione* e seleziona l'applicazione/le applicazioni che desideri assegnare alla risorsa.  È possibile digitare per cercare un'applicazione oppure selezionarne una dall'elenco.

Per rimuovere un'applicazione, apri l'elenco delle applicazioni e deseleziona l'applicazione.



== Utilizzo della sezione Dati utente per assegnare o modificare annotazioni

Quando si personalizza Data Infrastructure Insights per monitorare i dati in base alle esigenze aziendali, è possibile definire note specializzate chiamate annotazioni e assegnarle alle risorse.  La sezione Dati utente di una pagina di risorse visualizza le annotazioni assegnate a una risorsa e consente inoltre di modificare le annotazioni assegnate a tale risorsa.

.Passi
. Per aggiungere un'annotazione alla risorsa, nella sezione Dati utente della pagina della risorsa, fare clic su *+Annotazione*.
. Seleziona un'annotazione dall'elenco.
. Fare clic su Valore ed effettuare una delle seguenti operazioni, a seconda del tipo di annotazione selezionato:
+
.. Se il tipo di annotazione è elenco, data o booleano, selezionare un valore dall'elenco.
.. Se il tipo di annotazione è testo, digitare un valore.


. Fare clic su Salva.


L'annotazione viene assegnata alla risorsa.  Successivamente è possibile filtrare le risorse in base all'annotazione utilizzando una query.

Se si desidera modificare il valore dell'annotazione dopo averla assegnata, scorrere l'elenco delle annotazioni e immettere un valore diverso.

Se l'annotazione è di tipo elenco per cui è selezionata l'opzione _Aggiungi nuovi valori al volo_, è possibile digitare per aggiungere un nuovo valore oltre a selezionare un valore esistente.
