---
sidebar: sidebar 
permalink: concept_telegraf_display_options.html 
keywords: telegraf, data, display, 
summary: Opzioni di visualizzazione dei dati Telegraf 
---
= Trasformazione delle metriche
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights fornisce diverse opzioni di *trasformazione* per determinate metriche nei widget (in particolare, quelle denominate "Personalizzate" o Metriche di integrazione, come quelle provenienti da Kubernetes, ONTAP Advanced Data, plugin Telegraf, ecc.), consentendo di visualizzare i dati in vari modi.  Quando si aggiungono metriche trasformabili a un widget, viene visualizzato un menu a discesa che offre le seguenti opzioni di trasformazione:

Nessuno: i dati vengono visualizzati così come sono, senza alcuna manipolazione.

Tasso: valore corrente diviso per l'intervallo di tempo trascorso dall'osservazione precedente.

Cumulativo: l'accumulo della somma dei valori precedenti e del valore corrente.

Delta: la differenza tra il valore dell'osservazione precedente e il valore attuale.

Tasso delta: valore delta diviso per l'intervallo di tempo trascorso dall'osservazione precedente.

Tasso cumulativo: valore cumulativo diviso per l'intervallo di tempo trascorso dall'osservazione precedente.

Si noti che la trasformazione delle metriche non modifica i dati sottostanti in sé, ma solo il modo in cui vengono visualizzati.
