---
sidebar: sidebar 
permalink: concept_import_from_dashboard_gallery.html 
summary: Importa dashboard predefinite dalla galleria per ottenere rapidamente informazioni aziendali, oppure importa dashboard personalizzate che hai esportato per condividere le configurazioni tra i tenant. 
keywords: dashboard, gallery, import, export 
---
= Importazione di dashboard
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Accedi ai dashboard predefiniti dalla galleria per ottenere rapidamente informazioni dettagliate sulla tua infrastruttura, oppure importa dashboard personalizzati che hai esportato da altri tenant. I dashboard della galleria sono personalizzati in base ai data collector del tuo ambiente e progettati per rispondere a specifiche domande aziendali, mentre i dashboard esportati ti permettono di condividere configurazioni utili tra più tenant.



[[importing-from-the-dashboard-gallery]]
== Importazione dalla Galleria della Dashboard

Per importare una dashboard dalla galleria, procedere come segue:

. Seleziona *Osservabilità > Esplora > Tutte le dashboard*
. Fare clic su *+Importa dashboard* e scegliere _Importa dalla galleria_.
+
Viene visualizzato un elenco di *Dashboard consigliate*, in base ai raccoglitori di dati presenti nel tuo ambiente. Sono disponibili dashboard per rispondere a domande su diversi tipi di oggetti, tra cui AWS, NetApp, Storage, VMware e altri.

. Seleziona una o più dashboard dall'elenco e fai clic su *Aggiungi dashboard*. Queste dashboard verranno visualizzate nell'elenco delle dashboard.


Oltre alle Dashboard consigliate, puoi anche scegliere di importare *Dashboard aggiuntive* che non sono pertinenti ai tuoi dati attuali.  Ad esempio, se al momento non hai installato alcun raccoglitore di dati di archiviazione ma prevedi di configurarne alcuni in futuro, puoi comunque scegliere di importare i dashboard rilevanti per l'archiviazione.  Queste dashboard saranno disponibili per la visualizzazione, ma potrebbero non mostrare dati rilevanti finché non sarà configurato almeno un raccoglitore di dati di archiviazione.

L'importazione dalla galleria della dashboard è disponibile per gli utenti con ruolo di Amministratore o Proprietario dell'account.



[[importing-an-exported-dashboard]]
== Importazione di una dashboard esportata

Per *esportare* una dashboard, nella pagina *Osservabilità > Esplora > Tutte le dashboard*, fare clic sul menu a destra della dashboard e scegliere _Esporta_. È anche possibile selezionare più dashboard e scegliere _Esporta_ dal menu a discesa _Azioni in blocco_. I dashboard vengono salvati in un file .ZIP sul sistema locale.

Per *importare* la dashboard, vai al tenant desiderato e procedi come segue:

. Seleziona *Osservabilità > Esplora > Tutte le dashboard*
. Fare clic su *+Importa dashboard* e scegliere _Importa da file_. Seleziona il file .ZIP del file esportato in precedenza. La/le dashboard verranno importate e verranno visualizzate nell'elenco delle dashboard. Tieni presente che se stai importando una dashboard con lo stesso nome di una dashboard esistente, al nome della dashboard verrà aggiunto un "(2)".

