---
sidebar: sidebar 
permalink: concept_cs_api.html 
keywords: api, access, token, swagger 
summary: 'Workload Security include una potente API per l"integrazione con altre applicazioni come i CMDB.' 
---
= API di sicurezza del carico di lavoro
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L'API Workload Security consente ai clienti NetApp e ai fornitori di software indipendenti (ISV) di integrare Workload Security con altre applicazioni, come CMDB o altri sistemi di ticketing.

Requisiti per l'accesso all'API:

* Per concedere l'accesso viene utilizzato un modello di token di accesso API.
* La gestione dei token API viene eseguita dagli utenti di Workload Security con il ruolo di amministratore.




== Documentazione API (Swagger)

Per reperire le informazioni API più recenti, accedere a Workload Security e andare su *Amministrazione > Accesso API*.  Fare clic sul collegamento *Documentazione API*.  La documentazione API è basata su Swagger, che fornisce una breve descrizione e informazioni sull'utilizzo dell'API e consente di provarla sul proprio tenant.


NOTE: Se si richiama l'API Forensics Activity, utilizzare l'API cloudsecure_forensics.activities.*v2*.  Se si effettuano più chiamate a questa API, assicurarsi che le chiamate avvengano in sequenza e non in parallelo.  Più chiamate parallele potrebbero causare il timeout dell'API.



== Token di accesso API

Prima di utilizzare l'API Workload Security, è necessario creare uno o più *token di accesso API*.  I token di accesso concedono permessi di lettura.  È anche possibile impostare la scadenza per ciascun token di accesso.

Per creare un token di accesso:

* Fare clic su *Amministrazione > Accesso API*
* Fai clic su *+Token di accesso API*
* Inserisci *Nome token*
* Specifica *Scadenza token*



NOTE: Il tuo token potrà essere copiato negli appunti e salvato solo durante il processo di creazione.  Una volta creati, i token non possono essere recuperati, pertanto si consiglia vivamente di copiarli e salvarli in un luogo sicuro.  Ti verrà chiesto di fare clic sul pulsante Copia token di accesso API prima di poter chiudere la schermata di creazione del token.

È possibile disattivare, attivare e revocare i token.  I token disabilitati possono essere abilitati.

I token garantiscono l'accesso generico alle API dal punto di vista del cliente, gestendo l'accesso alle API nell'ambito del proprio tenant.

L'applicazione riceve un token di accesso dopo che un utente si è autenticato e ha autorizzato l'accesso, quindi passa il token di accesso come credenziale quando chiama l'API di destinazione.  Il token trasmesso informa l'API che il portatore del token è stato autorizzato ad accedere all'API ed eseguire azioni specifiche in base all'ambito concesso durante l'autorizzazione.

L'intestazione HTTP in cui viene passato il token di accesso è *X-CloudInsights-ApiKey:*

Ad esempio, utilizzare quanto segue per recuperare le risorse di archiviazione:

 curl https://<Workload Security tenant>/rest/v1/cloudsecure/activities -H 'X-CloudInsights-ApiKey: <API_Access_Token>'
Dove _<API_Access_Token>_ è il token salvato durante la creazione della chiave di accesso API e _<Workload Security Tenant>_ è l'URL del tenant del tuo ambiente Workload Security.

Informazioni dettagliate sono disponibili nel link _Documentazione API_ in *Amministrazione > Accesso API*.



== Script per estrarre dati tramite API

Gli agenti Workload Security includono uno script di esportazione per facilitare le chiamate parallele all'API v2 suddividendo l'intervallo di tempo richiesto in batch più piccoli.

Lo script si trova in _/opt/netapp/cloudsecure/agent/export-script_.  Un file README nella stessa directory fornisce le istruzioni per l'uso.

Ecco un comando di esempio per richiamare lo script:

[source]
----
python3 data-export.py --tenant_url <Workload Security tenant> --access_key %ACCESS_KEY% --path_filter "<dir path>" --user_name "<user>" --from_time "01-08-2024 00:00:00" --to_time "31-08-2024 23:59:59" --iteration_interval 12 --num_workers 3
----
Parametri chiave: - `--iteration_interval 12` : Suddivide l'intervallo di tempo richiesto in intervalli di 12 ore.  - `--num_workers 3` : Recupera questi intervalli in parallelo utilizzando 3 thread.
