---
sidebar: sidebar 
permalink: concept_about_applications.html 
keywords: applications, asset, cost 
summary: 'Conoscere le applicazioni utilizzate nell"ambiente aziendale aiuta a tenere traccia dell"utilizzo delle risorse e dei costi.' 
---
= Monitoraggio dell'utilizzo delle risorse per applicazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Conoscere le applicazioni utilizzate nell'ambiente aziendale aiuta a tenere traccia dell'utilizzo e dei costi delle risorse.

Prima di poter monitorare i dati associati alle applicazioni in esecuzione sul tenant, è necessario definire tali applicazioni e associarle alle risorse appropriate.  È possibile associare le applicazioni alle seguenti risorse: host, macchine virtuali, volumi, volumi interni, qtree, condivisioni e hypervisor.

Questo argomento fornisce un esempio di monitoraggio dell'utilizzo delle macchine virtuali utilizzate dal team di marketing per la posta elettronica di Exchange.

Potresti voler creare una tabella simile alla seguente per identificare le applicazioni utilizzate sul tuo tenant e annotare il gruppo o l'unità aziendale che utilizza ciascuna applicazione.

[cols="5*"]
|===


| Inquilino | Linea di business | Unità aziendale | Progetto | Applicazioni 


| NetApp | Archiviazione dati | Legal | Brevetti | Oracle Identity Manager, Oracle On Demand, PatentWiz 


| NetApp | Archiviazione dati | Marketing | Eventi di vendita | Exchange, Oracle Shared Database, BlastOff Event Planner 
|===
La tabella mostra che il team di marketing utilizza l'applicazione Exchange.  Vogliamo monitorare l'utilizzo delle loro macchine virtuali per Exchange, in modo da poter prevedere quando sarà necessario aggiungere altro spazio di archiviazione.  Possiamo associare l'applicazione Exchange a tutte le macchine virtuali di Marketing:

. Crea un'applicazione denominata _Exchange_
. Vai su *Query > +Nuova query* per creare una nuova query per le macchine virtuali (oppure seleziona una query VM esistente, se applicabile).
+
Supponendo che tutte le VM del team di marketing abbiano un nome contenente la stringa "*mkt*", crea la tua query per filtrare il nome della VM per "mkt".

. Selezionare le VM.
. Associare le VM all'applicazione _Exchange_ utilizzando *Azioni in blocco > Aggiungi applicazioni*.
. Selezionare l'applicazione desiderata e fare clic su *Salva*.
. Al termine, *Salva* la query.

