---
sidebar: sidebar 
permalink: concept_cs_event_rate_checker.html 
summary: Questo script può essere eseguito per controllare la frequenza degli eventi nella SVM prima di installare una DSC SVM ONTAP 
keywords: event, checker, rate, sizing, cloud secure 
---
= SVM Event Rate Checker (Guida al dimensionamento dell'agente)
:hardbreaks:
:allow-uri-read: 


[role="lead"]
La funzione di verifica del tasso di eventi viene utilizzata per controllare la velocità di eventi combinata NFS/SMB nella SVM prima di installare un data collector SVM ONTAP, per verificare il numero di macchine SVM che un agente è in grado di monitorare. Utilizza Event Rate Checker come guida al dimensionamento per pianificare il tuo ambiente di sicurezza.

Un agente può supportare fino a un massimo di 50 raccoglitori di dati.



== Requisiti:

* IP cluster
* Nome utente e password dell'amministratore del cluster



NOTE: Durante l'esecuzione di questo script, non deve essere eseguito alcun Data Collector SVM ONTAP per la SVM per la quale viene determinata la frequenza degli eventi.

Fasi:

. Installare l'Agent seguendo le istruzioni in CloudSecure.
. Una volta installato l'agente, eseguire lo script _server_data_rate_checker.sh_ come utente sudo:
+
 /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
. Questo script richiede l'installazione di _sshpass_ nella macchina linux. Esistono due modi per installarlo:
+
.. Eseguire il seguente comando:
+
 linux_prompt> yum install sshpass
.. Se questo non funziona, scaricare _sshpass_ sulla macchina linux dal web ed eseguire il seguente comando:
+
 linux_prompt> rpm -i sshpass


. Fornire i valori corretti quando richiesto. Per un esempio, vedere di seguito.
. L'esecuzione dello script richiede circa 5 minuti.
. Al termine dell'esecuzione, lo script stampa la frequenza degli eventi dalla SVM. È possibile controllare il tasso di eventi per SVM nell'output della console:
+
 “Svm svm_rate is generating 100 events/sec”.


Ciascun Data Collector SVM di ONTAP può essere associato a una singola SVM, il che significa che ciascun data collector potrà ricevere il numero di eventi generati da una singola SVM.

Tenere presente quanto segue:

A) utilizzare questa tabella come guida generale al dimensionamento. È possibile aumentare il numero di core e/o memoria per aumentare il numero di data collector supportati, fino a un massimo di 50 data collector:

|===


| Configurazione del computer dell'agente | Numero di Data Collector SVM | Tasso massimo di eventi che il computer dell'agente può gestire 


| 4 core, 16 GB | 10 raccolta di dati | 20.000 eventi/sec 


| 4 core, 32 GB | 20 raccolta di dati | 20.000 eventi/sec 
|===
B) per calcolare il totale degli eventi, aggiungere gli eventi generati per tutte le SVM per quell'agente.

C) se lo script non viene eseguito durante le ore di punta o se il traffico di picco è difficile da prevedere, mantenere un buffer del tasso di eventi del 30%.

B + C deve essere inferiore A A, altrimenti il computer dell'agente non potrà eseguire il monitoraggio.

In altre parole, il numero di raccolta dati che è possibile aggiungere a una macchina a singolo agente deve essere conforme alla formula seguente:

 Sum of all Event rate of all Data Source Collectors + Buffer Event rate of 30% < 20000 events/second
Consultare la link:concept_cs_agent_requirements.html["Requisiti dell'agente"] pagina per ulteriori prerequisiti e requisiti.



== Esempio

Diciamo che abbiamo tre SVM che generano percentuali di eventi rispettivamente di 100, 200 e 300 eventi al secondo.

Applichiamo la formula:

....
 (100+200+300) + [(100+200+300)*30%] = 600+180 = 780events/sec
780 events/second is < 20000 events/second, so the 3 SVMs can be monitored via one agent box.
....
L'output della console è disponibile nella macchina Agente nel nome del file __fpolicy_stat_<SVM Name>.log__ nella directory di lavoro corrente.

Lo script può fornire risultati errati nei seguenti casi:

* Vengono fornite credenziali, IP o nome SVM errati.
* Un fpolicy già esistente con lo stesso nome, numero di sequenza, ecc. genera un errore.
* Lo script viene arrestato bruscamente durante l'esecuzione.


Di seguito è riportato un esempio di esecuzione di script:

 [root@ci-cs-data agent]# /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
....
Enter the cluster ip: 10.192.139.166
Enter the username to SSH: admin
Enter the password:
Getting event rate for NFS and SMB events.
Available SVMs in the Cluster
-----------------------------
QA_SVM
Stage_SVM
Qa-fas8020
Qa-fas8020-01
Qa-fas8020-02
audit_svm
svm_rate
vs_new
vs_new2
....
....
-----------------------------
Enter [1/5] SVM name to check (press enter to skip): svm_rate
Enter [2/5] SVM name to check (press enter to skip): audit_svm
Enter [3/5] SVM name to check (press enter to skip):
Enter [4/5] SVM name to check (press enter to skip):
Enter [5/5] SVM name to check (press enter to skip):
Running check for svm svm_rate...
Running check for svm audit_svm...
Waiting 5 minutes for stat collection
Stopping sample svm_rate_sample
Stopping sample audit_svm_sample
fpolicy stats of svm svm_rate is saved in fpolicy_stat_svm_rate.log
Svm svm_rate is generating 100 SMB events/sec and 100 NFS events/sec
Overall svm svm_rate is generating 200 events/sec
fpolicy stats of svm audit_svm is saved in fpolicy_stat_audit_svm.log
Svm audit_svm is generating 200 SMB events/sec and 100 NFS events/sec
Overall svm audit_svm is generating 300 events/sec
....
 [root@ci-cs-data agent]#


== Risoluzione dei problemi

|===


| Domanda | Risposta 


| Se si esegue questo script su una SVM già configurata per la sicurezza del carico di lavoro, viene utilizzata solo la configurazione fpolicy esistente sulla SVM oppure viene impostata una configurazione temporanea ed è possibile eseguire il processo? | La funzione Event Rate Checker può essere eseguita correttamente anche per una SVM già configurata per la sicurezza del carico di lavoro. Non dovrebbe esserci alcun impatto. 


| È possibile aumentare il numero di SVM su cui è possibile eseguire lo script? | Sì. È sufficiente modificare lo script e modificare il numero massimo di SVM da 5 a qualsiasi numero desiderato. 


| Se si aumenta il numero di SVM, si aumenterà il tempo di esecuzione dello script? | No. Lo script viene eseguito per un massimo di 5 minuti, anche in caso di aumento del numero di SVM. 


| È possibile aumentare il numero di SVM su cui è possibile eseguire lo script? | Sì. È necessario modificare lo script e modificare il numero massimo di SVM da 5 a qualsiasi numero desiderato. 


| Se si aumenta il numero di SVM, si aumenterà il tempo di esecuzione dello script? | No. Lo script viene eseguito per un massimo di 5mins TB, anche in caso di aumento del numero di SVM. 


| Cosa succede se si esegue Event Rate Checker con un agente esistente? | L'esecuzione di Event Rate Checker con un agente già esistente può causare un aumento della latenza sulla SVM. Questo aumento sarà temporaneo durante l'esecuzione di Event Rate Checker. 
|===