---
sidebar: sidebar 
permalink: concept_telegraf_display_options.html 
keywords: telegraf, data, display, 
summary: Opzioni di visualizzazione dei dati Telegraf 
---
= Trasformazione delle metriche
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Data Infrastructure Insights fornisce diverse opzioni *Transform* per determinate metriche nei widget (in particolare, quelle metriche chiamate "personalizzate" o metriche di integrazione, come da Kubernetes, dati avanzati di ONTAP, plug-in Telegraf, ecc.), consentendo di visualizzare i dati in diversi modi. Quando si aggiungono metriche trasformabili a un widget, viene visualizzato un menu a discesa che offre le seguenti scelte di trasformazione:

Nessuno:: I dati vengono visualizzati così come sono, senza alcuna manipolazione.
Tasso:: Valore corrente diviso per l'intervallo di tempo dall'osservazione precedente.
Cumulativo:: L'accumulo della somma dei valori precedenti e del valore corrente.
Delta:: La differenza tra il valore di osservazione precedente e il valore corrente.
Delta rate (tasso delta):: Valore delta diviso per l'intervallo di tempo dall'osservazione precedente.
Tasso cumulativo:: Valore cumulativo diviso per l'intervallo di tempo dall'osservazione precedente.


Si noti che la trasformazione delle metriche non modifica i dati sottostanti, ma solo il modo in cui vengono visualizzati.
