---
sidebar: sidebar 
permalink: concept_searching_assets.html 
summary: Le tecniche di ricerca avanzata possono aiutarti a individuare le risorse che stai cercando. 
keywords: asset page, objects, search, advanced, alerts 
---
= Suggerimenti e consigli per cercare risorse e avvisi
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Per ricercare dati o oggetti nell'ambiente monitorato è possibile utilizzare diverse tecniche di ricerca.

* *Ricerca con caratteri jolly*
+
È possibile eseguire una ricerca con più caratteri jolly utilizzando il carattere *.  Ad esempio, _applic*n_ restituirebbe _application_.

* *Frasi utilizzate nella ricerca*
+
Una frase è un gruppo di parole racchiuso tra virgolette doppie, ad esempio "VNX LUN 5".  È possibile utilizzare le virgolette doppie per cercare documenti che contengono spazi nei loro nomi o attributi.

* *Operatori booleani*
+
Utilizzando gli operatori booleani OR, AND e NOT, è possibile combinare più termini per formare una query più complessa.

+
O

+
L'operatore OR è l'operatore di congiunzione predefinito.

+
Se non esiste alcun operatore booleano tra due termini, viene utilizzato l'operatore OR.

+
L'operatore OR collega due termini e trova un documento corrispondente se uno dei due termini è presente in un documento.

+
Ad esempio, _storage OR netapp_ cerca i documenti che contengono _storage_ o _netapp_.

+
I punteggi più alti vengono assegnati ai documenti che corrispondono alla maggior parte dei termini.

+
E

+
È possibile utilizzare l'operatore AND per trovare documenti in cui entrambi i termini di ricerca sono presenti in un unico documento.  Ad esempio, _storage AND netapp_ cerca i documenti che contengono sia _storage_ che _netapp_.

+
È possibile utilizzare il simbolo *&&* al posto della parola AND.

+
NON

+
Quando si utilizza l'operatore NOT, tutti i documenti che contengono il termine dopo NOT vengono esclusi dai risultati della ricerca.  Ad esempio, _storage NOT netapp_ cerca i documenti che contengono solo _storage_ e non _netapp_.

+
È possibile utilizzare il simbolo *!* al posto della parola NOT.



La ricerca non distingue tra maiuscole e minuscole.



== Ricerca tramite termini indicizzati

Le ricerche che corrispondono a un numero maggiore di termini indicizzati generano punteggi più alti.

La stringa di ricerca viene suddivisa in termini di ricerca separati tramite uno spazio.  Ad esempio, la stringa di ricerca "storage aurora netapp" è suddivisa in tre parole chiave: "storage", "aurora" e "netapp".  La ricerca viene effettuata utilizzando tutti e tre i termini.  I documenti che corrispondono alla maggior parte di questi termini avranno il punteggio più alto.  Più informazioni fornisci, migliori saranno i risultati della ricerca.  Ad esempio, è possibile cercare un archivio in base al nome e al modello.

L'interfaccia utente visualizza i risultati della ricerca per categorie, con i tre risultati principali per categoria.  Se non hai trovato l'oggetto che ti aspettavi, puoi includere più termini nella stringa di ricerca per migliorare i risultati della ricerca.

La tabella seguente fornisce un elenco di termini indicizzati che possono essere aggiunti alla stringa di ricerca.

|===
| Categoria | Termini indicizzati 


| Magazzinaggio | modello del fornitore del nome "storage" 


| StoragePool | "storagepool" nome nome dell'archiviazione indirizzi IP dell'archiviazione numero di serie dell'archiviazione fornitore dell'archiviazione modello di archiviazione nomi per tutti i volumi interni associati nomi per tutti i dischi associati 


| Volume interno | "internalvolume" nome nome dell'archiviazione indirizzi IP dell'archiviazione numero di serie dell'archiviazione fornitore dell'archiviazione modello di archiviazione nome del pool di archiviazione nomi di tutte le condivisioni associate nomi di tutte le applicazioni associate 


| Volume | etichetta del nome "volume" nomi di tutti i volumi interni nome del pool di archiviazione nome dell'archiviazione indirizzi IP dell'archiviazione numero di serie dell'archiviazione fornitore dell'archiviazione modello di archiviazione 


| Nodo di archiviazione | "storagenode" nome nome dell'archiviazione indirizzi IP dell'archiviazione numero di serie dell'archiviazione fornitore dell'archiviazione modello di archiviazione 


| Ospite | nome "host" indirizzi IP nomi di tutte le applicazioni associate 


| Archivio dati | nome "datastore" centro virtuale nomi IP di tutti i volumi nomi di tutti i volumi interni 


| Macchine virtuali | nome "virtualmachine" nome DNS indirizzi IP nome dell'host indirizzi IP dell'host nomi di tutti i datastore nomi di tutte le applicazioni associate 


| Interruttori (normali e NPV) | "switch" indirizzo IP nome wwn numero di serie modello ID dominio nome del fabric wwn del fabric 


| Applicazione | nome "applicazione" tenant linea di business unità aziendale progetto 


| Nastro | "nastro" indirizzo IP nome numero di serie fornitore 


| Porta | nome wwn "porta" 


| Tessuto | nome wwn "fabric" 


| Macchina virtuale di archiviazione (SVM) | UUID del nome "storagevirtualmachine" 
|===