---
sidebar: sidebar 
permalink: concept_cs_event_rate_checker.html 
summary: 'Questo script può essere eseguito per controllare la frequenza degli eventi nell"SVM prima di installare un ONTAP SVM DSC' 
keywords: event, checker, rate, sizing, cloud secure 
---
= SVM Event Rate Checker (Guida al dimensionamento degli agenti)
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Event Rate Checker viene utilizzato per controllare la frequenza degli eventi combinata NFS/SMB nell'SVM prima di installare un raccoglitore dati ONTAP SVM, per vedere quanti SVM una macchina agente sarà in grado di monitorare.  Utilizza Event Rate Checker come guida alle dimensioni per pianificare il tuo ambiente di sicurezza.

Un agente può supportare fino a un massimo di 50 raccoglitori di dati.



== Requisiti:

* IP del cluster
* Nome utente e password dell'amministratore del cluster



NOTE: Quando si esegue questo script, non deve essere in esecuzione alcun ONTAP SVM Data Collector per l'SVM per cui si sta determinando la frequenza degli eventi.

Passaggi:

. Installare l'agente seguendo le istruzioni in CloudSecure.
. Una volta installato l'agente, eseguire lo script _server_data_rate_checker.sh_ come utente sudo:
+
 /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
. Questo script richiede che _sshpass_ sia installato sulla macchina Linux.  Ci sono due modi per installarlo:
+
.. Esegui il seguente comando:
+
 linux_prompt> yum install sshpass
.. Se ciò non funziona, scarica _sshpass_ dal web sul computer Linux ed esegui il seguente comando:
+
 linux_prompt> rpm -i sshpass


. Fornire i valori corretti quando richiesto.  Di seguito è riportato un esempio.
. L'esecuzione dello script richiederà circa 5 minuti.
. Una volta completata l'esecuzione, lo script stamperà la frequenza degli eventi dall'SVM.  È possibile controllare la frequenza degli eventi per SVM nell'output della console:
+
 “Svm svm_rate is generating 100 events/sec”.


Ogni Ontap SVM Data Collector può essere associato a un singolo SVM, il che significa che ogni data collector sarà in grado di ricevere il numero di eventi generati da un singolo SVM.

Tieni presente quanto segue:

A) Utilizzare questa tabella come guida generale alle taglie.  È possibile aumentare il numero di core e/o di memoria per aumentare il numero di collettori dati supportati, fino a un massimo di 50 collettori dati:

|===


| Configurazione della macchina agente | Numero di collettori di dati SVM | Frequenza massima degli eventi che la macchina agente può gestire 


| 4 core, 16 GB | 10 raccoglitori di dati | 20K eventi/sec 


| 4 core, 32 GB | 20 raccoglitori di dati | 20K eventi/sec 
|===
B) Per calcolare il totale degli eventi, sommare gli eventi generati per tutti gli SVM per quell'agente.

C) Se lo script non viene eseguito durante le ore di punta o se è difficile prevedere il traffico di punta, mantenere un buffer di frequenza degli eventi del 30%.

B + C Dovrebbe essere minore di A, altrimenti la macchina agente non riuscirà a monitorare.

In altre parole, il numero di collettori di dati che possono essere aggiunti a una singola macchina agente dovrebbe essere conforme alla formula seguente:

 Sum of all Event rate of all Data Source Collectors + Buffer Event rate of 30% < 20000 events/second
Vedi illink:concept_cs_agent_requirements.html["Requisiti dell'agente"] pagina per ulteriori prerequisiti e requisiti.



== Esempio

Supponiamo di avere tre SVMS che generano frequenze di eventi rispettivamente di 100, 200 e 300 eventi al secondo.

Applichiamo la formula:

....
 (100+200+300) + [(100+200+300)*30%] = 600+180 = 780events/sec
780 events/second is < 20000 events/second, so the 3 SVMs can be monitored via one agent box.
....
L'output della console è disponibile nella macchina dell'agente nel nome file __fpolicy_stat_<Nome SVM>.log__ nella directory di lavoro corrente.

Lo script potrebbe dare risultati errati nei seguenti casi:

* Sono state fornite credenziali, IP o nome SVM errati.
* Una fpolicy già esistente con lo stesso nome, numero di sequenza, ecc. genererà un errore.
* Lo script si interrompe bruscamente durante l'esecuzione.


Di seguito è riportato un esempio di esecuzione dello script:

 [root@ci-cs-data agent]# /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
....
Enter the cluster ip: 10.192.139.166
Enter the username to SSH: admin
Enter the password:
Getting event rate for NFS and SMB events.
Available SVMs in the Cluster
-----------------------------
QA_SVM
Stage_SVM
Qa-fas8020
Qa-fas8020-01
Qa-fas8020-02
audit_svm
svm_rate
vs_new
vs_new2
....
....
-----------------------------
Enter [1/5] SVM name to check (press enter to skip): svm_rate
Enter [2/5] SVM name to check (press enter to skip): audit_svm
Enter [3/5] SVM name to check (press enter to skip):
Enter [4/5] SVM name to check (press enter to skip):
Enter [5/5] SVM name to check (press enter to skip):
Running check for svm svm_rate...
Running check for svm audit_svm...
Waiting 5 minutes for stat collection
Stopping sample svm_rate_sample
Stopping sample audit_svm_sample
fpolicy stats of svm svm_rate is saved in fpolicy_stat_svm_rate.log
Svm svm_rate is generating 100 SMB events/sec and 100 NFS events/sec
Overall svm svm_rate is generating 200 events/sec
fpolicy stats of svm audit_svm is saved in fpolicy_stat_audit_svm.log
Svm audit_svm is generating 200 SMB events/sec and 100 NFS events/sec
Overall svm audit_svm is generating 300 events/sec
....
 [root@ci-cs-data agent]#


== Risoluzione dei problemi

|===


| Domanda | Risposta 


| Se eseguo questo script su una SVM già configurata per Workload Security, utilizza semplicemente la configurazione fpolicy esistente sulla SVM oppure ne imposta una temporanea ed esegue il processo? | Event Rate Checker può funzionare correttamente anche per una SVM già configurata per Workload Security.  Non dovrebbe esserci alcun impatto. 


| Posso aumentare il numero di SVM su cui può essere eseguito lo script? | Sì. Basta modificare lo script e cambiare il numero massimo di SVM da 5 a qualsiasi numero desiderato. 


| Se aumento il numero di SVM, aumenterà il tempo di esecuzione dello script? | No. Lo script verrà eseguito per un massimo di 5 minuti, anche se il numero di SVM viene aumentato. 


| Posso aumentare il numero di SVM su cui può essere eseguito lo script? | Sì. È necessario modificare lo script e cambiare il numero massimo di SVM da 5 a qualsiasi numero desiderato. 


| Se aumento il numero di SVM, aumenterà il tempo di esecuzione dello script? | No. Lo script verrà eseguito per un massimo di 5 minuti, anche se il numero di SVM viene aumentato. 


| Cosa succede se eseguo Event Rate Checker con un agente esistente? | L'esecuzione di Event Rate Checker su un agente già esistente potrebbe causare un aumento della latenza sull'SVM.  Questo aumento sarà di natura temporanea mentre è in esecuzione Event Rate Checker. 
|===