---
sidebar: sidebar 
permalink: cs_intro.html 
keywords: CloudSecure, Cloud Secure 
summary: 'Proteggi i tuoi dati con il rilevamento delle minacce interne, la visibilità centralizzata su ambienti ibridi e l"apprendimento automatico avanzato di Storage Workload Security per il rilevamento delle anomalie e la conformità.' 
---
= Informazioni sulla sicurezza del carico di lavoro di archiviazione
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights Storage Workload Security (in precedenza Cloud Secure) aiuta a proteggere i tuoi dati con informazioni fruibili sulle minacce interne.  Fornisce visibilità e controllo centralizzati di tutti gli accessi ai dati aziendali negli ambienti cloud ibridi, per garantire il raggiungimento degli obiettivi di sicurezza e conformità.



== Visibilità

Ottieni visibilità e controllo centralizzati dell'accesso degli utenti ai dati aziendali critici archiviati in sede o nel cloud.

Sostituire gli strumenti e i processi manuali che non riescono a fornire una visibilità tempestiva e accurata dell'accesso e del controllo dei dati.  Workload Security funziona in modo esclusivo sia sui sistemi di archiviazione cloud che su quelli on-premise per fornirti avvisi in tempo reale sui comportamenti dannosi degli utenti.



== Protezione

Proteggi i dati aziendali dall'uso improprio da parte di utenti malintenzionati o compromessi tramite l'apprendimento automatico avanzato e il rilevamento delle anomalie.

Ti avvisa di eventuali accessi anomali ai dati tramite apprendimento automatico avanzato e rilevamento di anomalie nel comportamento dell'utente.



== Conformità

Garantisci la conformità aziendale verificando l'accesso dei dati utente ai dati aziendali critici archiviati in sede o nel cloud.
