---
sidebar: sidebar 
permalink: cs_notifications_email.html 
summary: Aggiunta di indirizzi e-mail per le notifiche degli avvisi di sicurezza del carico di lavoro. 
keywords: email, notifications, alerts, warnings, attacks 
---
= Configurazione delle notifiche e-mail per avvisi, avvertenze e stato di integrità dell'agente/collettore dell'origine dati
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Per configurare i destinatari degli avvisi di Workload Security, fare clic su *Amministrazione > Notifiche* e immettere un indirizzo e-mail nelle sezioni appropriate per ciascun destinatario.



== Avvisi e avvisi di potenziali attacchi

Per inviare notifiche di avviso di _Potenziale attacco_, inserisci gli indirizzi email dei destinatari nella sezione _Invia avvisi di potenziale attacco_.  Per ogni azione sull'avviso vengono inviate notifiche e-mail all'elenco dei destinatari dell'avviso.

Per inviare notifiche di _Avviso_, inserisci gli indirizzi email dei destinatari nella sezione _Invia avvisi di avviso_.



== Monitoraggio dello stato di salute dell'agente e del raccoglitore dati

È possibile monitorare lo stato di salute degli agenti e delle origini dati tramite notifiche.

Per ricevere notifiche nel caso in cui un agente o un raccoglitore di origini dati non funzioni, immettere gli indirizzi e-mail dei destinatari nella sezione _Avvisi sullo stato di integrità della raccolta dati_.

Tieni presente quanto segue:

* Gli avvisi sanitari verranno inviati solo dopo che l'agente/esattore avrà smesso di segnalare per almeno un'ora.
* Viene inviata una sola notifica e-mail ai destinatari previsti in un dato periodo di 24 ore, anche se l'agente o il raccoglitore dati sono disconnessi per un periodo di tempo più lungo.
* In caso di errore dell'agente, verrà inviato un avviso (non uno per ogni collettore).  L'e-mail conterrà un elenco di tutti gli SVM interessati.
* L'errore di raccolta di Active Directory viene segnalato come avviso; non influisce sul rilevamento di ransomware.
* L'elenco di configurazione introduttiva ora include una nuova fase _Configura notifiche e-mail_.




== Ricezione di notifiche di aggiornamento dell'agente e del raccoglitore dati

* Inserire l'ID e-mail in "Avvisi sanitari sulla raccolta dati".
* La casella di controllo "Abilita notifiche di aggiornamento" diventa abilitata.
* Le notifiche e-mail relative all'aggiornamento di Agent e Data Collector vengono inviate agli ID e-mail un giorno prima dell'aggiornamento pianificato.




== Risoluzione dei problemi

|===
| *Problema:* | *Prova questo:* 


| Gli ID e-mail sono presenti negli "Avvisi sullo stato di salute del Data Collector", tuttavia non ricevo notifiche. | Le email di notifica vengono inviate dal dominio NetApp Data Infrastructure Insights , ovvero da _accounts@service.cloudinsights.netapp.com_.  Alcune aziende bloccano le email in arrivo se provengono da un dominio esterno.  Assicurarsi che le notifiche esterne provenienti dai domini NetApp Data Infrastructure Insights siano inserite nella whitelist. 
|===