---
sidebar: sidebar 
permalink: forensic_user_overview.html 
keywords: Forensic, user, user, activity 
summary: dettaglio utente forense 
---
= Panoramica utente forense
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le informazioni per ciascun utente sono fornite nella Panoramica utente.  Utilizzare queste visualizzazioni per comprendere le caratteristiche degli utenti, le entità associate e le attività recenti.



== Profilo utente

Le informazioni del profilo utente includono le informazioni di contatto e la posizione dell'utente.  Il profilo fornisce le seguenti informazioni:

* Nome dell'utente
* Indirizzo email dell'utente
* Responsabile dell'utente
* Contatto telefonico per l'utente
* Posizione dell'utente




== Comportamento dell'utente

Le informazioni sul comportamento dell'utente identificano le attività e le operazioni recenti eseguite dall'utente.  Queste informazioni includono:

* Attività recenti
+
** Ultimo luogo di accesso
** Grafico delle attività
** Avvisi




* Operazioni degli ultimi sette giorni
+
** Numero di operazioni






== Intervallo di aggiornamento

L'elenco degli utenti viene aggiornato ogni 12 ore.



== Politica di conservazione

Se non viene aggiornato nuovamente, l'elenco degli utenti viene conservato per 13 mesi.  Dopo 13 mesi i dati verranno cancellati.  Se l'ambiente Workload Security viene eliminato, tutti i dati associati all'ambiente vengono eliminati.
