---
sidebar: sidebar 
permalink: forensic_alert_detail.html 
keywords: alert, Critical, Warning, Low, alert detail Synopsis, Time range, Start time, End time, user 
summary: 'dettagli dell"avviso' 
---
= Dettagli dell'avviso
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Facendo clic sulla sinossi di un avviso si apre la pagina che fornisce informazioni dettagliate sull'utente e sull'avviso che ha generato.



== La pagina Dettagli avviso mostra l'utente

Dettagli avviso fornisce informazioni sull'avviso selezionato nella pagina Avvisi.

* La gravità dell'allerta
* L'utente che ha generato l'avviso e il tipo di avviso:
+
** Accesso anomalo da parte dell'utente
** Accesso anomalo da parte della comunità
** Accesso anomalo da parte dell'utente nella comunità
** L'utente si è unito a molte comunità


* Data e ora in cui è stato rilevato l'avviso
* L'azione intrapresa
+
** In quarantena
** Altro
** Altro


* Lo stato dell'allerta
+
** Nuovo
** In corso
** Licenziato
** Risolto


* Variazione del tasso di attività dell'utente
+
** Attività tipiche orarie
** Attività orarie al momento dell'attivazione dell'allerta.
** Percentuale di variazione del tasso che ha causato l'avviso.


* Un grafico che mostra il tasso di attività medio storico e il tasso di attività che ha generato l'avviso.




=== Utente correlato

* Nome utente e titolo
* Dipartimento
* E-mail con un collegamento all'indirizzo e-mail
* Manager
* Telefono
* Posizione




=== Attività

Mostra l'attività dell'utente negli ultimi 7 giorni e l'ultima posizione da cui l'utente ha effettuato l'accesso.

* Attività:
+
** Leggere
** Altro
** Creare


* Numero totale di avvisi negli ultimi sette giorni.
* Numero totale di attività negli ultimi 7 giorni.


Fare clic su *Visualizza dettagli attività* per accederelink:forensic_activity_history["Cronologia delle attività"] dell'utente esaminato.
