---
sidebar: sidebar 
permalink: index.html 
summary: Benvenuti al portale della documentazione per Data Infrastructure Insights. 
keywords:  
---
= Documentazione Data Infrastructure Insights
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp Data Infrastructure Insights (in precedenza Cloud Insights) è uno strumento di monitoraggio dell'infrastruttura cloud che offre visibilità sull'intera infrastruttura. Con Data Infrastructure Insights puoi monitorare, risolvere i problemi e ottimizzare tutte le tue risorse, inclusi i tuoi cloud pubblici e i tuoi data center privati.



== Cosa può fare per me Data Infrastructure Insights ?

Data Infrastructure Insights fornisce un monitoraggio multicloud ibrido, garantendo l'osservabilità completa dell'infrastruttura e dei carichi di lavoro.

* Raccoglitori di dati per infrastrutture e carichi di lavoro eterogenei, incluso Kubernetes
* Collettore Telegraf aperto e API aperte per una facile integrazione
* Avvisi e notifiche completi
* Apprendimento automatico per informazioni intelligenti
* Ottimizzare l'utilizzo delle risorse
* Dashboard integrate o personalizzabili con filtri avanzati per ridurre al minimo il rumore di visualizzazione per rispondere alle domande
* Scopri lo stato di salute delle tue operazioni di archiviazione ONTAP 
* Proteggi la tua risorsa aziendale più preziosa – i dati – da manomissioni di file o attacchi di distruzione di dati


'''


== Iniziare

* Come faccio alink:task_cloud_insights_onboarding_1.html["*iniziamo*"] con Data Infrastructure Insights?
* Sono iscritto.  Adesso cosa faccio?link:task_getting_started_with_cloud_insights.html["Acquisizione dei dati"] link:concept_user_roles.html["Impostazione degli utenti"]
* Eccezionale!  Cosa succederà adesso?link:task_defining_annotations.html["Preparazione delle risorse: annotazione"] link:concept_querying_assets.html["Trovare le risorse desiderate: query"] link:concept_dashboards_overview.html["Visualizzare i dati desiderati: dashboard"] link:task_create_monitor.html["Monitoraggio e avvisi"] link:task_cs_getting_started.html["Protezione dei dati"]
* Questa è roba fantastica!  Sono pronto alink:concept_subscribing_to_cloud_insights.html["*iscriviti*"] .

