---
sidebar: sidebar 
permalink: insights_overview.html 
keywords: insight, greedy, degraded, impacted, impacting, impactful, impact, resources, consuming, workload, ttf, time to full, k8s, kubernetes, namespace 
summary: 'Gli approfondimenti ti offrono una panoramica sull"utilizzo delle risorse e sulle tendenze.' 
---
= Approfondimenti
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Gli approfondimenti consentono di analizzare aspetti quali l'utilizzo delle risorse e il modo in cui influisce su altre risorse, oppure di effettuare analisi del tempo di utilizzo completo.

Sono disponibili numerosi approfondimenti.  Vai su *Dashboard > Approfondimenti* per iniziare a esplorare. Puoi visualizzare gli Approfondimenti attivi (in corso di elaborazione) nella scheda principale, oppure gli Approfondimenti inattivi nella scheda _Approfondimenti inattivi_.  Gli Insight inattivi sono quelli che erano precedentemente attivi ma che non si verificano più.



== Tipi di intuizione



=== Risorse condivise sotto stress

I carichi di lavoro ad alto impatto possono ridurre le prestazioni di altri carichi di lavoro in una risorsa condivisa.  Ciò mette sotto stress la risorsa condivisa.  Data Infrastructure Insights fornisce strumenti che ti aiutano a esaminare la saturazione delle risorse e l'impatto sul tuo tenant.link:insights_shared_resources_under_stress.html["Saperne di più"]



=== Gli spazi dei nomi di Kubernetes stanno esaurendo lo spazio

Kubernetes Namespaces Running Out of Space Insight fornisce una panoramica dei carichi di lavoro sui namespace Kubernetes che rischiano di esaurire lo spazio, con una stima del numero di giorni rimanenti prima che ogni spazio si riempia.link:insights_k8s_namespaces_running_out_of_space.html["Saperne di più"]



=== Reclaim ONTAP Cold Storage

_Reclaim ONTAP Cold Storage_ Insight fornisce dati sulla capacità di raffreddamento, sui potenziali risparmi in termini di costi/energia e sulle azioni consigliate per i volumi sui sistemi ONTAP .link:insights_reclaim_ontap_cold_storage.html["Saperne di più"]


NOTE: Questa è una funzionalità di _Anteprima_ e potrebbe cambiare nel tempo man mano che vengono apportati miglioramenti. link:/concept_preview_features.html["Saperne di più"] Informazioni sulle funzionalità di Data Infrastructure Insights Preview.
