---
sidebar: sidebar 
permalink: pre-requisites_for_k8s_operator.html 
keywords: telegraf, installation, install, agent, telegraf agent, kubernetes, eks, operator, k8s 
summary: Data Infrastructure Insights supporta Telegraf come agente per la raccolta di dati di integrazione su Kubernetes. 
---
= Prima di installare o aggiornare NetApp Kubernetes Monitoring Operator
:hardbreaks:
:allow-uri-read: 
:nofooter: 


[role="lead"]
Leggere queste informazioni prima di installare o aggiornare illink:task_config_telegraf_agent_k8s.html["Operatore di monitoraggio Kubernetes"] .

|===
| Componente | Requisito 


| Versione di Kubernetes | Kubernetes v1.20 e versioni successive. 


| Distribuzioni Kubernetes | AWS Elastic Kubernetes Service (EKS) Azure Kubernetes Service (AKS) Google Kubernetes Engine (GKE) Red Hat OpenShift Rancher Kubernetes Engine (RKE) VMware Tanzu 


| Sistema operativo Linux | Data Infrastructure Insights non supporta i nodi in esecuzione con architettura Arm64.  Monitoraggio di rete: è necessario eseguire il kernel Linux versione 4.18.0 o successiva.  Photon OS non è supportato. 


| Etichette | Data Infrastructure Insights supporta il monitoraggio dei nodi Kubernetes che eseguono Linux, specificando un selettore di nodi Kubernetes che cerca le seguenti etichette Kubernetes su queste piattaforme: Kubernetes v1.20 e versioni successive: Kubernetes.io/os = linux Rancher + cattle.io come piattaforma di orchestrazione/Kubernetes: cattle.io/os = linux 


| Comandi | I comandi curl e kubectl devono essere disponibili; per risultati ottimali, aggiungili al PATH. 


| Connettività | kubectl cli è configurato per comunicare con il cluster K8s di destinazione e per avere connettività Internet con l'ambiente Data Infrastructure Insights .  Se durante l'installazione ci si trova dietro un proxy, seguire le istruzioni riportate nellink:task_config_telegraf_agent_k8s.html#configuring-proxy-support["Configurazione del supporto proxy"] sezione dell'installazione dell'operatore.  Per un audit e una segnalazione dei dati accurati, sincronizzare l'ora sulla macchina dell'agente utilizzando il protocollo NTP (Network Time Protocol) o il protocollo SNTP (Simple Network Time Protocol). 


| Altro | Se utilizzi OpenShift 4.6 o versione successiva, devi seguire le istruzionilink:task_config_telegraf_agent_k8s.html#openshift-instructions["Istruzioni OpenShift"] oltre a garantire che questi prerequisiti siano soddisfatti. 


| Token API | Se si sta ridistribuendo l'operatore (ovvero lo si sta aggiornando o sostituendo), non è necessario creare un nuovo token API; è possibile riutilizzare il token precedente. 
|===


== Cose importanti da notare prima di iniziare

Se stai correndo con un<<configuring-proxy-support,procuratore>> , avere un<<using-a-custom-or-private-docker-repository,repository personalizzato>> , o stanno usando<<openshift-instructions,OpenShift>> , leggere attentamente le seguenti sezioni.

Leggi anche su<<permessi,Permessi>> .



=== Configurazione del supporto proxy

Esistono due posizioni in cui è possibile utilizzare un proxy sul tenant per installare NetApp Kubernetes Monitoring Operator.  Possono essere gli stessi sistemi proxy o sistemi proxy separati:

* Proxy necessario durante l'esecuzione dello snippet di codice di installazione (utilizzando "curl") per connettere il sistema in cui viene eseguito lo snippet al tuo ambiente Data Infrastructure Insights
* Proxy necessario al cluster Kubernetes di destinazione per comunicare con l'ambiente Data Infrastructure Insights


Se si utilizza un proxy per uno o entrambi questi elementi, per installare NetApp Kubernetes Operating Monitor è necessario innanzitutto assicurarsi che il proxy sia configurato per consentire una buona comunicazione con l'ambiente Data Infrastructure Insights .  Ad esempio, dai server/VM da cui si desidera installare l'operatore, è necessario poter accedere a Data Infrastructure Insights e poter scaricare i file binari da Data Infrastructure Insights.

Per il proxy utilizzato per installare NetApp Kubernetes Operating Monitor, prima di installare l'operatore, impostare le variabili di ambiente _http_proxy/https_proxy_.  Per alcuni ambienti proxy, potrebbe essere necessario impostare anche la variabile di ambiente _no_proxy_.

Per impostare le variabili, eseguire i seguenti passaggi sul sistema *prima* di installare NetApp Kubernetes Monitoring Operator:

. Imposta le variabili di ambiente _https_proxy_ e/o _http_proxy_ per l'utente corrente:
+
.. Se il proxy da configurare non dispone di autenticazione (nome utente/password), eseguire il seguente comando:
+
 export https_proxy=<proxy_server>:<proxy_port>
.. Se il proxy da configurare dispone di autenticazione (nome utente/password), eseguire questo comando:
+
 export http_proxy=<proxy_username>:<proxy_password>@<proxy_server>:<proxy_port>




Per far sì che il proxy utilizzato per il cluster Kubernetes comunichi con l'ambiente Data Infrastructure Insights , installare NetApp Kubernetes Monitoring Operator dopo aver letto tutte queste istruzioni.

Configurare la sezione proxy di AgentConfiguration in operator-config.yaml prima di distribuire NetApp Kubernetes Monitoring Operator.

[listing]
----
agent:
  ...
  proxy:
    server: <server for proxy>
    port: <port for proxy>
    username: <username for proxy>
    password: <password for proxy>

    # In the noproxy section, enter a comma-separated list of
    # IP addresses and/or resolvable hostnames that should bypass
    # the proxy
    noproxy: <comma separated list>

    isTelegrafProxyEnabled: true
    isFluentbitProxyEnabled: <true or false> # true if Events Log enabled
    isCollectorsProxyEnabled: <true or false> # true if Network Performance and Map enabled
    isAuProxyEnabled: <true or false> # true if AU enabled
  ...
...
----


=== Utilizzo di un repository Docker personalizzato o privato

Per impostazione predefinita, NetApp Kubernetes Monitoring Operator estrarrà le immagini dei container dal repository Data Infrastructure Insights .  Se si utilizza un cluster Kubernetes come destinazione per il monitoraggio e tale cluster è configurato per estrarre immagini di container solo da un repository Docker personalizzato o privato o da un registro di container, è necessario configurare l'accesso ai container necessari all'operatore di monitoraggio NetApp Kubernetes.

Eseguire "Image Pull Snippet" dal riquadro di installazione di NetApp Monitoring Operator.  Questo comando effettuerà l'accesso al repository Data Infrastructure Insights , estrarrà tutte le dipendenze delle immagini per l'operatore e uscirà dal repository Data Infrastructure Insights .  Quando richiesto, immettere la password temporanea del repository fornita.  Questo comando scarica tutte le immagini utilizzate dall'operatore, comprese quelle per le funzionalità opzionali.  Di seguito sono riportate le funzioni per cui vengono utilizzate queste immagini.

Funzionalità dell'operatore principale e monitoraggio di Kubernetes

* monitoraggio netapp
* kube-rbac-proxy
* metriche dello stato di Kube
* telegrafo
* utente root senza distribuzione


Registro eventi

* fluente-bit
* esportatore di eventi kubernetes


Prestazioni e mappa della rete

* ci-net-observer


Invia l'immagine Docker dell'operatore al tuo repository Docker privato/locale/aziendale in base alle policy aziendali.  Assicurati che i tag delle immagini e i percorsi delle directory di queste immagini nel tuo repository siano coerenti con quelli nel repository Data Infrastructure Insights .

Modifica la distribuzione monitoring-operator in operator-deployment.yaml e modifica tutti i riferimenti alle immagini per utilizzare il tuo repository Docker privato.

....
image: <docker repo of the enterprise/corp docker repo>/kube-rbac-proxy:<kube-rbac-proxy version>
image: <docker repo of the enterprise/corp docker repo>/netapp-monitoring:<version>
....
Modifica AgentConfiguration in operator-config.yaml per riflettere la nuova posizione del repository Docker.  Crea un nuovo imagePullSecret per il tuo repository privato, per maggiori dettagli consulta _https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/_

[listing]
----
agent:
  ...
  # An optional docker registry where you want docker images to be pulled from as compared to CI's docker registry
  # Please see documentation for link:task_config_telegraf_agent_k8s.html#using-a-custom-or-private-docker-repository[using a custom or private docker repository].
  dockerRepo: your.docker.repo/long/path/to/test
  # Optional: A docker image pull secret that maybe needed for your private docker registry
  dockerImagePullSecret: docker-secret-name
----


=== Istruzioni OpenShift

Se utilizzi OpenShift 4.6 o versione successiva, devi modificare AgentConfiguration in _operator-config.yaml_ per abilitare l'impostazione _runPrivileged_:

....
# Set runPrivileged to true SELinux is enabled on your kubernetes nodes
runPrivileged: true
....
Openshift potrebbe implementare un livello di sicurezza aggiuntivo che potrebbe bloccare l'accesso ad alcuni componenti di Kubernetes.



=== Permessi

Se il cluster che stai monitorando contiene risorse personalizzate che non hanno un ClusterRole chelink:https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles["aggregati da visualizzare"] , sarà necessario concedere manualmente all'operatore l'accesso a queste risorse per monitorarle con i registri eventi.

. Modificare _operator-additional-permissions.yaml_ prima dell'installazione oppure, dopo l'installazione, modificare la risorsa _ClusterRole/<namespace>-additional-permissions_
. Crea una nuova regola per gli apiGroup e le risorse desiderati con i verbi ["get", "watch", "list"].  Vedi \ https://kubernetes.io/docs/reference/access-authn-authz/rbac/
. Applica le modifiche al cluster

