---
sidebar: sidebar 
permalink: reporting_creating_custom_reports.html 
summary: 'Utilizzo di strumenti di creazione di report per creare report personalizzati ("ad hoc")' 
keywords: reporting, cognos, data warehouse, dwh, ad-hoc, custom 
---
= Creazione di report personalizzati
:hardbreaks:
:allow-uri-read: 


[role="lead"]
È possibile utilizzare gli strumenti di creazione dei report per creare report personalizzati.  Dopo aver creato i report, è possibile salvarli ed eseguirli regolarmente.  I risultati dei report possono essere inviati automaticamente via e-mail a te stesso e ad altri.


NOTE: La funzionalità di reporting è disponibile in Data Infrastructure Insightslink:concept_subscribing_to_cloud_insights.html["Edizione Premium"] .

Gli esempi in questa sezione mostrano il seguente processo, che può essere utilizzato per qualsiasi modello di dati di Data Infrastructure Insights Reporting:

* Identificare una domanda a cui rispondere con un report
* Determinazione dei dati necessari a supporto dei risultati
* Selezione degli elementi dati per il report


Prima di progettare il tuo report personalizzato, devi completare alcune attività preliminari.  Se non si compilano queste informazioni, i report potrebbero risultare inaccurati o incompleti.

Ad esempio, se non si completa il processo di identificazione del dispositivo, i report sulla capacità non saranno accurati.  Oppure, se non completi l'impostazione delle annotazioni (ad esempio livelli, unità aziendali e data center), i tuoi report personalizzati potrebbero non riportare accuratamente i dati nel tuo dominio o potrebbero mostrare "N/D" per alcuni punti dati.

Prima di progettare i report, completa le seguenti attività:

* Configura tuttolink:task_configure_data_collectors.html["raccoglitori di dati"] correttamente.
* Inserisci annotazioni (ad esempio livelli, data center e unità aziendali) sui dispositivi e sulle risorse del tuo tenant.  È utile disporre di annotazioni stabili prima di generare report, perché Data Infrastructure Insights Reporting raccoglie informazioni storiche.




== Processo di creazione del report

Il processo di creazione di report personalizzati (chiamati anche "ad hoc") prevede diverse attività:

* Pianifica i risultati del tuo report.
* Identifica i dati a supporto dei tuoi risultati.
* Selezionare il modello di dati (ad esempio, modello di dati di addebito, modello di dati di inventario e così via) che contiene i dati.
* Selezionare gli elementi dati per il report.
* Facoltativamente, formattare, ordinare e filtrare i risultati del report.




=== Pianificazione dei risultati del report personalizzato

Prima di aprire gli strumenti di creazione del report, potrebbe essere opportuno pianificare i risultati che si desidera ottenere dal report.  Con gli strumenti di creazione di report, è possibile creare report facilmente e potrebbe non essere necessaria una grande pianificazione; tuttavia, è una buona idea chiedere al richiedente del report quali siano i requisiti del report.

* Individua la domanda esatta a cui vuoi rispondere. Per esempio:
+
** Quanta capacità mi rimane?
** Quali sono i costi di chargeback per unità aziendale?
** Qual è la capacità per livello per garantire che le unità aziendali siano allineate al livello di archiviazione appropriato?
** Come posso prevedere i requisiti di alimentazione e raffreddamento?  (Aggiungi metadati personalizzati inserendo annotazioni alle risorse.)


* Identifica gli elementi dati necessari a supportare la risposta.
* Identifica le relazioni tra i dati che vuoi vedere nella risposta.  Non includere relazioni illogiche nella tua domanda, ad esempio "Voglio vedere le porte correlate alla capacità".
* Identificare eventuali calcoli necessari sui dati.
* Determinare quali tipi di filtraggio sono necessari per limitare i risultati.
* Determina se devi utilizzare dati attuali o storici.
* Determina se è necessario impostare privilegi di accesso sui report per limitare i dati a un pubblico specifico.
* Definire come verrà distribuito il report.  Ad esempio, dovrebbe essere inviato tramite e-mail secondo una pianificazione prestabilita o incluso nell'area della cartella dei contenuti del team?
* Stabilire chi si occuperà della manutenzione del rapporto.  Ciò potrebbe influire sulla complessità del progetto.
* Creare un mockup del report.




=== Suggerimenti per la progettazione di report

Quando si progettano report, potrebbero essere utili alcuni suggerimenti.

* Determina se devi utilizzare dati attuali o storici.
+
La maggior parte dei report deve riportare solo i dati più recenti disponibili in Data Infrastructure Insights.

* Data Infrastructure Insights Reporting fornisce informazioni storiche sulla capacità e sulle prestazioni, ma non sull'inventario.
* Tutti possono vedere tutti i dati; tuttavia, potrebbe essere necessario limitare i dati a un pubblico specifico.
+
Per segmentare le informazioni per diversi utenti, è possibile creare report e impostare per ciascuno di essi le autorizzazioni di accesso.





== Modelli di dati di reporting

Data Infrastructure Insights include diversi modelli di dati dai quali è possibile selezionare report predefiniti o creare report personalizzati.

Ogni modello di dati contiene un data mart semplice e un data mart avanzato:

* Il data mart semplice fornisce un rapido accesso agli elementi dati più comunemente utilizzati e include solo l'ultima istantanea dei dati del Data Warehouse; non include dati storici.
* Il data mart avanzato fornisce tutti i valori e i dettagli disponibili nel data mart semplice e include l'accesso ai valori dei dati storici.




=== Modelli di dati di capacità

Consente di rispondere a domande sulla capacità di archiviazione, sull'utilizzo del file system, sulla capacità del volume interno, sulla capacità delle porte, sulla capacità di qtree e sulla capacità della macchina virtuale (VM).  Il modello di dati di capacità è un contenitore per diversi modelli di dati di capacità.  Utilizzando questo modello di dati è possibile creare report che rispondano a vari tipi di domande:



==== Modello di dati di archiviazione e capacità del pool di archiviazione

Consente di rispondere a domande sulla pianificazione delle risorse di capacità di archiviazione, inclusi storage e pool di archiviazione, e include dati di pool di archiviazione sia fisici che virtuali.  Questo semplice modello di dati può aiutarti a rispondere a domande relative alla capacità sul pavimento e all'utilizzo della capacità dei pool di archiviazione per livello e data center nel tempo.  Se non hai familiarità con i report sulla capacità, dovresti iniziare con questo modello di dati perché è un modello di dati più semplice e mirato.  Utilizzando questo modello di dati è possibile rispondere a domande simili alle seguenti:

* Qual è la data prevista per il raggiungimento della soglia di capacità dell'80% del mio spazio di archiviazione fisico?
* Qual è la capacità di archiviazione fisica di un array per un dato livello?
* Qual è la mia capacità di archiviazione in base al produttore, alla famiglia e al data center?
* Qual è l'andamento dell'utilizzo dello storage su un array per tutti i livelli?
* Quali sono i miei 10 sistemi di storage con il maggiore utilizzo?
* Qual è l'andamento dell'utilizzo dello storage nei pool di storage?
* Quanta capacità è già stata assegnata?
* Quale capacità è disponibile per l'assegnazione?




==== Modello di dati di utilizzo del file system

Questo modello di dati fornisce visibilità sull'utilizzo della capacità da parte degli host a livello di file system.  Gli amministratori possono determinare la capacità allocata e utilizzata per ogni file system, determinare il tipo di file system e identificare le statistiche di tendenza in base al tipo di file system.  Utilizzando questo modello di dati è possibile rispondere alle seguenti domande:

* Qual è la dimensione del file system?
* Dove vengono conservati i dati e come vengono consultati, ad esempio in locale o in SAN?
* Quali sono le tendenze storiche per la capacità del file system?  Quindi, sulla base di ciò, cosa possiamo prevedere per le esigenze future?




==== Modello di dati di capacità del volume interno

Consente di rispondere a domande sulla capacità utilizzata del volume interno, sulla capacità assegnata e sull'utilizzo della capacità nel tempo:

* Quali volumi interni hanno un utilizzo superiore a una soglia predefinita?
* Quali volumi interni rischiano di esaurire la capacità in base a un trend?  8 Qual è la capacità utilizzata rispetto alla capacità assegnata sui nostri volumi interni?




==== Modello di dati sulla capacità del porto

Consente di rispondere a domande sulla connettività delle porte dello switch, sullo stato delle porte e sulla velocità delle porte nel tempo.  Puoi rispondere a domande simili alle seguenti per aiutarti a pianificare l'acquisto di nuovi switch: Come posso creare una previsione del consumo di porte che preveda la disponibilità delle risorse (porte) (in base al data center, al fornitore dello switch e alla velocità della porta)?

* Quali porte rischiano di esaurire la loro capacità, in base alla velocità dei dati, al data center, al fornitore e al numero di porte host e di archiviazione?
* Quali sono le tendenze nel tempo della capacità delle porte degli switch?
* Quali sono le velocità delle porte?
* Quale tipo di capacità portuale è necessaria e quale organizzazione sta per esaurire un certo tipo di porto o fornitore?
* Qual è il momento ottimale per acquistare tale capacità e renderla disponibile?




==== Modello di dati di capacità Qtree

Consente di tracciare l'andamento dell'utilizzo di qtree (con dati quali la capacità utilizzata rispetto a quella assegnata) nel tempo.  È possibile visualizzare le informazioni in base a diverse dimensioni, ad esempio per entità aziendale, applicazione, livello e livello di servizio.  Utilizzando questo modello di dati è possibile rispondere alle seguenti domande:

* Qual è la capacità utilizzata per i qtree rispetto ai limiti impostati per applicazione o entità aziendale?
* Quali sono le tendenze della nostra capacità utilizzata e libera in modo da poter pianificare la capacità?
* Quali entità aziendali stanno utilizzando la maggiore capacità?
* Quali applicazioni consumano più capacità?




==== Modello di dati di capacità della VM

Consente di segnalare l'ambiente virtuale e l'utilizzo della sua capacità.  Questo modello di dati consente di segnalare le variazioni nell'utilizzo della capacità nel tempo per VM e archivi dati.  Il modello di dati fornisce anche dati di thin provisioning e di chargeback delle macchine virtuali.

* Come posso determinare il chargeback della capacità in base alla capacità fornita alle VM e agli archivi dati?
* Quale capacità non viene utilizzata dalle VM e quale parte inutilizzata è libera, orfana o altro?
* Cosa dobbiamo acquistare in base alle tendenze di consumo?
* Quali risparmi in termini di efficienza di storage si ottengono utilizzando le tecnologie di thin provisioning e deduplicazione dello storage?


Le capacità nel modello di dati VM Capacity vengono ricavate dai dischi virtuali (VMDK).  Ciò significa che la dimensione fornita di una VM utilizzando il modello di dati Capacità VM è la dimensione dei suoi dischi virtuali.  Questa è diversa dalla capacità fornita nella vista Macchine virtuali in Data Infrastructure Insights, che mostra la dimensione fornita per la VM stessa.



==== Modello di dati di capacità del volume

Consente di analizzare tutti gli aspetti dei volumi sul tenant e di organizzare i dati in base a fornitore, modello, livello, livello di servizio e data center.

È possibile visualizzare la capacità relativa ai volumi orfani, ai volumi inutilizzati e ai volumi di protezione (utilizzati per la replica).  È inoltre possibile visualizzare diverse tecnologie di volume (iSCSI o FC) e confrontare volumi virtuali con volumi non virtuali per problemi di virtualizzazione degli array.

Con questo modello di dati puoi rispondere a domande simili alle seguenti:

* Quali volumi hanno un utilizzo superiore a una soglia predefinita?
* Qual è la tendenza nel mio data center per quanto riguarda la capacità dei volumi orfani?
* Quanta capacità del mio data center è virtualizzata o sottoposta a thin provisioning?
* Quanta capacità del mio data center deve essere riservata alla replica?




=== Modello di dati di addebito

Consente di rispondere a domande sulla capacità utilizzata e sulla capacità allocata sulle risorse di archiviazione (volumi, volumi interni e qtree).  Questo modello di dati fornisce informazioni sulla capacità di storage e sulla responsabilità per host, applicazioni ed entità aziendali e include sia dati attuali che storici.  I dati del report possono essere classificati in base al livello di servizio e al livello di archiviazione.

È possibile utilizzare questo modello di dati per generare report di addebito in conto individuando la quantità di capacità utilizzata da un'entità aziendale.  Questo modello di dati consente di creare report unificati di più protocolli (tra cui NAS, SAN, FC e iSCSI).

* Per l'archiviazione senza volumi interni, i report di addebito mostrano l'addebito in base ai volumi.
* Per l'archiviazione con volumi interni:
+
** Se le entità aziendali sono assegnate ai volumi, i report di addebito mostrano l'addebito in base ai volumi.
** Se le entità aziendali non sono assegnate ai volumi ma ai qtree, i report di addebito mostrano l'addebito per qtree.
** Se le entità aziendali non sono assegnate a volumi e non sono assegnate a qtree, i report di addebito mostrano il volume interno.
** La decisione se visualizzare il chargeback per volume, qtree o volume interno viene presa per ciascun volume interno, quindi è possibile che diversi volumi interni nello stesso pool di archiviazione visualizzino il chargeback a livelli diversi.




I dati sulla capacità vengono eliminati dopo un intervallo di tempo predefinito.  Per maggiori dettagli, vedere Processi del Data Warehouse.

I report che utilizzano il modello dati Chargeback potrebbero visualizzare valori diversi rispetto ai report che utilizzano il modello dati Storage Capacity.

* Per gli array di storage che non sono sistemi di storage NetApp , i dati di entrambi i modelli di dati sono gli stessi.
* Per i sistemi di storage NetApp e Celerra, il modello di dati Chargeback utilizza un singolo livello (di volumi, volumi interni o qtree) per basare i propri addebiti, mentre il modello di dati Storage Capacity utilizza più livelli (di volumi e volumi interni) per basare i propri addebiti.




=== Modello di dati di inventario

Consente di rispondere a domande sulle risorse di inventario, tra cui host, sistemi di archiviazione, switch, dischi, nastri, qtree, quote, macchine virtuali e server e dispositivi generici.  Il modello di dati Inventory include diversi sottomart che consentono di visualizzare informazioni su repliche, percorsi FC, percorsi iSCSI, percorsi NFS e violazioni.  Il modello di dati di inventario non include dati storici.  Domande a cui puoi rispondere con questi dati

* Quali beni ho e dove sono?
* Chi utilizza le risorse?
* Che tipo di dispositivi ho e quali sono i componenti di tali dispositivi?
* Quanti host ho per sistema operativo e quante porte ci sono su quegli host?
* Quali array di storage per fornitore sono presenti in ciascun data center?
* Quanti switch per fornitore ho in ogni data center?
* Quanti porti non sono autorizzati?
* Quali nastri del fornitore stiamo utilizzando e quante porte sono presenti su ciascun nastro? Sono stati identificati tutti i dispositivi generici prima di iniziare a lavorare sui report?
* Quali sono i percorsi tra host e volumi di archiviazione o nastri?
* Quali sono i percorsi tra dispositivi generici e volumi di archiviazione o nastri?
* Quante violazioni di ogni tipo ho per data center?
* Per ogni volume replicato, quali sono i volumi di origine e di destinazione?
* Ci sono incompatibilità di firmware o discrepanze di velocità delle porte tra gli HBA host Fibre Channel e gli switch?




=== Modello di dati sulle prestazioni

Consente di rispondere a domande sulle prestazioni di volumi, volumi applicativi, volumi interni, switch, applicazioni, VM, VMDK, ESX rispetto a VM, host e nodi applicativi.  Molti di questi riportano dati _orari_, dati _giornalieri_ o entrambi.  Utilizzando questo modello di dati, è possibile creare report che rispondono a diversi tipi di domande sulla gestione delle prestazioni:

* Quali volumi o volumi interni non sono stati utilizzati o consultati durante un periodo specifico?
* Possiamo individuare eventuali errori di configurazione per l'archiviazione di un'applicazione (non utilizzata)?
* Qual era il modello generale di comportamento di accesso per un'applicazione?
* I volumi a livelli sono assegnati in modo appropriato per una determinata applicazione?
* Potremmo utilizzare uno spazio di archiviazione più economico per un'applicazione attualmente in esecuzione senza compromettere le prestazioni dell'applicazione?
* Quali sono le applicazioni che generano più accessi allo storage attualmente configurato?


Utilizzando le tabelle delle prestazioni dello switch, è possibile ottenere le seguenti informazioni:

* Il traffico del mio host attraverso le porte connesse è bilanciato?
* Quali switch o porte presentano un numero elevato di errori?
* Quali sono gli switch più utilizzati in base alle prestazioni delle porte?
* Quali sono gli switch sottoutilizzati in base alle prestazioni delle porte?
* Qual è l'andamento della produttività dell'host in base alle prestazioni della porta?
* Qual è stato l'utilizzo delle prestazioni negli ultimi X giorni per un host, un sistema di archiviazione, un nastro o uno switch specificato?
* Quali dispositivi producono traffico su uno switch specifico (ad esempio, quali dispositivi sono responsabili dell'utilizzo di uno switch molto utilizzato)?
* Qual è la produttività di una specifica unità aziendale nel nostro ambiente?


Utilizzando le tabelle delle prestazioni del disco, è possibile ottenere le seguenti informazioni:

* Qual è la produttività per un pool di archiviazione specificato in base ai dati sulle prestazioni del disco?
* Qual è il pool di archiviazione più utilizzato?
* Qual è l'utilizzo medio del disco per uno specifico storage?
* Qual è la tendenza di utilizzo di un sistema di archiviazione o di un pool di archiviazione in base ai dati sulle prestazioni del disco?
* Qual è l'andamento dell'utilizzo del disco per uno specifico pool di archiviazione?


Quando si utilizzano le tabelle delle prestazioni VM e VMDK, è possibile ottenere le seguenti informazioni:

* Il mio ambiente virtuale funziona in modo ottimale?
* Quali VMDK segnalano i carichi di lavoro più elevati?
* Come posso utilizzare le prestazioni segnalate dai VMD mappati su diversi datastore per prendere decisioni sulla riorganizzazione in livelli?


Il modello di dati Performance include informazioni che aiutano a determinare l'adeguatezza dei livelli, le configurazioni errate di archiviazione per le applicazioni e gli orari dell'ultimo accesso dei volumi e dei volumi interni.  Questo modello di dati fornisce dati quali tempi di risposta, IOPS, throughput, numero di scritture in sospeso e stato di accesso.



=== Modello di dati di efficienza di archiviazione

Consente di monitorare il punteggio e il potenziale di efficienza dello storage nel tempo.  Questo modello di dati memorizza le misurazioni non solo della capacità fornita, ma anche della quantità utilizzata o consumata (la misurazione fisica).  Ad esempio, quando è abilitato il thin provisioning, Data Infrastructure Insights indica quanta capacità viene utilizzata dal dispositivo.  È possibile utilizzare questo modello anche per determinare l'efficienza quando la deduplicazione è abilitata.  Utilizzando il data mart Storage Efficiency è possibile rispondere a diverse domande:

* Quali sono i risparmi in termini di efficienza di storage ottenuti grazie all'implementazione di tecnologie di thin provisioning e deduplicazione?
* Quali sono i risparmi di spazio di archiviazione nei data center?
* In base ai trend storici della capacità, quando è necessario acquistare ulteriore spazio di archiviazione?
* Quale sarebbe il guadagno di capacità se abilitassimo tecnologie come il thin provisioning e la deduplicazione?
* Per quanto riguarda la capacità di archiviazione, sono a rischio adesso?




=== Tabelle dei fatti e delle dimensioni del modello di dati

Ogni modello di dati include sia tabelle dei fatti che tabelle delle dimensioni.

* Tabelle dei fatti: contengono dati misurati, ad esempio quantità, capacità grezza e utilizzabile.  Contiene chiavi esterne per le tabelle delle dimensioni.
* Tabelle dimensionali: contengono informazioni descrittive sui fatti, ad esempio data center e unità aziendali.  Una dimensione è una struttura, spesso composta da gerarchie, che categorizza i dati.  Gli attributi dimensionali aiutano a descrivere i valori dimensionali.


Utilizzando attributi di dimensione diversi o multipli (visualizzati come colonne nei report), è possibile creare report che accedono ai dati per ciascuna dimensione descritta nel modello di dati.



=== Colori utilizzati negli elementi del modello dati

I colori sugli elementi del modello dati hanno indicazioni diverse.

* Risorse gialle: rappresentano le misurazioni.
* Risorse non gialle: rappresentano attributi.  Questi valori non si sommano.




=== Utilizzo di più modelli di dati in un unico report

In genere, si utilizza un modello di dati per report.  Tuttavia, è possibile scrivere un report che combini dati provenienti da più modelli di dati.

Per scrivere un report che combina dati provenienti da più modelli di dati, scegli uno dei modelli di dati da utilizzare come base, quindi scrivi query SQL per accedere ai dati dai data mart aggiuntivi.  È possibile utilizzare la funzionalità SQL Join per combinare i dati provenienti da diverse query in un'unica query che è possibile utilizzare per scrivere il report.

Ad esempio, supponiamo di voler conoscere la capacità corrente di ogni array di archiviazione e di voler acquisire annotazioni personalizzate sugli array.  È possibile creare il report utilizzando il modello di dati Capacità di archiviazione.  È possibile utilizzare gli elementi delle tabelle Capacità corrente e Dimensioni e aggiungere una query SQL separata per accedere alle informazioni sulle annotazioni nel modello di dati Inventario.  Infine, è possibile combinare i dati collegando i dati di archiviazione dell'inventario alla tabella delle dimensioni di archiviazione utilizzando il nome dell'archiviazione e i criteri di unione.
