---
sidebar: sidebar 
permalink: reporting_overview.html 
summary: Report predefiniti e personalizzati dei tuoi dati con Data Infrastructure Insights. 
keywords: reporting, cognos, data warehouse, dwh 
---
= Panoramica dei report di Data Infrastructure Insights Insights
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il reporting di Data Infrastructure Insights è uno strumento di business intelligence che consente di visualizzare report predefiniti o di creare report personalizzati.


NOTE: La funzionalità di reporting è disponibile in Data Infrastructure Insightslink:concept_subscribing_to_cloud_insights.html["Edizione Premium"] .  La disponibilità della funzionalità di reporting è soggetta a un requisito di ingombro minimo. link:https://www.netapp.com/forms/cloud-insights-contact-us/["Contatta il tuo rappresentante commerciale NetApp"] per maggiori informazioni.

Con i report di Data Infrastructure Insights puoi svolgere le seguenti attività:

* Esegui un report predefinito
* Crea un report personalizzato
* Personalizza il formato e il metodo di consegna di un report
* Pianifica l'esecuzione automatica dei report
* Rapporti via e-mail
* Utilizzare i colori per rappresentare le soglie sui dati


Data Infrastructure Insights Reporting può generare report personalizzati per aree quali chargeback, analisi dei consumi e previsioni e può aiutare a rispondere a domande come le seguenti:

* Che inventario ho?
* Dov'è il mio inventario?
* Chi utilizza i nostri beni?
* A cosa si riferisce il chargeback per lo spazio di archiviazione assegnato a un'unità aziendale?
* Quanto tempo ci vorrà prima che io abbia bisogno di acquisire ulteriore capacità di archiviazione?
* Le unità aziendali sono allineate lungo i livelli di archiviazione appropriati?
* Come cambia l'allocazione dello spazio di archiviazione nel corso di un mese, un trimestre o un anno?




== Accesso ai report Data Infrastructure Insights

È possibile accedere a Data Infrastructure Insights Reporting facendo clic sul collegamento *Report* nel menu.

Verrai indirizzato all'interfaccia di reporting.  Data Infrastructure Insights utilizza IBM Cognos Analytics per il suo motore di reporting.



== Che cos'è ETL?

Quando si lavora con la creazione di report, si sentiranno i termini "Data Warehouse" ed "ETL".  ETL è l'acronimo di "Extract, Transform, and Load".  Il processo ETL recupera i dati raccolti in Data Infrastructure Insights e li trasforma in un formato utilizzabile nella creazione di report.  Per "Data Warehouse" si intendono i dati raccolti disponibili per la creazione di report.

Il processo ETL comprende i seguenti processi individuali:

* *Estratto*: estrae i dati da Data Infrastructure Insights.
* *Trasforma*: applica regole o funzioni logiche aziendali ai dati così come vengono estratti da Data Infrastructure Insights.
* *Carica*: salva i dati trasformati nel data warehouse per utilizzarli nella creazione di report.

