---
sidebar: sidebar 
permalink: security_information_and_region.html 
summary: 'Data Infrastructure Insights segue le Best practice per la sicurezza durante l"intero ciclo di vita del rilascio.' 
keywords: security, risk, protection 
---
= Informazioni e Regione
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NetApp prende molto sul serio la sicurezza delle informazioni dei clienti. Ecco come e dove Data Infrastructure Insights memorizza le tue informazioni.



== Quali informazioni vengono memorizzate da Data Infrastructure Insights?

Data Infrastructure Insights memorizza le seguenti informazioni:

* Dati sulle performance
+
I dati sulle performance sono dati Time-Series che forniscono informazioni sulle performance del dispositivo/origine monitorato. Ad esempio, il numero di iOS forniti da un sistema di storage, il throughput di una porta FibreChannel, il numero di pagine inviate da un server Web, il tempo di risposta di un database e molto altro ancora.

* Dati di inventario
+
I dati di inventario sono costituiti da metadati che descrivono il dispositivo/origine monitorato e il modo in cui sono configurati. Ad esempio, le versioni hardware e software installate, i dischi e le LUN in un sistema di storage, i core della CPU, la RAM e i dischi di una macchina virtuale, gli spazi delle tabelle di un database, il numero e il tipo di porte su uno switch SAN, i nomi di directory/file (se la protezione del carico di lavoro dello storage è attivata) e così via

* Dati di configurazione
+
In questo modo vengono riepilogati i dati di configurazione forniti dal cliente utilizzati per gestire l'inventario e le operazioni del cliente, ad esempio nomi host o indirizzi IP dei dispositivi monitorati, intervalli di polling, valori di timeout, ecc.

* Segreti
+
I segreti sono costituiti dalle credenziali utilizzate dall'unità di acquisizione di Data Infrastructure Insights per accedere ai dispositivi e ai servizi del cliente. Queste credenziali vengono crittografate utilizzando una crittografia asimmetrica avanzata e le chiavi private vengono memorizzate solo sulle unità di acquisizione e non escono mai dall'ambiente del cliente. Anche gli SRE privilegiati di Data Infrastructure Insights non sono in grado di accedere ai segreti dei clienti in testo normale a causa di questa progettazione.

* Dati funzionali
+
Si tratta di dati generati in seguito alla fornitura da parte di NetApp del Cloud Data Service, che informa NetApp sullo sviluppo, l'implementazione, le operazioni, la manutenzione e la protezione del Cloud Data Service. I dati funzionali non contengono informazioni sul cliente o informazioni personali.

* Dati di accesso dell'utente
+
Informazioni sull'autenticazione e sull'accesso che consentono a NetApp BlueXP  di comunicare con i siti regionali di Data Infrastructure Insights, inclusi i dati relativi all'autorizzazione dell'utente.

* Storage workload Security User Directory Data
+
Nei casi in cui la funzionalità workload Security è attivata E il cliente sceglie di attivare User Directory Collector, il sistema memorizza i nomi degli utenti, gli indirizzi e-mail aziendali e altre informazioni raccolte da Active Directory.




NOTE: I dati della directory utente si riferiscono alle informazioni della directory utente raccolte dal collettore di dati della directory utente di sicurezza del carico di lavoro, non ai dati sugli utenti di Data Infrastructure Insights/workload Security.

*Nessun dato personale esplicito* viene raccolto dalle risorse dell'infrastruttura e dei servizi. Le informazioni raccolte comprendono solo metriche delle performance, informazioni di configurazione e metadati dell'infrastruttura, come molti case telefoniche dei vendor, tra cui il supporto automatico di NetApp e ActiveIQ. Tuttavia, a seconda delle convenzioni di denominazione di un cliente, i dati per condivisioni, volumi, macchine virtuali, qtree, le applicazioni, ecc. possono contenere informazioni di identificazione personale.

Se la sicurezza del carico di lavoro è attivata, il sistema esamina inoltre i nomi di file e directory su SMB o altre condivisioni, che potrebbero contenere informazioni di identificazione personale. Se i clienti abilitano il servizio di raccolta directory utente per la protezione del workload (che essenzialmente mappa i SID di Windows ai nomi utente tramite Active Directory), il nome visualizzato, l'indirizzo e-mail aziendale e gli eventuali attributi aggiuntivi selezionati verranno raccolti e memorizzati da Data Infrastructure Insights.

Inoltre, i registri di accesso a Data Infrastructure Insights sono gestiti e contengono gli indirizzi IP e e e-mail degli utenti utilizzati per accedere al servizio.



== Dove sono memorizzate le mie informazioni?

Data Infrastructure Insights memorizza le informazioni in base all'area in cui viene creato l'ambiente.

Nella regione host vengono memorizzate le seguenti informazioni:

* Telemetria e informazioni su asset/oggetti, inclusi contatori e metriche delle performance
* Informazioni sull'unità di acquisizione
* Dati funzionali
* Informazioni di controllo sulle attività degli utenti all'interno di Data Infrastructure Insights
* Sicurezza del carico di lavoro informazioni su Active Directory
* Informazioni sulla verifica della sicurezza del carico di lavoro


Le seguenti informazioni risiedono negli Stati Uniti, indipendentemente dalla regione in cui risiede l'ambiente Data Infrastructure Insights:

* Informazioni sul sito dell'ambiente (talvolta chiamate "tenant"), come il proprietario del sito o dell'account.
* Informazioni che consentono a NetApp BlueXP  di comunicare con i siti regionali di approfondimento sull'infrastruttura dati, incluso qualsiasi cosa fare con l'autorizzazione dell'utente.
* Informazioni relative alla relazione tra l'utente di Data Infrastructure Insights e il tenant.




=== Regioni host

Le regioni host includono:

* USA: US-est-1
* EMEA: eu-Central-1
* APAC: ap-sud-est-2




== Ulteriori informazioni

Per ulteriori informazioni sulla privacy e la sicurezza di NetApp, consultare i seguenti link:

* link:https://www.netapp.com/us/company/trust-center/index.aspx["Trust Center"]
* link:https://www.netapp.com/us/company/trust-center/privacy/data-location-cross-border-transfers.aspx["Trasferimenti di dati transfrontalieri"]
* link:https://www.netapp.com/us/company/trust-center/privacy/bcr-binding-corporate-rules.aspx["Regole aziendali vincolanti"]
* link:https://www.netapp.com/us/company/trust-center/transparency/third-party-data-requests.aspx["Risposta a richieste di dati di terze parti"]
* link:https://www.netapp.com/us/company/trust-center/privacy/privacy-principles-security-safeguards.aspx["Principi di privacy di NetApp"]

