---
sidebar: sidebar 
permalink: security_information_and_region.html 
summary: 'Data Infrastructure Insights segue le migliori pratiche di sicurezza durante l"intero ciclo di vita del rilascio.' 
keywords: security, risk, protection 
---
= Informazioni e Regione
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp prende molto seriamente la sicurezza delle informazioni dei clienti.  Ecco come e dove Data Infrastructure Insights archivia le tue informazioni.



== Quali informazioni memorizza Data Infrastructure Insights ?

Data Infrastructure Insights memorizza le seguenti informazioni:

* Dati sulle prestazioni
+
I dati sulle prestazioni sono dati di serie temporali che forniscono informazioni sulle prestazioni del dispositivo/sorgente monitorato.  Ciò include, ad esempio, il numero di I/O forniti da un sistema di archiviazione, la capacità di elaborazione di una porta FibreChannel, il numero di pagine fornite da un server Web, il tempo di risposta di un database e altro ancora.

* dati di inventario
+
I dati di inventario sono costituiti da metadati che descrivono il dispositivo/la sorgente monitorati e la loro configurazione.  Ciò include, ad esempio, le versioni hardware e software installate, i dischi e le LUN in un sistema di archiviazione, i core della CPU, la RAM e i dischi di una macchina virtuale, gli spazi tabella di un database, il numero e il tipo di porte su uno switch SAN, i nomi di directory/file (se Storage Workload Security è abilitato), ecc.

* Dati di configurazione
+
Riepiloga i dati di configurazione forniti dal cliente, utilizzati per gestire l'inventario e le operazioni del cliente, ad esempio nomi host o indirizzi IP dei dispositivi monitorati, intervalli di polling, valori di timeout, ecc.

* Segreti
+
I segreti sono costituiti dalle credenziali utilizzate dalla Data Infrastructure Insights Acquisition Unit per accedere ai dispositivi e ai servizi dei clienti.  Queste credenziali vengono crittografate utilizzando una crittografia asimmetrica avanzata e le chiavi private vengono memorizzate solo sulle unità di acquisizione e non escono mai dall'ambiente del cliente.  A causa di questa progettazione, anche gli SRE Data Infrastructure Insights privilegiati non sono in grado di accedere ai segreti dei clienti in testo normale.

* Dati funzionali
+
Si tratta di dati generati in seguito alla fornitura del Cloud Data Service da parte di NetApp , che informano NetApp sullo sviluppo, l'implementazione, le operazioni, la manutenzione e la protezione del Cloud Data Service.  I dati funzionali non contengono informazioni sul cliente o informazioni personali.

* Dati di accesso dell'utente
+
Informazioni di autenticazione e accesso che consentono a NetApp Console di comunicare con i siti Data Infrastructure Insights regionali, inclusi i dati relativi all'autorizzazione dell'utente.

* Dati della directory utente della sicurezza del carico di lavoro di archiviazione
+
Nei casi in cui la funzionalità Workload Security è abilitata E il cliente sceglie di abilitare il raccoglitore di directory utente, il sistema memorizzerà i nomi visualizzati degli utenti, gli indirizzi e-mail aziendali e altre informazioni raccolte da Active Directory.




NOTE: I dati della directory utente si riferiscono alle informazioni della directory utente raccolte dal raccoglitore dati della directory utente di Workload Security, non ai dati sugli utenti stessi di Data Infrastructure Insights/Workload Security.

*Nessun dato personale esplicito* viene raccolto dalle risorse infrastrutturali e dei servizi.  Le informazioni raccolte sono costituite solo da parametri di prestazione, informazioni di configurazione e metadati dell'infrastruttura, in modo molto simile a quanto avviene con i servizi telefonici di molti fornitori, tra cui il supporto automatico NetApp e ActiveIQ.  Tuttavia, a seconda delle convenzioni di denominazione del cliente, i dati per condivisioni, volumi, VM, qtree, applicazioni, ecc. possono contenere informazioni di identificazione personale.

Se Workload Security è abilitato, il sistema esamina anche i nomi di file e directory su SMB o altre condivisioni, che potrebbero contenere informazioni personali identificabili.  Quando i clienti abilitano Workload Security User Directory Collector (che sostanzialmente mappa i SID di Windows ai nomi utente tramite Active Directory), il nome visualizzato, l'indirizzo e-mail aziendale e tutti gli attributi aggiuntivi selezionati verranno raccolti e archiviati da Data Infrastructure Insights.

Inoltre, vengono conservati i registri di accesso a Data Infrastructure Insights , che contengono gli indirizzi IP e gli indirizzi e-mail degli utenti utilizzati per accedere al servizio.



== Dove vengono archiviate le mie informazioni?

Data Infrastructure Insights archivia le informazioni in base alla regione in cui è stato creato l'ambiente.

Nella regione host vengono memorizzate le seguenti informazioni:

* Telemetria e informazioni su asset/oggetti, inclusi contatori e metriche delle prestazioni
* Informazioni sull'unità di acquisizione
* Dati funzionali
* Informazioni di audit sulle attività degli utenti all'interno di Data Infrastructure Insights
* Informazioni sulla sicurezza del carico di lavoro di Active Directory
* Informazioni sull'audit di sicurezza del carico di lavoro


Le seguenti informazioni risiedono negli Stati Uniti, indipendentemente dalla regione che ospita l'ambiente Data Infrastructure Insights :

* Informazioni sul sito ambientale (talvolta denominato "inquilino"), come il proprietario del sito/account.
* Informazioni che consentono a NetApp Console di comunicare con i siti Data Infrastructure Insights regionali, incluso tutto ciò che riguarda l'autorizzazione dell'utente.
* Informazioni relative alla relazione tra l'utente Data Infrastructure Insights e il tenant.




=== Regioni ospitanti

Le regioni ospitanti includono:

* Stati Uniti: us-east-1
* EMEA: eu-central-1
* APAC: ap-southeast-2




== Ulteriori informazioni

Per maggiori informazioni sulla privacy e la sicurezza di NetApp, consulta i seguenti link:

* link:https://www.netapp.com/us/company/trust-center/index.aspx["Centro di fiducia"]
* link:https://www.netapp.com/us/company/trust-center/privacy/data-location-cross-border-transfers.aspx["Trasferimenti transfrontalieri di dati"]
* link:https://www.netapp.com/us/company/trust-center/privacy/bcr-binding-corporate-rules.aspx["Regole aziendali vincolanti"]
* link:https://www.netapp.com/us/company/trust-center/transparency/third-party-data-requests.aspx["Rispondere alle richieste di dati di terze parti"]
* link:https://www.netapp.com/us/company/trust-center/privacy/privacy-principles-security-safeguards.aspx["Principi sulla privacy NetApp"]

