---
sidebar: sidebar 
permalink: task_dc_ibm_powervm.html 
keywords: IBM, powerVM, 
summary: Configurazione di IBM PowerVM Data Collector. 
---
= Configurazione del data collector IBM PowerVM
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il data collector IBM PowerVM (SSH) viene utilizzato per raccogliere informazioni sulle partizioni virtuali in esecuzione sulle istanze hardware IBM POWER gestite da una console di gestione hardware (HMC).



== Terminologia

Data Infrastructure Insights acquisisce le informazioni di inventario dalle partizioni virtuali in esecuzione sulle istanze hardware IBM POWER. Per ogni tipo di risorsa acquisita, viene visualizzata la terminologia più comune utilizzata per la risorsa. Durante la visualizzazione o la risoluzione dei problemi di questo data collector, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Vendor/modello | Termine di approfondimento sull'infrastruttura dati 


| hdisk | Disco virtuale 


| Sistema gestito | Host 


| Server LPAR, VIO | Macchina virtuale 


| Gruppo di volumi | Data Store 


| Volume fisico | LUN 
|===
Nota: Si tratta solo di mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo data collector.



== Requisiti

Per configurare e utilizzare questo data collector devono essere soddisfatti i seguenti requisiti:

* Indirizzo IP della console di gestione hardware (HMC)
* Nome utente e password che consentono di accedere a hardware Management Console (HMC) tramite SSH
* Requisito di porta SSH-22
* Visualizzare l'autorizzazione su tutti i sistemi di gestione e i domini di protezione delle partizioni logiche
+
L'utente deve anche disporre dell'autorizzazione View per le configurazioni HMC e della capacità di raccogliere le informazioni VPD per il raggruppamento di sicurezza della console HMC. L'utente deve anche essere autorizzato all'accesso a Virtual io Server Command nel gruppo di protezione partizione logica. È consigliabile iniziare da un ruolo di operatore e rimuovere tutti i ruoli. Gli utenti di sola lettura su HMC non dispongono dei privilegi necessari per eseguire i comandi proxy sugli host AIX.

* La Best practice di IBM consiste nel fare in modo che i dispositivi siano monitorati da due o più HMCS. Tenere presente che questo potrebbe causare la segnalazione di dispositivi duplicati da parte di OnCommand Insight, pertanto si consiglia vivamente di aggiungere dispositivi ridondanti all'elenco "Escludi dispositivi" nella configurazione avanzata per questo data collector.




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP della console di gestione hardware (HMC) | Indirizzo IP o nome di dominio completo della console di gestione hardware PowerVM 


| Utente HMC | Nome utente della console di gestione hardware 


| Password | Password utilizzata per la console di gestione hardware 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo polling inventario (min) | Intervallo tra i sondaggi di inventario. L'impostazione predefinita è 20 minuti. 


| Porta SSH | Porta utilizzata per SSH su PowerVM 


| Password | Password utilizzata per la console di gestione hardware 


| Numero di tentativi | Numero di tentativi di inventario 


| Escludi dispositivi | Elenco separato da virgole degli ID dei dispositivi o dei nomi visualizzati da escludere 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector sono disponibili nella link:concept_requesting_support.html["Supporto"]pagina o nella link:reference_data_collector_support_matrix.html["Matrice di supporto Data Collector"].
