---
sidebar: sidebar 
permalink: task_dc_emc_xio.html 
keywords: data collector, XtremeIO, EMC 
summary: Configurazione di XtremeIO data collector. 
---
= Data collector Dell EMC XtremeIO
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Il data collector EMC XtremIO acquisisce i dati di inventario e performance dal sistema storage EMC XtremIO.



== Requisiti

Per configurare il data collector EMC XtremIO (HTTP), è necessario disporre di:

* L'indirizzo host di XtremIO Management Server (XMS)
* Un account con privilegi di amministratore
* Accesso alla porta 443 (HTTPS)




== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal data collector EMC XtremIO. Per ogni tipo di asset acquisito da Data Infrastructure Insights viene visualizzata la terminologia più comune utilizzata per questa risorsa. Durante la visualizzazione o la risoluzione dei problemi di questa origine dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Vendor/modello | Termine di approfondimento sull'infrastruttura dati 


| Disco (SSD) | Disco 


| Cluster | Storage 


| Controller | Nodo di storage 


| Volume | Volume 


| Mappa LUN | Mappa del volume 


| Iniziatore FC di destinazione | Maschera di volume 
|===
Nota: Si tratta solo di mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questa origine dati.



== Requisiti

* L'indirizzo IP dell'host XtremIO Management Server (XMS)
* Nome utente e password dell'amministratore per XtremIO




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Host XMS | Indirizzo IP o nome di dominio completo di XtremIO Management Server 


| Nome utente | Nome utente di XtremIO Management Server 


| Password | Password per XtremIO Management Server 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Porta TCP | Porta TCP utilizzata per la connessione a XTremIO Management Server. Il valore predefinito è 443. 


| Intervallo di polling dell'inventario (min) | Intervallo tra i sondaggi di inventario. L'impostazione predefinita è 60 minuti. 


| Intervallo di polling delle performance (sec) | Intervallo tra i sondaggi delle performance. Il valore predefinito è 300 secondi. 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector sono disponibili nella link:concept_requesting_support.html["Supporto"]pagina o nella link:reference_data_collector_support_matrix.html["Matrice di supporto Data Collector"].
