---
sidebar: sidebar 
permalink: task_dc_ibm_powervm.html 
keywords: IBM, powerVM, 
summary: Configurazione del raccoglitore dati IBM PowerVM. 
---
= Configurazione del raccoglitore dati IBM PowerVM
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il raccoglitore dati IBM PowerVM (SSH) viene utilizzato per raccogliere informazioni sulle partizioni virtuali in esecuzione su istanze hardware IBM POWER gestite da una console di gestione hardware (HMC).



== Terminologia

Data Infrastructure Insights acquisisce informazioni di inventario dalle partizioni virtuali in esecuzione sulle istanze hardware IBM POWER.  Per ogni tipologia di asset acquisito viene mostrata la terminologia più comune utilizzata per l'asset.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| disco rigido | Disco virtuale 


| Sistema gestito | Ospite 


| LPAR, server VIO | Macchina virtuale 


| Gruppo di volumi | Archivio dati 


| Volume fisico | LUN 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

Per configurare e utilizzare questo raccoglitore dati è necessario soddisfare i seguenti requisiti:

* Indirizzo IP della Hardware Management Console (HMC)
* Nome utente e password che consentono l'accesso alla Hardware Management Console (HMC) tramite SSH
* Requisito porta SSH-22
* Visualizza l'autorizzazione su tutti i sistemi di gestione e sui domini di sicurezza delle partizioni logiche
+
L'utente deve inoltre disporre dell'autorizzazione di visualizzazione sulle configurazioni HMC e della possibilità di raccogliere informazioni VPD per il raggruppamento di sicurezza della console HMC.  All'utente deve inoltre essere consentito l'accesso al comando Virtual IO Server nel raggruppamento di sicurezza Partizione logica.  È buona norma iniziare dal ruolo di operatore e poi rimuovere tutti i ruoli.  Gli utenti di sola lettura sull'HMC non hanno privilegi per eseguire comandi proxy sugli host AIX.

* La best practice di IBM prevede che i dispositivi siano monitorati da due o più HMC.  Tieni presente che ciò potrebbe far sì che OnCommand Insight segnali dispositivi duplicati, pertanto è altamente consigliato aggiungere dispositivi ridondanti all'elenco "Escludi dispositivi" nella Configurazione avanzata per questo raccoglitore dati.




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP della console di gestione hardware (HMC) | Indirizzo IP o nome di dominio completo della PowerVM Hardware Management Console 


| Utente HMC | Nome utente per la console di gestione hardware 


| Password | Password utilizzata per la console di gestione hardware 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 20 minuti. 


| Porta SSH | Porta utilizzata per SSH su PowerVM 


| Password | Password utilizzata per la console di gestione hardware 


| Numero di tentativi | Numero di tentativi di ripetizione dell'inventario 


| Escludi dispositivi | Elenco separato da virgole di ID dispositivo o nomi visualizzati da escludere 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
