---
sidebar: sidebar 
permalink: task_dc_pure_flashblade.html 
keywords: data collector, Pure Storage, pure, FlashBlade 
summary: Configurazione del raccoglitore dati Pure Storage. 
---
= Raccoglitore dati Pure Storage FlashBlade
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza il raccoglitore dati Pure Storage FlashBlade per raccogliere dati di inventario e prestazioni dai cluster FlashBlade che espongono la versione 2 della loro API REST



== Terminologia

Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per la risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Unità (SSD) | Disco 


| Vettore | Magazzinaggio 


| Lama | Nodo di archiviazione 


| Sistema di file | Volume interno 


| Bucket di archiviazione degli oggetti | Qtree 


| Iniziatore, bersaglio | Maschera del volume 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

* Indirizzo IP del sistema di archiviazione o nome di dominio completo
* Token API, idealmente con durata infinita.  Dovrebbe essere sufficiente un utente con livello di sola lettura.
* Requisito porta: HTTPS 443




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP host FlashBlade | Indirizzo IP del sistema di archiviazione 


| Nome utente | Nome utente per aiutare gli amministratori Data Infrastructure Insights a ricordare a quale utente appartiene il loro token API 


| Token API | Token API 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Tipo di connessione | Scegli HTTP o HTTPS.  Visualizza anche la porta predefinita. 


| Sostituisci la porta TCP | Se vuoto, utilizzare la porta predefinita nel campo Tipo di connessione, altrimenti immettere la porta di connessione da utilizzare 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 60 minuti 


| Intervallo di sondaggio sulle prestazioni (sec) | Il valore predefinito è 300 
|===


== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova questo: 


| "Credenziali di accesso non valide" con messaggi di errore "La policy non consente" o "Non sei autorizzato" | Convalida l'account utente e la password Pure tramite l'interfaccia http Pure 
|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
