---
sidebar: sidebar 
permalink: task_cs_user_management.html 
keywords: Workload Security, User, Login, account, cloud secure 
summary: Gli account utente di Workload Security sono gestiti tramite la gestione degli utenti Data Infrastructure Insights 
---
= Gestione degli utenti
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Gli account utente di Workload Security vengono gestiti tramite Data Infrastructure Insights.

Data Infrastructure Insights fornisce quattro livelli di account utente: proprietario dell'account, amministratore, utente e ospite.  A ciascun account vengono assegnati livelli di autorizzazione specifici.  Un account utente con privilegi di amministratore può creare o modificare utenti e assegnare a ciascun utente uno dei seguenti ruoli di sicurezza del carico di lavoro:

|===


| Ruolo | Accesso alla sicurezza del carico di lavoro 


| Amministratore | Può eseguire tutte le funzioni di sicurezza del carico di lavoro, comprese quelle per avvisi, analisi forense, raccoglitori di dati, criteri di risposta automatizzati e API per la sicurezza del carico di lavoro.  Un amministratore può anche invitare altri utenti, ma può assegnare solo ruoli di sicurezza del carico di lavoro. 


| Utente | Può visualizzare e gestire gli avvisi e visualizzare le analisi forensi.  Il ruolo utente può modificare lo stato dell'avviso, aggiungere una nota, acquisire manualmente snapshot e limitare l'accesso utente. 


| Ospite | È possibile visualizzare avvisi e analisi forensi.  Il ruolo ospite non può modificare lo stato dell'avviso, aggiungere una nota, acquisire manualmente snapshot o limitare l'accesso degli utenti. 
|===
.Passi
. Accedi a Workload Security
. Nel menu, fare clic su *Amministrazione > Gestione utenti*
+
Verrai indirizzato alla pagina Gestione utenti di Data Infrastructure Insights.

. Selezionare il ruolo desiderato per ciascun utente.


Quando si aggiunge un nuovo utente, è sufficiente selezionare il ruolo desiderato (solitamente Utente o Ospite).

Ulteriori informazioni sugli account utente e sui ruoli sono disponibili in Data Infrastructure Insightslink:https://docs.netapp.com/us-en/cloudinsights/concept_user_roles.html["Ruolo utente"] documentazione.
