---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: Configurazione di DELL EMC RecoverPoint Data Collector. 
---
= Data collector Dell EMC RecoverPoint
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il caso d'utilizzo principale del data collector EMC RecoverPoint consiste nel rilevare le relazioni di replica volume-volume che l'appliance di storage RecoverPoint facilita. Questo collector rileverà anche l'appliance Recoverpoint. Dell/EMC vende una soluzione di backup VMware per macchine virtuali --"RecoverPoint per macchine virtuali" - che non è supportata da questo collector

Per la configurazione, il data collector richiede l'indirizzo IP dei processori di storage e un nome utente e una password di sola lettura.

Il data collector EMC RecoverPoint raccoglie le relazioni di replica volume-volume che RecoverPoint coordina tra altri storage array. Data Infrastructure Insights mostra uno storage array per ogni cluster RecoverPoint e raccoglie dati di inventario per i nodi e le porte storage in tale cluster. Non vengono raccolti dati di volumi o pool di storage.



== Requisiti

Per configurare questo data collector sono necessarie le seguenti informazioni:

* Indirizzo IP o nome di dominio completo del processore di storage
* Nome utente e password di sola lettura
* Accesso API REST tramite la porta 443




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo di RecoverPoint | Indirizzo IP o nome di dominio completo del cluster RecoverPoint 


| Nome utente | Nome utente del cluster RecoverPoint 


| Password | Password utilizzata per il cluster RecoverPoint 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Porta TCP | Porta TCP utilizzata per la connessione al cluster Recoverpoint 


| Intervallo polling inventario (minuti) | Intervallo tra i sondaggi di inventario. L'impostazione predefinita è 20 minuti. 


| Cluster esclusi | Elenco separato da virgole di ID cluster o nomi da escludere durante il polling. 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector sono disponibili nella link:concept_requesting_support.html["Supporto"]pagina o nella link:reference_data_collector_support_matrix.html["Matrice di supporto Data Collector"].
