---
sidebar: sidebar 
permalink: task_dc_emc_vplex.html 
keywords: data collector, VPLEX, EMC 
summary: Configurazione del raccoglitore dati VPLEX. 
---
= Configurazione del raccoglitore dati EMC VPLEX
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Questo raccoglitore di dati acquisisce dati di inventario e prestazioni dai sistemi di storage EMC VPLEX.  Per la configurazione, il raccoglitore dati necessita di un indirizzo IP del server VPLEX e di un account di dominio di livello amministrativo.


NOTE: Per poter raccogliere dati sulle prestazioni di Data Infrastructure Insights dai cluster Vplex, è necessario che il servizio di archiviazione delle prestazioni sia operativo, per popolare i file .CSV e i log che Data Infrastructure Insights recupera tramite copie di file basate su SCP.  NetApp ha osservato che molti aggiornamenti del firmware/della stazione di gestione Vplex renderanno questa funzionalità non operativa.  I clienti che pianificano tali aggiornamenti potrebbero voler chiedere in modo proattivo a Dell/EMC se l'aggiornamento pianificato renderà questa funzionalità inutilizzabile e, in tal caso, come possono riattivarla per ridurre al minimo le lacune nella visibilità delle prestazioni?  Il codice delle prestazioni Vplex di Cloud Insight valuterà a ogni polling se tutti i file previsti esistono e se vengono aggiornati correttamente; se sono mancanti o obsoleti, Data Infrastructure Insights registrerà gli errori di raccolta delle prestazioni.



== Terminologia

Data Infrastructure Insightst acquisisce le seguenti informazioni di inventario dal raccoglitore dati VPLEX.  Per ogni tipologia di asset acquisito viene mostrata la terminologia più comune utilizzata per tale asset.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Grappolo | Magazzinaggio 


| Motore | Nodo di archiviazione 


| Dispositivo, estensione del sistema | Pool di archiviazione back-end 


| Volume virtuale | Volume 


| Porta front-end, porta back-end | Porta 


| Dispositivo distribuito | Sincronizzazione dell'archiviazione 


| Vista di archiviazione | Mappa del volume, maschera del volume 


| Volume di archiviazione | LUN di backend 


| ITL | Percorso backend 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

* Un indirizzo IP della console di gestione VPLEX
* Account di dominio a livello amministrativo per il server VPLEX
* Porta 443 (HTTPS).  Richiede connettività in uscita alla porta TCP 443 sulla stazione di gestione VPLEX.
* Per migliorare le prestazioni, nome utente e password di sola lettura per l'accesso ssh/scp.
* Per le prestazioni è richiesta la porta 22.




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP della console di gestione VPLEX | Indirizzo IP o nome di dominio completo della console di gestione VPLEX 


| Nome utente | Nome utente per VPLEX CLI 


| Password | Password utilizzata per VPLEX CLI 


| Indirizzo IP remoto delle prestazioni | Indirizzo IP remoto delle prestazioni della console di gestione VPLEX 


| Nome utente remoto delle prestazioni | Nome utente remoto delle prestazioni della console di gestione VPLEX 


| Password remota per le prestazioni | Password remota delle prestazioni della console di gestione VPLEX 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Porta di comunicazione | Porta utilizzata per VPLEX CLI.  Il valore predefinito è 443. 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 20 minuti. 


| Numero di tentativi di connessione | Il valore predefinito è 3. 


| Intervallo di sondaggio sulle prestazioni (sec) | Intervallo tra i sondaggi sulle prestazioni. Il valore predefinito è 600 secondi. 


| Numero di tentativi | Il valore predefinito è 2. 
|===


== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova questo: 


| Errore: autenticazione utente fallita. | Assicurati che le credenziali per questo dispositivo siano corrette. 
|===


=== Prestazione

[cols="2*"]
|===
| Problema: | Prova questo: 


| Errore: le prestazioni di VPLEX per la versione precedente alla 5.3 non sono supportate. | Aggiorna VPLEX alla versione 5.3 o successiva 


| Errore: non sono stati raccolti dati sufficienti. | • Controllare il timestamp della raccolta nel file di registro e modificare di conseguenza l'intervallo di polling • Attendere un tempo più lungo 


| Errore: i file di registro perpetui non vengono aggiornati. | Contattare il supporto EMC per abilitare l'aggiornamento dei file di registro perpetui 


| Errore: l'intervallo di polling delle prestazioni è troppo grande. | Controllare il timestamp della raccolta nel file di registro ${logfile} e modificare di conseguenza l'intervallo di polling 


| Errore: l'indirizzo IP remoto delle prestazioni della console di gestione VPLEX non è configurato. | Modificare l'origine dati per impostare l'indirizzo IP remoto delle prestazioni della console di gestione VPLEX. 


| Errore: nessun dato sulle prestazioni segnalato dal direttore | • Verificare che i monitor delle prestazioni del sistema funzionino correttamente • Contattare il supporto EMC per abilitare l'aggiornamento dei file di registro del monitor delle prestazioni del sistema 
|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
