---
sidebar: sidebar 
permalink: task_query_copy_table_values.html 
summary: È possibile copiare i valori da una tabella agli Appunti per utilizzarli in altre applicazioni. 
keywords: query, queries, copy, values, clipboard 
---
= Copia dei valori della tabella
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
È possibile copiare i valori nelle tabelle negli Appunti per utilizzarli nelle caselle di ricerca o in altre applicazioni.

.A proposito di questa attività
Esistono due metodi per copiare i valori dalle tabelle o dai risultati delle query negli Appunti.

.Fasi
. Metodo 1: Evidenziare il testo desiderato con il mouse, copiarlo e incollarlo nei campi di ricerca o in altre applicazioni.
. Metodo 2: Per i campi a valore singolo, passare il mouse sul campo e fare clic sull'icona degli Appunti visualizzata. Il valore viene copiato negli Appunti per essere utilizzato nei campi di ricerca o in altre applicazioni.
+
Questo metodo consente di copiare solo i valori che sono collegamenti alle risorse. Solo i campi che includono valori singoli (ad esempio non elenchi) hanno l'icona di copia.


