---
sidebar: sidebar 
permalink: task_dc_na_eseries.html 
keywords: data collector, ontap, clustered ontap, e-series, santricity 
summary: Configurazione del raccoglitore dati NetApp E-Series. 
---
= Raccoglitore dati API NetApp E-Series Legacy Santricity
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il raccoglitore di dati API NetApp E-Series Legacy Santricity raccoglie dati di inventario e prestazioni.  Il collettore supporta il firmware 7.x+ utilizzando le stesse configurazioni e segnalando gli stessi dati.



== Terminologia

Cloud Insight acquisisce le seguenti informazioni di inventario dal raccoglitore dati NetApp E-Series.  Per ogni tipologia di asset acquisito viene mostrata la terminologia più comune utilizzata per tale asset.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Disco | Disco 


| Gruppo di volumi | Gruppo di dischi 


| Array di archiviazione | Magazzinaggio 


| Controllore | Nodo di archiviazione 


| Gruppo di volumi | Pool di archiviazione 


| Volume | Volume 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Terminologia della serie E (pagina di destinazione)

I seguenti termini si applicano agli oggetti o ai riferimenti che potresti trovare nelle landing page delle risorse NetApp E-Series.  Molti di questi termini si applicano anche ad altri raccoglitori di dati.



=== Magazzinaggio

* Modello: nome del modello del dispositivo.
* Fornitore: lo stesso nome del fornitore che vedresti se stessi configurando una nuova origine dati
* Numero di serie: il numero di serie dell'array.  Nei sistemi di archiviazione con architettura cluster come NetApp Clustered Data Ontap, questo numero di serie potrebbe essere meno utile dei singoli numeri di serie dei "nodi di archiviazione"
* IP: in genere saranno gli IP o i nomi host configurati nell'origine dati
* Versione del microcodice – firmware
* Capacità grezza: somma di base 2 di tutti i dischi fisici nel sistema, indipendentemente dal loro ruolo
* Latenza: rappresentazione di ciò che sta sperimentando l'host che gestisce i carichi di lavoro, sia in lettura che in scrittura.  Idealmente, Data Infrastructure Insights reperirebbe questo valore direttamente, ma spesso non è così.  Invece dell'array che offre questa funzionalità, Data Infrastructure Insights esegue in genere un calcolo ponderato in base agli IOPS derivato dalle statistiche dei singoli volumi.
* Throughput: il throughput totale dell'array rivolto all'host.  Idealmente, se ottenuto direttamente dall'array, se non disponibile, Data Infrastructure Insights somma la produttività dei volumi per ricavare questo valore
* Gestione: può contenere un collegamento ipertestuale all'interfaccia di gestione del dispositivo.  Creato a livello di programmazione dalla fonte Data Infrastructure Insights come parte della reportistica di inventario  




=== Pool di archiviazione

* Archiviazione: su quale array di archiviazione risiede questo pool. Obbligatorio
* Tipo: un valore descrittivo da un elenco di possibilità enumerate.  Più comunemente sarà "Thin Provisioning" o "RAID Group"
* Nodo: se l'architettura di questo array di archiviazione è tale che i pool appartengono a un nodo di archiviazione specifico, il suo nome verrà visualizzato qui come collegamento ipertestuale alla sua landing page
* Utilizza Flash Pool – Valore Sì/No
* Ridondanza: livello RAID o schema di protezione.  E-Series segnala "RAID 7" per i pool DDP
* Capacità: i valori qui indicati sono la capacità logica utilizzata, la capacità utilizzabile e la capacità logica totale, nonché la percentuale utilizzata tra queste.  Entrambi questi valori includono la capacità di “conservazione” della Serie E, risultando in numeri e percentuali superiori a quanto potrebbe mostrare l’interfaccia utente della Serie E stessa
* Capacità sovraimpegnata: se tramite tecnologie di efficienza è stata assegnata una somma totale di volume o capacità di volume interno superiore alla capacità logica del pool di archiviazione, il valore percentuale sarà maggiore dello 0%.
* Snapshot: capacità snapshot utilizzate e totali, se l'architettura del pool di archiviazione dedica parte della sua capacità ad aree di segmenti esclusivamente per gli snapshot
* Utilizzo: valore percentuale che indica la percentuale più alta di disco occupato tra tutti i dischi che contribuiscono alla capacità di questo pool di archiviazione.  L'utilizzo del disco non ha necessariamente una forte correlazione con le prestazioni dell'array: l'utilizzo può essere elevato a causa di ricostruzioni del disco, attività di deduplicazione, ecc. in assenza di carichi di lavoro gestiti dall'host.  Inoltre, molte implementazioni di replicazione degli array possono aumentare l'utilizzo del disco senza essere visualizzate come carico di lavoro del volume.
* IOPS: la somma degli IOPS di tutti i dischi che contribuiscono alla capacità di questo pool di archiviazione.  Se gli IOPS del disco non sono disponibili su una determinata piattaforma, questo valore verrà ricavato dalla somma degli IOPS del volume per tutti i volumi presenti su questo pool di archiviazione
* Throughput: la somma del throughput di tutti i dischi che contribuiscono alla capacità di questo pool di archiviazione.  Se la capacità di elaborazione del disco non è disponibile su una determinata piattaforma, questo valore verrà ricavato dalla somma del volume per tutti i volumi presenti su questo pool di archiviazione




=== Nodo di archiviazione

* Archiviazione: di quale array di archiviazione fa parte questo nodo. Obbligatorio
* Partner HA: sulle piattaforme in cui un nodo eseguirà il failover su un solo altro nodo, generalmente verrà visualizzato qui
* Stato: salute del nodo.  Disponibile solo quando l'array è sufficientemente integro da poter essere inventariato da una fonte dati
* Modello: nome del modello del nodo
* Versione: nome della versione del dispositivo.
* Numero di serie: il numero di serie del nodo
* Memoria – memoria base 2 se disponibile
* Utilizzo: in genere un numero di utilizzo della CPU o, nel caso di NetApp Ontap, un indice di stress del controller.  L'utilizzo non è attualmente disponibile per NetApp E-Series
* IOPS: numero che rappresenta gli IOPS gestiti dall'host su questo controller.  Idealmente, l'origine è direttamente dall'array; se non disponibile, verrà calcolato sommando tutti gli IOPS per i volumi che appartengono esclusivamente a questo nodo.
* Latenza: numero che rappresenta la latenza tipica dell'host o il tempo di risposta su questo controller.  Idealmente, l'origine è direttamente dall'array; se non disponibile, verrà calcolato eseguendo un calcolo ponderato degli IOP dai volumi che appartengono esclusivamente a questo nodo.
* Throughput: numero che rappresenta il throughput gestito dall'host su questo controller.  Idealmente, la fonte dovrebbe essere direttamente l'array; se non disponibile, verrà calcolato sommando tutta la produttività dei volumi che appartengono esclusivamente a questo nodo.
* Processori – numero di CPU




== Requisiti

* L'indirizzo IP di ciascun controller sull'array
* Requisito di porta 2463




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Elenco separato da virgole degli IP del controller Array SANtricity | Indirizzi IP e/o nomi di dominio completi per i controller di array 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 30 minuti 


| Intervallo di sondaggio delle prestazioni fino a 3600 secondi | Il valore predefinito è 300 secondi 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo raccoglitore di dati possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
