---
sidebar: sidebar 
permalink: task_view_configured_data_collectors.html 
keywords: acquisition, AU, data collector, collector, bulk edit, postpone polling, resume polling 
summary: Un riassunto. 
---
= Gestione dei raccoglitori di dati configurati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La pagina Data Collector installati fornisce l'accesso ai data collector configurati per Data Infrastructure Insights.  È possibile utilizzare questa pagina per modificare i raccoglitori di dati esistenti.

.Passi
. Nel menu Data Infrastructure Insights , fare clic su *Osservabilità > Collettori*
+
Viene visualizzata la schermata Raccoglitori dati disponibili.

. Fare clic su *Raccolta dati installati*
+
Viene visualizzato un elenco di tutti i Data Collector installati.  L'elenco fornisce il nome del collettore, lo stato, l'indirizzo IP a cui il collettore sta accedendo e l'ultima volta che i dati sono stati acquisiti da un dispositivo.  Le azioni che possono essere eseguite in questa schermata includono:

+
** Controllo dei sondaggi
** Modifica le credenziali del raccoglitore dati
** Clonare i collettori di dati






== Controllo del polling del Data Collector

Dopo aver apportato una modifica a un raccoglitore dati, potresti voler eseguire immediatamente un polling per verificare le modifiche oppure potresti voler posticipare la raccolta dati su un raccoglitore dati per uno, tre o cinque giorni mentre lavori su un problema.

.Passi
. Nel menu Data Infrastructure Insights , fare clic su *Osservabilità > Collettori*
. Fare clic su *Raccolta dati installati*
. Seleziona la casella di controllo a sinistra del Data Collector che desideri modificare
. Fare clic su *Azioni in blocco* e selezionare l'azione di sondaggio che si desidera eseguire.
+
È possibile eseguire azioni in blocco contemporaneamente su più Data Collector.  Selezionare i raccoglitori di dati e scegliere l'azione da eseguire dal menu *Azione in blocco*.





== Modifica delle informazioni del raccoglitore dati

È possibile modificare le informazioni di configurazione del raccoglitore dati esistente.

.Per modificare un singolo raccoglitore di dati:
. Nel menu Data Infrastructure Insights , fare clic su *Osservabilità > Collettori* per aprire l'elenco dei collettori dati installati.
. Nel menu delle opzioni a destra del raccoglitore dati che vuoi modificare, clicca su *Modifica*.
+
Si apre la finestra di dialogo Modifica raccoglitore.

. Inserisci le modifiche e clicca su *Test configurazione* per testare la nuova configurazione oppure clicca su *Salva* per salvare la configurazione.


È anche possibile modificare più raccoglitori di dati:

. Selezionare la casella di controllo a sinistra di ogni raccoglitore dati che si desidera modificare.
. Fare clic sul pulsante *Azioni in blocco* e scegliere *Modifica* per aprire la finestra di dialogo Modifica raccoglitore dati.
. Modificare i campi come sopra.
+

NOTE: I collettori di dati selezionati devono essere dello stesso fornitore e modello e risiedere nella stessa unità di acquisizione.

+
Quando si modificano più raccoglitori di dati, il campo Nome raccoglitore di dati mostra "Misto" e non può essere modificato.  Altri campi, come nome utente e password, risultano "Misti" e possono essere modificati.  I campi che condividono lo stesso valore nei raccoglitori di dati selezionati mostrano i valori correnti e possono essere modificati.

+
Quando si modificano più raccoglitori di dati, il pulsante *Configurazione di prova* non è disponibile.





== Clonazione di collettori di dati

Utilizzando la funzione di clonazione, è possibile aggiungere rapidamente un'origine dati che abbia le stesse credenziali e gli stessi attributi di un'altra origine dati.  La clonazione consente di configurare facilmente più istanze dello stesso tipo di dispositivo.

.Passi
. Nel menu Data Infrastructure Insights , fare clic su *Osservabilità > Collettori*.
. Fare clic su *Raccolta dati installati*.
. Fare clic sulla casella di controllo a sinistra del raccoglitore dati che si desidera copiare.
. Nel menu delle opzioni a destra del raccoglitore dati selezionato, fare clic su *Clona*.
+
Viene visualizzata la finestra di dialogo Clona raccolta dati.

. Inserisci le nuove informazioni nei campi richiesti.
. Fare clic su *Salva*.


.Dopo aver finito
L'operazione di clonazione copia tutti gli altri attributi e impostazioni per creare il nuovo raccoglitore dati.



== Esecuzione di azioni in blocco sui collettori di dati

È possibile modificare contemporaneamente alcune informazioni per più raccoglitori di dati.  Questa funzione consente di avviare un sondaggio, posticiparlo e riprenderlo su più raccoglitori di dati.  Inoltre, è possibile eliminare più raccoglitori di dati.

.Passi
. Nel menu Data Infrastructure Insights , fare clic su *Osservabilità > Collettori*
. Fare clic su *Raccolta dati installati*
. Fare clic sulla casella di controllo a sinistra dei raccoglitori di dati che si desidera modificare.
. Nel menu delle opzioni a destra, fare clic sull'opzione che si desidera eseguire.


.Dopo aver finito
L'operazione selezionata viene eseguita sui raccoglitori di dati.  Quando si sceglie di eliminare i raccoglitori di dati, viene visualizzata una finestra di dialogo che richiede di confermare l'azione.
