---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: Configurazione del raccoglitore dati DELL EMC RecoverPoint. 
---
= Raccoglitore dati Dell EMC RecoverPoint
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il caso d'uso principale del raccoglitore dati EMC RecoverPoint è quello di scoprire le relazioni di replica tra volumi facilitate dall'appliance di storage RecoverPoint.  Questo raccoglitore scoprirà anche l'appliance Recoverpoint stessa.  Si prega di notare che Dell/EMC vende una soluzione di backup VMware per VM, "RecoverPoint for VMs", che non è supportata da questo collector.

Per la configurazione, il raccoglitore dati richiede l'indirizzo IP dei processori di archiviazione e un nome utente e una password di sola lettura.

Il raccoglitore dati EMC RecoverPoint raccoglie le relazioni di replica da volume a volume che RecoverPoint coordina tra altri array di storage.  Data Infrastructure Insights mostra un array di archiviazione per ogni cluster RecoverPoint e raccoglie i dati di inventario per i nodi e le porte di archiviazione su quel cluster.  Non vengono raccolti dati di pool di archiviazione o di volume.



== Requisiti

Per configurare questo raccoglitore dati sono necessarie le seguenti informazioni:

* Indirizzo IP o nome di dominio completo del processore di archiviazione
* Nome utente e password di sola lettura
* Accesso API REST tramite porta 443




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo di RecoverPoint | Indirizzo IP o nome di dominio completo del cluster RecoverPoint 


| Nome utente | Nome utente per il cluster RecoverPoint 


| Password | Password utilizzata per il cluster RecoverPoint 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Porta TCP | Porta TCP utilizzata per connettersi al cluster Recoverpoint 


| Intervallo di sondaggio dell'inventario (minuti) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 20 minuti. 


| Cluster esclusi | Elenco separato da virgole di ID o nomi di cluster da escludere durante il polling. 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
