---
sidebar: sidebar 
permalink: task_dc_ibm_cleversafe.html 
keywords: data collector, IBM Cleversafe 
summary: Configurazione del raccoglitore dati IBM Cleversafe. 
---
= Raccoglitore dati IBM Cleversafe
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza questo strumento di raccolta dati per scoprire dati di inventario e prestazioni per i sistemi di storage IBM Cleversafe.


NOTE: IBM Cleversafe viene misurato in base a una tariffa Raw TB diversa da quella delle unità gestite.  Ogni 40 TB di capacità IBM Cleversafe non formattata viene addebitato come 1link:concept_subscribing_to_cloud_insights.html#pricing["Unità gestita (MU)"] .



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati IBM Cleversafe.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Pool di archiviazione | Pool di archiviazione 


| Contenitore | Volume interno 


| Contenitore | Condivisione file 


| Condivisione NFS | Condividere 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

* L'indirizzo IP dei servizi dati esterni per il cluster
* Nome utente e password dell'amministratore
* Porta 9440




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| IP del gestore o nome host | Indirizzo IP o nome host del nodo di gestione 


| Nome utente | Nome utente per l'account utente con ruolo di superutente o amministratore di sistema 


| Password | Password per l'account utente con ruolo di superutente o amministratore di sistema 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario. 


| Timeout della connessione HTTP (sec) | Timeout HTTP in secondi. 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
