---
sidebar: sidebar 
permalink: task_dc_emc_vnx_file.html 
keywords: data collector, Celerra, EMC, DELL, VNX File 
summary: Configurazione del raccoglitore dati DELL EMC Celerra. 
---
= Raccoglitore dati DELL EMC VNX File (in precedenza Celerra Unified Storage System)
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Questo raccoglitore di dati acquisisce informazioni di inventario dal sistema di archiviazione file VNX.  Per la configurazione, questo raccoglitore di dati richiede l'indirizzo IP dei processori di archiviazione e un nome utente e una password di sola lettura.



[[terminology]]
== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati VNX File.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="50,50"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Server di rete Celerra/pool di archiviazione Celerra | Pool di archiviazione 


| Sistema di file | Volume interno 


| Spostamento dati | Controllore 


| File System montato su un data mover | Condivisione file 


| Esportazioni CIFS e NFS | Condividere 


| Volume del disco | LUN di backend 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



[[requirements]]
== Requisiti

Per configurare questo raccoglitore dati è necessario quanto segue:

* L'indirizzo IP del processore di archiviazione
* Nome utente e password di sola lettura
* Porta SSH 22




[[configuration]]
== Configurazione

[cols="50,50"]
|===
| Campo | Descrizione 


| Indirizzo IP del file VNX | Indirizzo IP o nome di dominio completo del dispositivo file VNX 


| Nome utente | Nome utilizzato per accedere al dispositivo VNX File 


| Password | Password utilizzata per accedere al dispositivo VNX File 
|===


[[advanced-configuration]]
== Configurazione avanzata

[cols="50,50"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (minuti) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 20 minuti. 
|===


[[troubleshooting]]
== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:



[[inventory]]
=== Inventario

[cols="50,50"]
|===
| Problema: | Prova questo: 


| Errore: impossibile procedere mentre è in corso l'aggiornamento DART | Soluzione possibile: mettere in pausa il raccoglitore dati e attendere il completamento dell'aggiornamento DART prima di tentare un'altra richiesta di acquisizione. 
|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
