---
sidebar: sidebar 
permalink: task_cs_getting_started.html 
keywords: collectors, data collectors, configure, introduction, browsers, Cloud Secure 
summary: 'Distribuisci agenti Workload Security e raccoglitori di dati per monitorare l"attività degli utenti e rilevare le minacce alla sicurezza.' 
---
= Introduzione alla sicurezza del carico di lavoro
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Workload Security ti aiuta a monitorare l'attività degli utenti e a rilevare potenziali minacce alla sicurezza nel tuo ambiente di archiviazione.  Prima di poter iniziare il monitoraggio, è necessario configurare agenti, raccoglitori di dati e servizi di directory per gettare le basi per un monitoraggio completo della sicurezza.

Il sistema Workload Security utilizza un agente per raccogliere i dati di accesso dai sistemi di archiviazione e le informazioni utente dai server Directory Services.

Prima di poter iniziare a raccogliere dati, è necessario configurare quanto segue:

[cols="2*"]
|===


| Compito | Informazioni correlate 


| Configurare un agente  a| 
link:concept_cs_agent_requirements.html["Requisiti dell'agente"]

link:task_cs_add_agent.html["Aggiungi agente"]



| Configurare un connettore di directory utente | link:task_config_user_dir_connect.html["Aggiungi connettore directory utente"] 


| Configurare i raccoglitori di dati | Fare clic su *Sicurezza del carico di lavoro > Collettori*. Fare clic sul collettore dati che si desidera configurare. Per informazioni sul collettore, consultare la sezione Riferimento del fornitore del Data Collector della documentazione. 


| Crea account utente | link:concept_user_roles.html["Gestisci account utente"] 
|===
Workload Security può essere integrato anche con altri strumenti.  Per esempio,link:http://docs.netapp.com/us-en/cloudinsights/CloudInsights_CloudSecure_Splunk_integration_guide.pdf["vedi questa guida"] sull'integrazione con Splunk.
