---
sidebar: sidebar 
permalink: task_dc_na_solidfire.html 
summary: Configurare il raccoglitore dati NetApp SolidFire 
keywords: data collector, queries, create 
---
= Raccoglitore dati NetApp SolidFire All-Flash Array
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il raccoglitore di dati NetApp SolidFire All-Flash Array supporta la raccolta di inventario e prestazioni da configurazioni SolidFire sia iSCSI che Fibre Channel.

Il raccoglitore dati SolidFire utilizza la SolidFire REST API.  L'unità di acquisizione in cui risiede il raccoglitore dati deve essere in grado di avviare connessioni HTTPS alla porta TCP 443 sull'indirizzo IP di gestione del cluster SolidFire .  Il raccoglitore dati necessita di credenziali in grado di effettuare query REST API sul cluster SolidFire .



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati NetApp SolidFire All-Flash Array.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Guidare | Disco 


| Grappolo | Magazzinaggio 


| Nodo | Nodo di archiviazione 


| Volume | Volume 


| Porta Fibre Channel | Porta 


| Gruppo di accesso al volume, assegnazione LUN | Mappa del volume 


| Sessione iSCSI | Maschera del volume 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

Di seguito sono riportati i requisiti per la configurazione di questo raccoglitore dati:

* Indirizzo IP virtuale di gestione
* Nome utente e credenziali di sola lettura
* Porta 443




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP virtuale di gestione (MVIP) | Indirizzo IP virtuale di gestione del cluster SolidFire 


| Nome utente | Nome utilizzato per accedere al cluster SolidFire 


| Password | Password utilizzata per accedere al cluster SolidFire 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Tipo di connessione | Scegli il tipo di connessione 


| Porta di comunicazione | Porta utilizzata per l'API NetApp 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 20 minuti 


| Intervallo di sondaggio sulle prestazioni (sec) | Il valore predefinito è 300 secondi 
|===


== Risoluzione dei problemi

Quando SolidFire segnala un errore, questo viene visualizzato in Data Infrastructure Insights come segue:

_È stato ricevuto un messaggio di errore da un dispositivo SolidFire durante il tentativo di recupero dei dati.  La chiamata era <metodo> (<stringaparametro> ).  Il messaggio di errore del dispositivo era (controllare il manuale del dispositivo): <messaggio>_

Dove:

* <metodo> è un metodo HTTP, come GET o PUT.
* <parameterString> è un elenco separato da virgole di parametri inclusi nella chiamata REST.
* Il <messaggio> è qualsiasi cosa il dispositivo abbia restituito come messaggio di errore.


Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
