---
sidebar: sidebar 
permalink: task_io_density_report_no_root.html 
summary: 'Quando si esegue una query per ottenere un"elevata densità di i/o, si desidera escludere i volumi root.' 
keywords: NetApp, root volume, high I/O, 
---
= Garantire che i report sulla densità io descrivano solo i volumi di dati interni
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Il volume root di NetApp contiene directory e file di configurazione per la gestione del sistema storage. Quando si esegue una query per ottenere un'elevata densità di i/o, si desidera escludere questi volumi root.

Durante il monitoraggio dell'ambiente, è più importante determinare quali volumi di dati interni producono numeri di densità i/o elevati. Per identificare con precisione solo i volumi di dati, è necessario isolare i volumi interni di NetApp dalle query utilizzate per monitorare la densità di i/O.

Questa guida descrive come identificare facilmente gli aggregati root di NetApp, isolarli dai risultati delle query di volume interne e creare regole che escludono eventuali nuovi aggregati root di NetApp man mano che vengono aggiunti al sistema. Le seguenti funzionalità Insight vengono utilizzate per garantire che i report di densità i/o derivino da volumi di dati interni:

* Viene creata una query per identificare tutti gli aggregati root NetApp monitorati da Insight.
* A ciascuno degli aggregati root di NetApp viene assegnata un'annotazione.
* Viene creata una regola di annotazione per applicare l'annotazione ai nuovi aggregati root NetApp.


I passaggi descritti in questa guida possono essere applicati anche ai sistemi storage di altri vendor. Sarà necessario identificare i volumi che contengono directory e file di configurazione per la gestione del sistema di storage e utilizzare procedure simili per escludere questi volumi.



== Creazione di una query per identificare gli aggregati root di NetApp nel tuo ambiente

Le query forniscono ricerche a un livello granulare, in base ai criteri selezionati dall'utente. L'utilizzo di una query consente di cercare volumi interni nell'ambiente che contengono l'aggregato root NetApp.

.Fasi
. Creare una query per identificare gli aggregati root NetApp nel proprio ambiente: Fare clic su *Query > Nuova query > Seleziona tipo di risorsa* (?)
. Fare clic su *pool di storage*
. Immettere il nome dell'aggregato root
+
In questo esempio viene utilizzato "aggr0" come nome. Quando si crea un aggregato, è necessario rispettare solo i seguenti requisiti per il nome:

+
.. Deve iniziare con una lettera o un carattere di sottolineatura (_).
.. Può contenere solo lettere, cifre e caratteri di sottolineatura.
.. Può contenere fino a 250 caratteri. Nella maggior parte dei casi, l'aggregato è il nome aggr0, aggr_0 o qualcosa di simile. Potrebbe essere necessario un processo iterativo per identificare tutti gli aggregati root NetApp nel tuo ambiente.


. Fare clic su *Save* (Salva) e immettere un nome per la nuova query.
+
Come accennato in precedenza, questo potrebbe essere un processo iterativo e richiedere più query per identificare tutti gli aggregati root di NetApp.





== Creare un'annotazione per i volumi root restituiti dalle query

Le annotazioni sono note specializzate assegnate alle risorse, che consentono di filtrare le risorse in base alle annotazioni. L'annotazione creata verrà utilizzata per identificare gli aggregati root di NetApp nel tuo ambiente e garantire che non siano inclusi in un report specifico.

.Prima di iniziare
È necessario aver identificato tutti gli aggregati root che si desidera escludere dal report "High i/o Density" (densità i/o elevata).

.Fasi
. Nel menu Data Infrastructure Insights, fare clic su *Manage > Annotations* (Gestione > Annotazioni*)
. Fare clic su *Aggiungi*
+
.. Inserire il nome dell'annotazione: *RootAgg*
.. Inserire una descrizione dell'annotazione: *Rimuovere l'aggregato root dal report "High i/o Density"*
.. Inserire il tipo di annotazione: *Booleano*


. Fare clic su *Save* (Salva)




== Creare una regola di annotazione per automatizzare l'esclusione di aggregati specifici dal report di densità i/O.

In alternativa all'applicazione manuale delle annotazioni a singole risorse, è possibile applicare automaticamente le annotazioni a più risorse utilizzando le regole di annotazione. Le regole di annotazione si basano sulle query create e, quando vengono eseguite sul sistema, aggiungono nuove risorse a set di risorse esistenti. Quando questi set di asset sono esclusi da un report, anche i nuovi asset vengono automaticamente esclusi.

.Prima di iniziare
È necessario aver creato e salvato una query che identifichi gli aggregati root NetApp identificati nel proprio ambiente.

.Fasi
. Nella barra degli strumenti di Data Infrastructure Insights, fare clic su *Manage > Annotation rules* (Gestisci > regole annotazione*).
. Fare clic su *Aggiungi*. Viene visualizzata la finestra di dialogo Aggiungi regola.
+
.. Nella casella Nome, immettere un nome univoco che descriva la regola: *"RootAggrExclude"*
.. Fare clic su Query e selezionare la query che Insight deve utilizzare per applicare la regola di annotazione a: *"Aggregate0"*
.. Fare clic su Annotation (Annotazione) e selezionare: *"Root agg exclude"*
.. Fare clic su *valore* e immettere *vero*



