---
sidebar: sidebar 
permalink: task_defining_annotations.html 
keywords: annotations, monitor, notes, tags 
summary: Tieni traccia dei dati utilizzando le annotazioni. 
---
= Definizione delle annotazioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si personalizza Data Infrastructure Insights per monitorare i dati in base alle esigenze aziendali, è possibile definire note specializzate, denominate annotazioni, e assegnarle alle risorse.

È possibile assegnare annotazioni alle risorse con informazioni quali fine del ciclo di vita della risorsa, data center, ubicazione dell'edificio, livello di archiviazione o livello di servizio del volume.

L'utilizzo delle annotazioni per monitorare l'ambiente include le seguenti attività di alto livello:

* Creazione o modifica di definizioni per tutti i tipi di annotazione.
* Visualizzazione delle pagine delle risorse e associazione di ciascuna risorsa a una o più annotazioni.
+
Ad esempio, se un bene è in leasing e il leasing scade entro due mesi, potrebbe essere opportuno applicare un'annotazione di fine vita al bene.  Ciò aiuta a impedire che altri utilizzino tale risorsa per un periodo di tempo prolungato.

* Creazione di regole per applicare automaticamente annotazioni a più risorse dello stesso tipo.
* Filtra le risorse in base alle loro annotazioni.




== Tipi di annotazione predefiniti

Data Infrastructure Insights fornisce alcuni tipi di annotazione predefiniti.  Queste annotazioni possono essere utilizzate per filtrare o raggruppare i dati.

È possibile associare le risorse a tipi di annotazione predefiniti come i seguenti:

* Ciclo di vita delle risorse, come compleanno, tramonto o fine vita
* Informazioni sulla posizione di un dispositivo, come centro dati, edificio o piano
* Classificazione delle risorse, ad esempio per qualità (livelli), per dispositivi connessi (livello di switch) o per livello di servizio
* Stato, ad esempio caldo (utilizzo elevato)


Nella tabella seguente sono elencati i tipi di annotazione forniti da Data Infrastructure Insights.

[cols="30,53, 16"]
|===


| Tipi di annotazione | Descrizione | Tipo 


| Alias | Nome intuitivo per una risorsa | Testo 


| Gruppo di risorse di calcolo | Assegnazione di gruppo utilizzata dal raccoglitore dati dei file system host e VM | Lista 


| Centro dati | Posizione fisica | Lista 


| Caldo | Dispositivi sottoposti a un uso intenso su base regolare o al limite della capacità | Booleano 


| Nota | Commenti associati a una risorsa | Test 


| Livello di servizio | Un insieme di livelli di servizio supportati che è possibile assegnare alle risorse.  Fornisce un elenco di opzioni ordinate per volumi interni, qtree e volumi.  Modifica i livelli di servizio per impostare criteri di prestazione per livelli diversi. | Lista 


| Tramonto | Soglia impostata dopo la quale non è più possibile effettuare nuove allocazioni a quel dispositivo.  Utile per migrazioni pianificate e altre modifiche di rete in sospeso. | Data 


| Cambia livello | Opzioni predefinite per l'impostazione delle categorie per gli switch.  In genere, queste designazioni rimangono valide per tutta la vita del dispositivo, anche se è possibile modificarle.  Disponibile solo per gli switch. | Lista 


| Livello | Può essere utilizzato per definire diversi livelli di servizio all'interno del tuo ambiente.  I livelli possono definire il tipo di livello, ad esempio la velocità necessaria (ad esempio, oro o argento).  Questa funzionalità è disponibile solo su volumi interni, qtree, array di archiviazione, pool di archiviazione e volumi. | Lista 


| Gravità della violazione | Grado (ad esempio, maggiore) di una violazione (ad esempio, porte host mancanti o ridondanza mancante), in una gerarchia dall'importanza più alta a quella più bassa. | Lista 
|===

NOTE: Alias, Data Center, Hot, Service Level, Sunset, Switch Level, Tier e Violation Severity sono annotazioni a livello di sistema che non è possibile eliminare o rinominare; è possibile modificare solo i valori assegnati.



== Creazione di annotazioni personalizzate

Utilizzando le annotazioni, puoi aggiungere alle risorse dati aziendali personalizzati e specifici che corrispondono alle tue esigenze aziendali.  Sebbene Data Infrastructure Insights fornisca un set di annotazioni predefinite, potresti voler visualizzare i dati in altri modi.  I dati nelle annotazioni personalizzate integrano i dati del dispositivo già raccolti, come il produttore dell'archiviazione, i volumi numerici e le statistiche sulle prestazioni.  I dati aggiunti tramite annotazioni non vengono rilevati da Data Infrastructure Insights.

.Passi
. Nel menu Data Infrastructure Insights , fare clic su *Gestisci > Annotazioni*.
+
La pagina Annotazioni mostra l'elenco delle annotazioni.

. Fai clic su *+Aggiungi*
. Inserisci un *Nome* e una *Descrizione* dell'annotazione.
+
In questi campi è possibile immettere fino a 255 caratteri.

. Fare clic su *Tipo* e quindi selezionare una delle seguenti opzioni che rappresenta il tipo di dati consentiti in questa annotazione:


.Tipi di annotazione
* Booleano: crea un elenco a discesa con le opzioni Sì e No. Ad esempio, l'annotazione "Allegato diretto" è booleana.
* Data: crea un campo che contiene una data. Ad esempio, se l'annotazione sarà una data, selezionare questa opzione.
* Elenco: crea uno dei seguenti:
+
** Un elenco fisso a discesa
+
Quando altri assegnano questo tipo di annotazione su un dispositivo, non possono aggiungere altri valori all'elenco.

** Un elenco flessibile a discesa
+
Se selezioni l'opzione Aggiungi nuovi valori al volo quando crei questo elenco, quando altri assegnano questo tipo di annotazione su un dispositivo, possono aggiungere altri valori all'elenco.



* Numero: crea un campo in cui l'utente che assegna l'annotazione può immettere un numero.  Ad esempio, se il tipo di annotazione è "Piano", l'utente può selezionare il tipo di valore "numero" e immettere il numero del piano.
* Testo: crea un campo che consente l'inserimento di testo libero.  Ad esempio, potresti immettere "Lingua" come tipo di annotazione, selezionare "Testo" come tipo di valore e immettere una lingua come valore.



NOTE: Dopo aver impostato il tipo e salvato le modifiche, non è più possibile modificare il tipo di annotazione.  Se è necessario modificare il tipo, è necessario eliminare l'annotazione e crearne una nuova.

. Se selezioni Elenco come tipo di annotazione, procedi come segue:
+
.. Seleziona *Aggiungi nuovi valori al volo* se desideri avere la possibilità di aggiungere più valori all'annotazione quando ti trovi su una pagina di risorse, creando un elenco flessibile.
+
Ad esempio, supponiamo di trovarci su una pagina di risorse e che la risorsa abbia l'annotazione Città con i valori Detroit, Tampa e Boston.  Se hai selezionato l'opzione *Aggiungi nuovi valori al volo*, puoi aggiungere valori aggiuntivi a città come San Francisco e Chicago direttamente nella pagina delle risorse, invece di dover andare alla pagina Annotazioni per aggiungerli.  Se non si sceglie questa opzione, non sarà possibile aggiungere nuovi valori di annotazione quando si applica l'annotazione; ciò creerà un elenco fisso.

.. Inserisci un valore e una descrizione nei campi *Valore* e *Descrizione*.
.. Fare clic su *+Aggiungi+* per aggiungere altri valori.
.. Fare clic sull'icona del cestino per eliminare un valore.


. Fai clic su *Salva*
+
Le tue annotazioni vengono visualizzate nell'elenco nella pagina Annotazioni.



.Una nota sulle annotazioni booleane
Quando si filtra un'annotazione booleana, potrebbero essere presentati i seguenti valori su cui filtrare:

* *Qualsiasi*: restituirà _tutti_ i risultati, compresi i risultati impostati su "Sì", "No" o non impostati affatto.
* *Sì*: Restituisce solo risultati "Sì". Si noti che DII mostra "Sì" come segno di spunta nella maggior parte delle tabelle. I valori possono essere impostati su "True", "On", ecc.; DII li tratta tutti come "Sì".
* *No*: restituisce solo risultati "No". Si noti che DII mostra "No" come una "X" nella maggior parte delle tabelle. I valori possono essere impostati su "Falso", "Off", ecc.; DII li tratta tutti come "No".
* *Nessuno*: restituisce solo i risultati in cui l'annotazione non è stata impostata. Chiamati anche valori "Null".


.Dopo aver finito
Nell'interfaccia utente, l'annotazione è immediatamente disponibile per l'uso.
