---
sidebar: sidebar 
permalink: task_dc_lenovo.html 
keywords: data collector,Lenovo, HX Series 
summary: Configurazione di Lenovo data collector. 
---
= Data collector Lenovo
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza il data collector Lenovo per rilevare i dati di inventario e relativi alle performance dei sistemi di storage Lenovo HX.

Nota: Si tratta solo di mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo data collector.



== Requisiti

* Indirizzo IP esterno PRISM
* Nome utente e password dell'amministratore
* Requisiti della porta TCP: 9440




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP esterno PRISM | L'indirizzo IP dei servizi dati esterni per il cluster 


| Nome utente | Nome utente per l'account Admin 


| Password | Password per l'account Admin 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Porta TCP | Porta TCP utilizzata per la connessione all'array. Il valore predefinito è 9440. 


| Intervallo di polling dell'inventario (min) | Intervallo tra i sondaggi di inventario. L'impostazione predefinita è 60 minuti. 


| Intervallo di polling delle performance (sec) | Intervallo tra i sondaggi delle performance. Il valore predefinito è 300 secondi. 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector sono disponibili nella link:concept_requesting_support.html["Supporto"]pagina o nella link:reference_data_collector_support_matrix.html["Matrice di supporto Data Collector"].
