---
sidebar: sidebar 
permalink: task_dc_ibm_ds4000.html 
keywords: data collector, IBM, DS4000 
summary: Raccoglitore dati IBM TotalStorage DS4000 
---
= Raccoglitore dati IBM TotalStorage DS4000
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Questo raccoglitore di dati acquisisce informazioni sull'inventario e sulle prestazioni dal sistema di archiviazione IBM DS4000.  Sono possibili due configurazioni (firmware 6.x e firmware 7.x+) ed entrambe hanno gli stessi valori.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati IBM DS4000.  Per ogni tipologia di asset acquisito viene mostrata la terminologia più comune utilizzata per tale asset.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Disco | Disco 


| Gruppo di volumi | Gruppo di dischi 


| Array di archiviazione | Magazzinaggio 


| Controllore | Nodo di archiviazione 


| Gruppo di volumi | Pool di archiviazione 


| Volume | Volume 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

* Indirizzo IP di ogni array DS5 o FAStT
* Convalida dell'accesso tramite ping dell'indirizzo IP di entrambi i controller sull'array
* Requisiti della porta: 2463




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Elenco separato da virgole degli IP del controller Array SANtricity | Indirizzi IP e/o nomi di dominio completi per i controller di array 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 30 minuti 


| Intervallo di sondaggio delle prestazioni fino a 3600 secondi | Il valore predefinito è 300 secondi 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
