---
sidebar: sidebar 
permalink: task_dc_proxmox_ve.html 
keywords: data collector, Proxmox Virtual Environment, PVE 
summary: Configurare il raccoglitore di dati di Proxmox Virtual Environment. 
---
= Raccoglitore di dati Proxmox Virtual Environment
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il collector DII Proxmox Virtual Environment raccoglierà dati di inventario e prestazioni per macchine virtuali basate su PVE (non container LXC) e host/hypervisor. Questo è un collector basato su API REST HTTPS che deve comunicare con la REST API di Proxmox fornita dal servizio/demone pveproxy che ascolta sulla porta TCP 8006.

Questo data collector utilizza l'autenticazione tramite utente + token. Dovrai creare un account di servizio su ciascun cluster Proxmox, assegnare le autorizzazioni appropriate all'utente e poi generare un token API con gli stessi diritti. Tieni presente che il token di un determinato utente Proxmox NON ha necessariamente gli stessi diritti/autorizzazioni dell'utente. DII avrà generalmente bisogno di diritti globali di livello Audit/Monitor: se stai creando un account di servizio tramite l'interfaccia utente di Proxmox, per PathPermision inizia da "/" , imposta Propagate su "Yes" e sblocca almeno Datastore Audit, Mapping Audit, Pool Audit, SDN Audit, Sys Audit, VM Audit, VM Monitor. Con l'utente creato, puoi poi creare un token di accesso per esso. Ti consigliamo vivamente di creare il token con una scadenza di 0 per assicurarti che non scada mai.



[[terminology]]
== Terminologia

Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per la risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="50,50"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Disco | Disco virtuale 


| Ospite | Ospite 


| Macchina virtuale | Macchina virtuale 


| Magazzinaggio | Archivio dati 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



[[configuration]]
== Configurazione

[cols="50,50"]
|===
| Campo | Descrizione 


| Nome host o indirizzo IP | Nome host Indirizzo IP del sistema storage 


| ID token API | Token API necessario per l'accesso 


| Segreto del token API | Segreto per il token sopra 
|===


[[advanced-configuration]]
== Configurazione avanzata

[cols="50,50"]
|===
| Campo | Descrizione 


| Porta di comunicazione HTTPS | Porta utilizzata per la comunicazione HTTPS (predefinita 8006) 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 20 minuti. 
|===


[[troubleshooting]]
== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
