---
sidebar: sidebar 
permalink: task_config_telegraf_consul.html 
keywords: telegraf, installation, install, consul 
summary: Configurazione del data collector console 
---
= Consul Data Collector
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza questo data collector per raccogliere le metriche da Consul.



== Installazione

. Da *osservabilità > Collector*, fare clic su *+Data Collector*. Scegliere Console.
+
Se non è stato configurato un agente per il ritiro, viene richiesto di selezionare link:task_config_telegraf_agent.html["installare un agente"] il locatario.

+
Se si dispone di un agente già configurato, selezionare il sistema operativo o la piattaforma appropriati e fare clic su *continua*.

. Seguire le istruzioni nella schermata Consul Configuration (Configurazione console) per configurare il data collector. Le istruzioni variano a seconda del tipo di sistema operativo o piattaforma utilizzata per la raccolta dei dati.




== Setup (Configurazione)

Le informazioni sono disponibili nella link:https://www.consul.io/docs/index.html["Documentazione di Consul"].



== Oggetti e contatori per console

Vengono raccolti i seguenti oggetti e i relativi contatori:

[cols="<.<,<.<,<.<,<.<"]
|===
| Oggetto: | Identificatori: | Attributi: | Punti dati: 


| Console | Namespace Check ID Service Node | Nodo IP nodo SO nodo UUID nodo Nome nodo Nome servizio Nome controllo ID servizio Stato | Avviso di passaggio critico 
|===


== Risoluzione dei problemi

Ulteriori informazioni sono disponibili nella link:concept_requesting_support.html["Supporto"] pagina .
