---
sidebar: sidebar 
permalink: task_dc_emc_datadomain.html 
keywords: data collector, Data Domain, EMC, DELL 
summary: Configurazione del raccoglitore dati DELL EMC Data Domain. 
---
= Raccoglitore dati DELL EMC Data Domain
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Questo raccoglitore di dati raccoglie informazioni sull'inventario e sulle prestazioni dai sistemi di storage di deduplicazione DELL EMC Data Domain.  Per configurare questo raccoglitore di dati, è necessario seguire specifiche istruzioni di configurazione e raccomandazioni d'uso.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati Data Domain.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Disco | Disco 


| Vettore | Magazzinaggio 


| Porto FC | Porta 


| Sistema di file | Volume interno 


| Quota | Quota 


| Condivisione NFS e CIFS | Condivisione file 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

Per configurare questo raccoglitore dati sono necessarie le seguenti informazioni:

* Indirizzo IP del dispositivo Data Domain
* Nome utente e password di sola lettura per l'archiviazione Data Domain
* Porta SSH 22




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| indirizzo IP | L'indirizzo IP o il nome di dominio completo dell'array di archiviazione Data Domain 


| Nome utente | Il nome utente per l'array di archiviazione Data Domain 


| Password | La password per l'array di archiviazione Data Domain 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario.  Il valore predefinito è 20. 


| Porta SSH | Porta del servizio SSH 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
