---
sidebar: sidebar 
permalink: task_dc_na_amazon_fsx.html 
keywords: 'data collector, stout, fsx, fsx-netapp, Amazon, AWS, cluster, volume, share, LUN"' 
summary: Raccoglitore dati Amazon FSx for NetApp ONTAP 
---
= Raccoglitore dati Amazon FSx for NetApp ONTAP
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Questo raccoglitore di dati acquisisce dati di inventario e prestazioni da Amazon FSx for NetApp ONTAP.  Questo strumento di raccolta dati verrà reso disponibile in modo incrementale in tutte le regioni del servizio Data Infrastructure Insights .  Contatta il tuo addetto alle vendite se non vedi l'icona per questo raccoglitore nel tuo ambiente Data Infrastructure Insights .


NOTE: Questo raccoglitore di Data Infrastructure Insights richiede un utente ONTAP con un ruolo _Filesystem-Scoped_.  Si prega di rivedere l'AWSlink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/roles-and-users.html["Ruoli e regole"] documentazione per le opzioni disponibili.  Al momento AWS supporta solo un tipo di ruolo utente con ambito filesystem, ovvero _fsxadmin_.  Questo è il ruolo appropriato da utilizzare per il raccoglitore Data Infrastructure Insights .  All'utente dovrebbero essere assegnate tutte e tre queste applicazioni: http, ontapi, ssh.



== Terminologia

Data Infrastructure Insights acquisisce dati di inventario e prestazioni dal raccoglitore dati FSx- NetApp .  Per ogni tipologia di asset acquisito viene mostrata la terminologia più comune utilizzata per l'asset.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Grappolo | Magazzinaggio 


| LUN | Volume 


| Volume | Volume interno 
|===


== Terminologia FSx- NetApp

I seguenti termini si applicano agli oggetti o ai riferimenti che potresti trovare nelle pagine di destinazione delle risorse di storage FSx- NetApp .  Molti di questi termini si applicano anche ad altri raccoglitori di dati.



=== Magazzinaggio

* Modello: elenco delimitato da virgole dei nomi di modelli univoci e discreti all'interno di questo cluster.
* Fornitore – AWS
* Numero di serie: il numero di serie dell'array.
* IP: in genere saranno gli IP o i nomi host configurati nell'origine dati.
* Capacità grezza: somma in base 2 di tutto lo spazio di archiviazione SSD assegnato al file system FSx.
* Latenza: rappresentazione di ciò che sta sperimentando l'host sottoposto a carichi di lavoro, sia in lettura che in scrittura.  Idealmente, Data Infrastructure Insights reperirebbe questo valore direttamente, ma spesso non è così.  Invece dell'array che offre questa funzionalità, Data Infrastructure Insights esegue in genere un calcolo ponderato in base agli IOPS derivato dalle statistiche dei singoli volumi interni.
* Capacità di elaborazione: aggregata dai volumi interni.  Gestione: può contenere un collegamento ipertestuale all'interfaccia di gestione del dispositivo.  Creato a livello di programmazione dalla fonte dati Data Infrastructure Insights come parte della reportistica di inventario.




=== Pool di archiviazione

* Archiviazione: su quale array di archiviazione risiede questo pool.  Obbligatorio.
* Tipo: un valore descrittivo da un elenco di possibilità enumerate.  Nella maggior parte dei casi sarà "Aggregato" o "Gruppo RAID".
* Capacità: i valori qui indicati sono la capacità logica utilizzata, la capacità utilizzabile e la capacità logica totale, nonché la percentuale utilizzata tra queste.
* IOPS: la somma degli IOPS di tutti i volumi allocati su questo pool di archiviazione.
* Throughput: la somma del throughput di tutti i volumi allocati su questo pool di archiviazione.




== Requisiti

Di seguito sono riportati i requisiti per configurare e utilizzare questo raccoglitore dati:

* Devi avere accesso a un account con il ruolo "fsxadmin", con tre applicazioni assegnate: ssh, ontapi, http
* I dettagli dell'account includono nome utente e password.
* Requisiti della porta: 443




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| IP di gestione NetApp | Indirizzo IP o nome di dominio completo del cluster NetApp 


| Nome utente | Nome utente per il cluster NetApp 


| Password | Password per il cluster NetApp 
|===


== Metriche avanzate

Questo raccoglitore di dati raccoglie le seguenti metriche avanzate dall'archiviazione FSx per NetApp ONTAP :

* politica
* nfsv3
* nfsv3:nodo
* nfsv4
* nfsv4_1
* nfsv4_1:nodo
* nfsv4:nodo
* gruppo_politiche
* qtree
* volume
* volume_del_carico_di_lavoro


Si noti che i comandi API e CLI di FSx recuperano alcuni valori di capacità che Data Infrastructure Insights ZAPI non raccoglie, pertanto alcuni valori di capacità (ad esempio quelli per i pool di archiviazione) potrebbero essere diversi in Data Infrastructure Insights rispetto a quelli presenti su FSx stesso.



== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova questo: 


| Ricevi la risposta HTTP 401 o il codice di errore ZAPI 13003 e ZAPI restituisce "Privilegi insufficienti" o "non autorizzato per questo comando" | Controllare nome utente, password e privilegi/permessi dell'utente. 


| ZAPI restituisce "il ruolo del cluster non è cluster_mgmt LIF" | L'AU deve comunicare con l'IP di gestione del cluster.  Controllare l'IP e, se necessario, cambiarlo con un IP diverso 


| Il comando ZAPI fallisce dopo il nuovo tentativo | L'AU ha problemi di comunicazione con il cluster.  Controllare la rete, il numero di porta e l'indirizzo IP.  L'utente dovrebbe anche provare a eseguire un comando dalla riga di comando della macchina AU. 


| AU non è riuscito a connettersi a ZAPI tramite HTTP | Verificare se la porta ZAPI accetta testo in chiaro.  Se AU tenta di inviare testo in chiaro a un socket SSL, la comunicazione fallisce. 


| La comunicazione fallisce con SSLException | AU sta tentando di inviare SSL a una porta in chiaro su un filer.  Verificare se la porta ZAPI accetta SSL oppure utilizzare una porta diversa. 


| Errori di connessione aggiuntivi: la risposta ZAPI ha il codice di errore 13001, "database non aperto". Il codice di errore ZAPI è 60 e la risposta contiene "API non completata in tempo". La risposta ZAPI contiene "initialize_session() ha restituito ambiente NULL". Il codice di errore ZAPI è 14007 e la risposta contiene "Nodo non funzionante". | Controllare la rete, il numero di porta e l'indirizzo IP.  L'utente dovrebbe anche provare a eseguire un comando dalla riga di comando della macchina AU. 
|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
