---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: Configurazione del raccoglitore dati ECS. 
---
= Configurazione del raccoglitore dati EMC ECS
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Questo raccoglitore di dati acquisisce dati di inventario e prestazioni dai sistemi di storage EMC ECS.  Per la configurazione, il raccoglitore dati richiede un indirizzo IP o un nome host del cluster ECS, nonché un nome utente e una password.


NOTE: Dell EMC ECS viene misurato a una tariffa Raw TB diversa da quella delle unità gestite.  Ogni 40 TB di capacità ECS non formattata viene addebitato come 1link:concept_subscribing_to_cloud_insights.html#pricing["Unità gestita (MU)"] .



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati ECS.  Per ogni tipologia di asset acquisito viene mostrata la terminologia più comune utilizzata per tale asset.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Grappolo | Magazzinaggio 


| Inquilino | Pool di archiviazione 


| Secchio | Volume interno 


| Disco | Disco 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

* Un indirizzo IP o un nome host del cluster ECS
* Un nome utente e una password per il sistema ECS
* Porta 4443 (HTTPS).  Richiede connettività in uscita alla porta TCP 4443 sul sistema ECS.




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| ECS Host | Indirizzo IP o nome di dominio completo del sistema ECS 


| Porta host ECS | Porta utilizzata per la comunicazione con l'host ECS 


| ID utente ECS | ID utente per ECS 


| Password | Password utilizzata per ECS 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 360 minuti. 
|===


== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova questo: 


| Errore: autenticazione utente fallita. | Assicurati che le credenziali per questo dispositivo siano corrette. 
|===


=== Prestazione

[cols="2*"]
|===
| Problema: | Prova questo: 


| Errore: non sono stati raccolti dati sufficienti. | * Controllare il timestamp della raccolta nel file di registro e modificare di conseguenza l'intervallo di polling * Attendere un tempo più lungo 


| Errore: l'intervallo di polling delle prestazioni è troppo grande. | Controllare il timestamp della raccolta nel file di registro ${logfile} e modificare di conseguenza l'intervallo di polling 
|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
