---
sidebar: sidebar 
permalink: task_dc_emc_vnx_block.html 
keywords: data collector, EMC, clariion, VNX block 
summary: 'Configurazione di DELL EMC VNX Block Storage (in precedenza CLARiiON).' 
---
= Raccoglitore dati Dell EMC VNX Block Storage (NaviCLI)
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza il raccoglitore dati Dell EMC VNX Block Storage (NaviSec) (in precedenza CLARiiON) per acquisire dati di inventario e prestazioni.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal data collector EMC VNX Block Storage.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Disco | Disco 


| Magazzinaggio | Magazzinaggio 


| Processore di archiviazione | Nodo di archiviazione 


| Questo pool, gruppo RAID | Pool di archiviazione 


| LUN | Volume 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questa fonte dati.



== Requisiti

Per poter raccogliere i dati è necessario soddisfare i seguenti requisiti:

* Un indirizzo IP di ciascun processore di archiviazione a blocchi VNX
* Nome utente e password Navisphere di sola lettura per gli array di archiviazione a blocchi VNX
* NaviSecCli deve essere installato su Data Infrastructure Insights AU
* Convalida dell'accesso: eseguire NaviSecCLI da Data Infrastructure Insights AU su ciascun array utilizzando il nome utente e la password.
* Requisiti della porta: 80, 443
* La versione di NaviSecCLI dovrebbe corrispondere al codice FLARE più recente sul tuo array
* Per migliorare le prestazioni, è necessario abilitare la registrazione delle statistiche.




== Sintassi dell'interfaccia della riga di comando di NaviSphere

naviseccli.exe -h <indirizzo IP> -user <utente> -password <password> -scope <ambito, usa 0 per l'ambito globale> -port <usa 443 per impostazione predefinita> comando



== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP di archiviazione a blocchi VNX | Indirizzo IP o nome di dominio completo dell'archiviazione a blocchi VNX 


| Nome utente | Nome utilizzato per accedere al dispositivo di archiviazione a blocchi VNX. 


| Password | Password utilizzata per accedere al dispositivo di archiviazione a blocchi VNX. 


| Percorso CLI per naviseccli.exe | Percorso completo della cartella contenente l'eseguibile _naviseccli.exe_ 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario.  Il valore predefinito è 40 minuti. 


| Ambito | Ambito client sicuro.  L'impostazione predefinita è Globale. 


| Intervallo di sondaggio sulle prestazioni (sec) | Intervallo tra i sondaggi sulle prestazioni. Il valore predefinito è 300 secondi. 
|===


== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:



=== Inventario

[cols="2a, 2a"]
|===
| Problema: | Prova questo: 


 a| 
Errore:

* Agente non in esecuzione
* Impossibile trovare naviseccli
* Impossibile eseguire alcun comando

 a| 
* Verificare che NaviSphere CLI sia installato su Cloud Insight Acquisition Unit
* Non hai selezionato l'opzione "Usa client sicuro" nella procedura guidata di configurazione del raccoglitore dati e non hai installato una versione non sicura di Naviphere CLI.
* Verificare che la directory di installazione di NaviSphere CLI sia corretta nella configurazione del raccoglitore dati
* Verificare che l'IP dell'archiviazione a blocchi VNX sia corretto nella configurazione del raccoglitore dati:
* Dall'unità di acquisizione Data Infrastructure Insights :
+
** Aprire un CMD.
** Cambiare la directory nella directory di installazione configurata
** Prova a stabilire una connessione con il dispositivo di archiviazione a blocchi VNX digitando "navicli -h {ip} getagent" (sostituisci {ip} con l'IP effettivo)






 a| 
Errore: 4.29 emc235848 emc241018 getall Impossibile analizzare le informazioni sull'alias dell'host
 a| 
Ciò è probabilmente causato da un problema di danneggiamento FLARE 29 del database dell'iniziatore host sull'array stesso.  Vedere gli articoli della knowledge base EMC: emc235848, emc241018.  Puoi anche controllare https://now.netapp.com/Knowledgebase/solutionarea.asp?id=kb58128[]



 a| 
Errore: impossibile recuperare i Meta LUN.  Errore durante l'esecuzione di java -jar navicli.jar
 a| 
* Modificare la configurazione del raccoglitore dati per utilizzare il client sicuro (consigliato)
* Installare navicli.jar nel percorso CLI per navicli.exe O naviseccli.exe
* Nota: navicli.jar è obsoleto a partire dalla versione 6.26 di EMC Navisphere
* Il file navicli.jar potrebbe essere disponibile su \ http://powerlink.emc.com




 a| 
Errore: i pool di archiviazione non segnalano i dischi sul processore di servizio all'indirizzo IP configurato
 a| 
Configurare il raccoglitore dati con entrambi gli IP del processore di servizio, separati da una virgola



 a| 
Errore: errore di mancata corrispondenza della revisione
 a| 
* In genere, ciò è causato dall'aggiornamento del firmware sul dispositivo di archiviazione a blocchi VNX, ma non dall'aggiornamento dell'installazione di NaviCLI.exe.  Ciò potrebbe essere causato anche dalla presenza di dispositivi diversi con firmware diversi, ma di una sola CLI installata (con una versione firmware diversa).
* Verificare che sia il dispositivo che l'host eseguano versioni identiche del software:
+
** Dall'unità di acquisizione Data Infrastructure Insights , aprire una finestra della riga di comando
** Cambiare la directory nella directory di installazione configurata
** Stabilisci una connessione con il dispositivo CLARiiON digitando “navicli -h <ip> getagent”
** Cerca il numero di versione nelle prime due righe.  Esempio: “Agente Rev: 6.16.2 (0.1)”
** Cerca e confronta la versione sulla prima riga.  Esempio: "Navisphere CLI Revisione 6.07.00.04.07"






 a| 
Errore: configurazione non supportata - nessuna porta Fibre Channel
 a| 
Il dispositivo non è configurato con alcuna porta Fibre Channel.  Attualmente sono supportate solo le configurazioni FC.  Verificare che questa versione/firmware sia supportata.

|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
