---
sidebar: sidebar 
permalink: task_dc_emc_powerstore.html 
keywords: data collector, PowerStore, EMC, DELL 
summary: Configurazione del raccoglitore dati DELL EMC PowerStore. 
---
= Raccoglitore dati Dell EMC PowerStore
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il raccoglitore dati EMC PowerStore raccoglie informazioni di inventario dallo storage EMC PowerStore.  Per la configurazione, il raccoglitore dati richiede l'indirizzo IP dei processori di archiviazione e un nome utente e una password di sola lettura.

Il raccoglitore dati EMC PowerStore raccoglie le relazioni di replica da volume a volume che PowerStore coordina tra altri array di storage.  Data Infrastructure Insights mostra un array di archiviazione per ogni cluster PowerStore e raccoglie i dati di inventario per i nodi e le porte di archiviazione su quel cluster.  Non vengono raccolti dati di pool di archiviazione o di volume.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario da questo raccoglitore di dati.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| ospite | ospite 


| host_volume_mapping | host_volume_mapping 


| hardware (ha Unità sotto l'oggetto "extra_details"): Unità | Disco 


| Apparecchio | StoragePool 


| Grappolo | Array di archiviazione 


| Nodo | StorageNode 


| fc_port | Porta 


| volume | Volume 


| Volume interno | file system 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

Per configurare questo raccoglitore dati sono necessarie le seguenti informazioni:

* Indirizzo IP o nome di dominio completo del processore di archiviazione
* Nome utente e password di sola lettura




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Gateway PowerStore | Indirizzi IP o nomi di dominio completi dello storage PowerStore 


| Nome utente | Nome utente per PowerStore 


| Password | Password utilizzata per PowerStore 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Porta HTTPS | Il valore predefinito è 443 


| Intervallo di sondaggio dell'inventario (minuti) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 60 minuti. 
|===
La raccolta delle prestazioni di PowerStore di Cloud Insight sfrutta i dati sorgente con granularità di 5 minuti di PowerStore.  Pertanto, Data Infrastructure Insights esegue il polling di tali dati ogni cinque minuti e questa operazione non è configurabile.



== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
