---
sidebar: sidebar 
permalink: task_configure_data_collectors.html 
keywords: acquisition, AU, data collector, collector, notification, notify, 
summary: Istruzioni generali per il data collector 
---
= Configurazione di Data Collector
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
È possibile configurare Data Collector nell'ambiente Data Infrastructure Insights per raccogliere dati dai dispositivi del data center.

.Prima di iniziare
* È necessario aver configurato un'unità di acquisizione prima di iniziare la raccolta dei dati.
* Sono necessarie le credenziali per i dispositivi da cui si stanno raccogliendo i dati.
* Per tutti i dispositivi da cui si stanno raccogliendo i dati sono necessari indirizzi di rete, informazioni sull'account e password.


.Fasi
. Dal menu Data Infrastructure Insights (analisi dell'infrastruttura dati), fare clic su *Observability (osservabilità) > Collector* (collezionisti)
+
Il sistema visualizza i Data Collector disponibili organizzati in base al vendor.

. Fare clic su *+ Collector* e selezionare il data collector da configurare.
+
Nella finestra di dialogo è possibile configurare il data collector e aggiungere un'unità di acquisizione.

. Inserire un nome per il data collector.
. Fare clic su *Advanced Configuration* (Configurazione avanzata) per aggiungere ulteriori campi di configurazione. (Non tutti i data collettori richiedono una configurazione avanzata).
. Fare clic su *Test Configuration* per verificare che il data collector sia configurato correttamente.
. Fare clic su *Aggiungi Collector* per salvare la configurazione e aggiungere il data collector al tenant di Data Infrastructure Insights.


Potrebbero essere necessari fino a due periodi di polling prima che i dati del servizio vengano visualizzati in dashboard o disponibili per la query.

* primo sondaggio di inventario: immediatamente
* 1° sondaggio sui dati delle performance per stabilire un riferimento: immediatamente dopo il sondaggio dell'inventario
* secondo sondaggio sulle performance: entro 15 secondi dal completamento del primo sondaggio sulle performance


Il polling procede quindi in base agli intervalli di polling delle performance e dell'inventario configurati.
