---
sidebar: sidebar 
permalink: task_dc_dell_xc_series.html 
keywords: data collector, Dell, EMC, xc 
summary: Configurazione del raccoglitore dati Dell EMC XC Series. 
---
= Raccoglitore dati Dell EMC serie XC
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza questo raccoglitore di dati per scoprire informazioni sull'inventario e sulle prestazioni degli array di storage Dell EMC XC Series.



== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP esterno Prism | Indirizzo IP del server XC 


| Nome utente | Nome utente per il server XC 


| Password | Password utilizzata per il server XC 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Porta TCP | Porta utilizzata per la comunicazione TCP con il server XC 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 60 minuti. 


| Intervallo di sondaggio sulle prestazioni (min) | Intervallo tra i sondaggi sulle prestazioni. Il valore predefinito è 300 secondi. 
|===


== Risoluzione dei problemi

Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
