---
sidebar: sidebar 
permalink: task_business_entity_annotations.html 
keywords: annotations, business entity 
summary: Le annotazioni delle entità aziendali possono essere utilizzate per il monitoraggio e la segnalazione delle risorse nella gerarchia aziendale 
---
= Annotazioni delle entità aziendali
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Crea e gestisci entità aziendali per il tuo ambiente aziendale utilizzando il tipo di annotazione *Entità aziendale*.



== Creazione di un'entità aziendale

Per creare un'entità aziendale, procedere come segue:

. Fare clic su *Gestisci > Annotazioni* e quindi sul collegamento _Entità aziendale_.
+
Viene visualizzato l'elenco delle entità aziendali attualmente definite.

. Fare clic su *+ Entità aziendale*.
. Immettere i valori per i campi *Inquilino*, *Linea di attività*, *Unità aziendale* e *Progetto*.
+
Puoi lasciare vuoto qualsiasi campo che non sia pertinente alla tua entità aziendale.

. Se in precedenza hai immesso un valore per un campo, puoi selezionarlo dal menu a discesa.  Non è necessario digitarlo di nuovo.



NOTE: I valori selezionati devono comporre un'entità aziendale totale univoca.  Ad esempio, se hai già un'entità aziendale con i valori _A / B / C / D_ in quell'ordine, non puoi creare un'altra entità aziendale con quegli stessi valori in quell'ordine.  Tuttavia, è possibile creare un'entità aziendale con tali valori in un ordine diverso.



== Applicazione di un'entità aziendale a un oggetto

Il modo più semplice per applicare un'entità aziendale a uno o più oggetti è tramite una query.

. Fare clic su *Query > +Nuova query* e selezionare il tipo di oggetto desiderato.  È possibile applicare filtri per restringere ulteriormente i risultati.
. Fare clic sulla casella di controllo per selezionare gli oggetti a cui si desidera applicare l'entità aziendale.
. Fare clic su *Azioni in blocco* e selezionare *Aggiungi annotazione*.
. Selezionare l'annotazione _Entità aziendale_ e selezionare il valore dell'entità aziendale desiderato dall'elenco.
. Fare clic su *Salva* per applicare l'entità aziendale agli oggetti.


È anche possibile applicare un'entità aziendale a un singolo oggetto accedendo alla landing page delle risorse dell'oggetto e cliccando su *+Annotazione) nella sezione Dati utente.

È anche possibile configurare unlink:task_create_annotation_rules.html["Regola di annotazione"] per applicare entità aziendali agli oggetti.


NOTE: A un oggetto può essere associata una sola entità aziendale.



== Rimozione di un'entità aziendale da un oggetto

Per rimuovere un'entità aziendale da uno o più oggetti, eseguire una query e selezionare l'oggetto/gli oggetti, fare clic su *Azioni in blocco* e selezionare _Rimuovi annotazione_.  Selezionare l'annotazione Entità aziendale e fare clic su *Elimina*.
