---
sidebar: sidebar 
permalink: task_query_assign_multiple_applications.html 
summary: Utilizzare una query per assegnare più applicazioni o annotazioni agli oggetti oppure per rimuoverle. 
keywords: query, queries, application, annotation, multiple 
---
= Assegnazione di più applicazioni o rimozione di più applicazioni dalle risorse
:hardbreaks:
:allow-uri-read: 


[role="lead"]
È possibile assegnare piùlink:task_create_application.html["applicazioni"] aggiungere o rimuovere più applicazioni dalle risorse utilizzando una query anziché doverle assegnare o rimuovere manualmente.


NOTE: Puoi usare questi passaggi per aggiungere o rimuoverelink:task_defining_annotations.html["annotazioni"] allo stesso modo.

.Prima di iniziare
Devi aver già creato una query che trovi tutte le risorse che vuoi modificare.

.Passi
. Fare clic su *Esplora* e selezionare *Query metriche*.
+
Viene visualizzata la pagina Query.

. Fare clic sul nome della query che trova le risorse.
+
Viene visualizzato l'elenco delle risorse associate alla query.

. Selezionare le risorse desiderate nell'elenco oppure fare clic sulla casella di controllo in alto per selezionare Tutto.
+
Viene visualizzato il menu a discesa Azioni in blocco.

. Per aggiungere un'applicazione alle risorse selezionate, fare clic su Azioni in blocco e selezionare *Aggiungi applicazione*.
. Selezionare una o più applicazioni.
+
È possibile selezionare più applicazioni per host, volumi interni, qtree e macchine virtuali; tuttavia, è possibile selezionare una sola applicazione per un volume o una condivisione.

. Fare clic su *Salva*.
. Per rimuovere un'applicazione assegnata alle risorse, fare clic su Azioni in blocco e selezionare *Rimuovi applicazione*.
. Seleziona l'applicazione o le applicazioni che desideri rimuovere.
. Fare clic su *Elimina*.


Tutte le nuove applicazioni assegnate sovrascrivono tutte le applicazioni sulla risorsa derivate da un'altra risorsa.  Ad esempio, i volumi ereditano le applicazioni dagli host e quando a un volume vengono assegnate nuove applicazioni, la nuova applicazione ha la precedenza sull'applicazione derivata.

Dopo aver fatto clic su _Salva_ per un'aggiunta in blocco o su _Rimuovi_ per un'eliminazione in blocco, Data Infrastructure Insights ti informa che l'azione richiederà del tempo.  Puoi ignorare questo messaggio; l'azione continuerà in background.


NOTE: Per ambienti con grandi quantità di risorse correlate, l'ereditarietà delle assegnazioni delle applicazioni a tali risorse potrebbe richiedere diversi minuti.  Se si hanno molti beni correlati, si prega di attendere più tempo affinché l'eredità avvenga.
