---
sidebar: sidebar 
permalink: task_dc_rubrik_cdm.html 
keywords: data collector, Rubrik, 
summary: Configurazione del raccoglitore dati Rubrik CDM. 
---
= Raccoglitore dati CDM Rubrik
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza il raccoglitore dati Rubrik per acquisire dati di inventario e prestazioni dagli storage appliance Rubrik.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati Rubrik.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Grappolo | Deposito, piscina di stoccaggio 


| Nodo | Nodo di archiviazione 


| Disco | Disco 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questa fonte dati.



== Requisiti

Per configurare questo raccoglitore dati sono necessari i seguenti elementi:

* L'unità di acquisizione Data Infrastructure Insights avvierà le connessioni alla porta TCP 443 al cluster Rubrik.  Un collettore per cluster.
* Indirizzo IP del cluster Rubrik.
* Nome utente e password per il cluster.
* Indirizzo IP o nome host del cluster Rubrik.
* Per l'autenticazione di base, un nome utente e una password per il cluster.  Se preferisci utilizzare l'autenticazione basata sull'account di servizio, hai bisogno di un account di servizio, di un segreto e di un ID organizzazione
* Requisito porta: HTTPS 443




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Proprietà intellettuale | Indirizzo IP del cluster Rubrik 


| Nome utente / Account di servizio | Nome utente per il cluster 


| Password / Segreto | Password per il cluster 


| ID organizzazione per l'account di servizio | Deve essere la stringa completa, ad esempio "Organization:::nnnnnn-nnnn....." 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 60 


| Intervallo di sondaggio sulle prestazioni (sec) | Il valore predefinito è 300 
|===


== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova questo: 


| Ho ricevuto un messaggio che indica che è stato creato più di uno spazio di archiviazione. | Verificare che il cluster sia configurato correttamente e che il collettore punti a un singolo cluster. 


| Il sondaggio fallisce con 400 [Richiesta non valida].... ManagedId non valido.... | Hai popolato il campo ID organizzazione con un valore, ma il cluster Rubrik NON ritiene che si tratti di un ID organizzazione valido, nonostante il messaggio di errore di Rubrik lo chiami "ManagedId" 
|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
