---
sidebar: sidebar 
permalink: task_dc_nutanix.html 
keywords: data collector, Nutanix, NX Series 
summary: Configurazione del data collector Nutanix NX. 
---
= Raccoglitore dati Nutanix NX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights utilizza il raccoglitore di dati Nutanix NX per individuare dati di inventario e di prestazioni dei sistemi di storage Nutanix NX.



[[terminology]]
== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati Nutanix.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="50,50"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Pool di archiviazione | Pool di archiviazione 


| Contenitore Nutanix | Volume interno 


| Contenitore Nutanix | Condivisione file 


| Condivisione NFS | Condividere 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



[[requirements]]
== Requisiti

* L'indirizzo IP dei servizi dati esterni per il cluster
* Nome utente e password di sola lettura, a meno che non siano in uso volumi_groups, nel qual caso sono richiesti nome utente e password amministratore
* Requisito porta: HTTPS 443




[[configuration]]
== Configurazione

[cols="50,50"]
|===
| Campo | Descrizione 


| Indirizzo IP esterno Prism | L'indirizzo IP dei servizi dati esterni per il cluster 


| Nome utente | Nome utente per l'account amministratore 


| Password | Password per l'account amministratore 
|===


[[advanced-configuration]]
== Configurazione avanzata

[cols="50,50"]
|===
| Campo | Descrizione 


| porta TCP | Porta TCP utilizzata per connettersi all'array Nutanix.  Il valore predefinito è 9440. 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 60 minuti. 


| Intervallo di sondaggio delle prestazioni (sec) | Intervallo tra i sondaggi sulle prestazioni. Il valore predefinito è 300 secondi. 
|===


[[troubleshooting]]
== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
