---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: Configurare NetApp StorageGRID data collector 
keywords: data collector, queries, create, storagegrid 
---
= Data collector NetApp StorageGRID
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il data collector NetApp StorageGRID supporta la raccolta di inventario e performance dalle configurazioni StorageGRID.

[NOTE]
====
Per garantire una misurazione coerente dei diritti DII su tutti i sistemi StorageGRID , indipendentemente dalla topologia e dalla configurazione hardware sottostante, Data Infrastructure Insights utilizza la capacità totale disponibile (storagegrid_storage_utilization_total_space_bytes), anziché la capacità RAW basata sul layout del disco fisico.

Per i clienti che utilizzano il modello di licenza basato sulla capacità, StorageGRID viene misurato come storage "Oggetto".

Per i clienti che utilizzano il modello di licenza legacy (MU), StorageGRID viene misurato come storage secondario, a una velocità di 40 TiB per 1 MU.

====


== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal NetApp StorageGRID Collector. Per ogni tipo di risorsa acquisita, viene visualizzata la terminologia più comune utilizzata per questa risorsa. Durante la visualizzazione o la risoluzione dei problemi di questo data collector, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Vendor/modello | Termine di approfondimento sull'infrastruttura dati 


| StorageGRID | Storage 


| Nodo | Nodo 


| Tenant | Pool di storage 


| Bucket | Volume interno 
|===


== Requisiti

Di seguito sono riportati i requisiti per la configurazione di questa origine dati:

* Indirizzo IP host StorageGRID
* Nome utente e password per un utente a cui sono stati assegnati i ruoli di Metric Query e accesso tenant
* Porta 443




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP host StorageGRID | Gestione Indirizzo IP virtuale dell'appliance StorageGRID 


| Nome utente | Nome utilizzato per accedere all'appliance StorageGRID 


| Password | Password utilizzata per accedere all'appliance StorageGRID 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo polling inventario (min) | Il valore predefinito è 60 minuti 


| Intervallo di polling delle performance (sec) | Il valore predefinito è 900 secondi 
|===


== Single Sign-on (SSO)

Le link:https://docs.netapp.com/sgws-112/index.jsp["StorageGRID"]versioni del firmware hanno versioni API corrispondenti; le versioni 3,0 API e più recenti supportano l'accesso SSO (Single Sign-on).

|===


| Versione del firmware | Versione di API | Supporto SSO (Single Sign-on) 


| 11,1 | 2 | No 


| 11,2 | 3,0 | Sì 


| 11,5 | 3,3 | Sì 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector sono disponibili nella link:concept_requesting_support.html["Supporto"]pagina o nella link:reference_data_collector_support_matrix.html["Matrice di supporto Data Collector"].
