---
sidebar: sidebar 
permalink: task_query_assign_multiple_applications.html 
summary: Utilizzare una query per assegnare più applicazioni o annotazioni agli oggetti o per rimuoverli da più applicazioni o annotazioni. 
keywords: query, queries, application, annotation, multiple 
---
= Assegnazione di più applicazioni o rimozione di più applicazioni dalle risorse
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
È possibile assegnare link:task_create_application.html["applicazioni"]o rimuovere più applicazioni dalle risorse utilizzando una query anziché doverle assegnare o rimuovere manualmente.


NOTE: È possibile utilizzare questi passaggi per aggiungere o rimuovere link:task_defining_annotations.html["annotazioni"]nello stesso modo.

.Prima di iniziare
È necessario aver già creato una query che trovi tutte le risorse da modificare.

.Fasi
. Fare clic su *Explore* e selezionare *Metric Query*.
+
Viene visualizzata la pagina Query.

. Fare clic sul nome della query che trova le risorse.
+
Viene visualizzato l'elenco delle risorse associate alla query.

. Selezionare le risorse desiderate nell'elenco o fare clic sulla casella di controllo in alto per selezionare tutto.
+
Viene visualizzato il menu a discesa azioni in blocco.

. Per aggiungere un'applicazione alle risorse selezionate, fare clic su azioni in blocco e selezionare *Aggiungi applicazione*.
. Selezionare una o più applicazioni.
+
È possibile selezionare più applicazioni per host, volumi interni, qtree e macchine virtuali; tuttavia, è possibile selezionare una sola applicazione per un volume o una condivisione.

. Fare clic su *Save* (Salva).
. Per rimuovere un'applicazione assegnata alle risorse, fare clic su azioni in blocco e selezionare *Rimuovi applicazione*.
. Selezionare l'applicazione o le applicazioni che si desidera rimuovere.
. Fare clic su *Delete* (Elimina).


Tutte le nuove applicazioni assegnate hanno la precedenza su quelle derivate da un'altra risorsa. Ad esempio, i volumi ereditano le applicazioni dagli host e, quando vengono assegnate nuove applicazioni a un volume, la nuova applicazione ha la precedenza sull'applicazione derivata.

Dopo aver fatto clic su _Save_ su un'operazione di aggiunta bulk o _Remove_ su un'azione di eliminazione bulk, Data Infrastructure Insights informa che l'azione richiederà del tempo. È possibile ignorare questo messaggio; l'azione continuerà in background.


NOTE: Per gli ambienti con grandi quantità di risorse correlate, l'ereditarietà delle assegnazioni delle applicazioni a tali risorse potrebbe richiedere diversi minuti. Attendere più tempo per l'ereditarietà se si dispone di molte risorse correlate.
