---
sidebar: sidebar 
permalink: task_dc_emc_unisphere_rest.html 
keywords: data collector, Unisphere, EMC 
summary: Configurazione del raccoglitore dati REST Dell EMC Unisphere. 
---
= Configurazione del raccoglitore dati REST Dell EMC Unisphere
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Questo strumento di raccolta dati acquisisce dati di inventario e prestazioni dai sistemi di gestione Dell EMC Unisphere per PowerMax/Vmax 3.

Si prega di notare che Dell/EMC non ha introdotto le statistiche per volume fino a Unisphere 10.0; questo raccoglitore dati supporta la versione 9.2.0+, ma non sarà in grado di raccogliere statistiche sui volumi poiché non esistono.

Un'istanza di Unisphere per Vmax/PowerMax può gestire uno o più array di archiviazione Symmetrix Vmax 3 o superiore: per impostazione predefinita, questo collector tenterà di rilevare tutti quelli "locali" per quell'istanza di Unisphere.  Se un'istanza Unisphere rileva array "remoti" (ovvero quelli connessi tramite replica SRDF), questi verranno ignorati e per individuarli è necessario creare un ulteriore raccoglitore Unisphere in Data Infrastructure Insights puntato a qualsiasi istanza Unisphere in quel sito li rilevi come locali.

Per la configurazione, il raccoglitore dati richiede un indirizzo IP/FQDN del server Unisphere, connettività TCP alla porta 8443 e un nome utente e una password.



== Requisiti

* Un indirizzo IP/nome di dominio completo del server Unisphere
* Nome utente e password
* Porta 8443.




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP del server Unisphere | Indirizzo IP o nome di dominio completo del server Unisphere 


| Porto Unisphere | Il valore predefinito è 8443 


| Nome utente | Nome utente per il server Unisphere 


| Password | Password utilizzata per il server Unisphere 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 40 minuti. 


| Intervallo di sondaggio sulle prestazioni (sec) | Intervallo tra i sondaggi sulle prestazioni. 


| Scegli "Escludi" o "Includi" per specificare un elenco | Specificare se includere o escludere le VM 


| Elenco dispositivi filtro inventario | Elenco delle VM da filtrare (separate da virgole o da punto e virgola se nel valore viene utilizzata una virgola) per il filtraggio 


| Intervallo di sondaggio sulle prestazioni di Unisphere (sec) | Il valore predefinito è 300 secondi 
|===


== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova questo: 


| Errore: autenticazione utente fallita. | Assicurati che le credenziali per questo dispositivo siano corrette. 


| Stato recente dell'inventario: dati inattesi recuperati - Array ha segnalato 0 volume | In genere indica un problema di autorizzazione (non di autenticazione).  Assicurati che le tue credenziali siano corrette e che il nome utente abbia il potere di elencare tutti i volumi e di visualizzarne gli attributi. 
|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
