---
sidebar: sidebar 
permalink: task_dc_ms_anf.html 
keywords: data collector, azure, Netapp files, anf 
summary: Configurazione di Azure NetApp Files data collector. 
---
= Configurazione del data collector Azure NetApp Files
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Data Infrastructure Insights utilizza il data collector di Azure NetApp Files per acquisire i dati di inventario e delle prestazioni.



== Requisiti

Per configurare questo data collector sono necessarie le seguenti informazioni.

* Requisito porta: 443 HTTPS
* IP REST di Azure Management (management.azure.com)
* ID client principale del servizio Azure (account utente)
* Chiave di autenticazione principale del servizio Azure (password utente)
* Devi configurare un account Azure per il rilevamento Data Infrastructure Insights.
+
Una volta configurato correttamente l'account e registrata l'applicazione in Azure, si disporranno delle credenziali necessarie per rilevare l'istanza di Azure con Data Infrastructure Insights. Il seguente collegamento descrive come configurare l'account per il rilevamento:



https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[]



== Configurazione

Inserire i dati nei campi di raccolta dati in base alla tabella riportata di seguito:

[cols="2*"]
|===
| Campo | Descrizione 


| ID client principale del servizio Azure | ID di accesso ad Azure 


| ID tenant Azure | ID tenant Azure 


| Chiave di autenticazione principale del servizio Azure | Chiave di autenticazione per l'accesso 


| Ho capito che Microsoft mi ha dato la bolletta per le richieste API | Controlla questa sezione per verificare che Microsoft ti presenti la fattura per le richieste API effettuate tramite il polling Insight. 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo polling inventario (min) | Il valore predefinito è 60 
|===


== Risoluzione dei problemi

* Le credenziali utilizzate dal data collector ANF devono avere accesso a qualsiasi sottoscrizione di Azure che contenga volumi ANF.
* Se l'accesso a Reader causa un errore nella raccolta delle performance, provare a concedere l'accesso del collaboratore a livello di gruppo di risorse.


Ulteriori informazioni su questo Data Collector sono disponibili nella link:concept_requesting_support.html["Supporto"]pagina o nella link:reference_data_collector_support_matrix.html["Matrice di supporto Data Collector"].
