---
sidebar: sidebar 
permalink: task_dc_na_7mode.html 
keywords: data collector, 7-mode, NetApp 
summary: Configurazione del raccoglitore dati NetApp in modalità 7. 
---
= NetApp Data ONTAP funzionante nel raccoglitore dati a 7 modalità
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Per i sistemi di storage che utilizzano il software Data ONTAP che opera in modalità 7, si utilizza il raccoglitore dati a 7 modalità, che sfrutta la CLI per ottenere dati su capacità e prestazioni.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati NetApp a 7 modalità.  Per ogni tipologia di asset acquisito viene mostrata la terminologia più comune utilizzata per tale asset.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:


NOTE: Questo raccoglitore di dati èlink:task_getting_started_with_cloud_insights.html#useful-definitions["deprecato"] .

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Disco | Disco 


| Gruppo di incursione | Gruppo di dischi 


| Filer | Magazzinaggio 


| Filer | Nodo di archiviazione 


| Aggregato | Pool di archiviazione 


| LUN | Volume 


| Volume | Volume interno 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

Per configurare e utilizzare questo raccoglitore dati è necessario quanto segue:

* Indirizzi IP del controller di archiviazione FAS e del partner.
* Porta 443
* Un nome utente e una password di livello amministratore personalizzati per il controller e il controller partner con le seguenti capacità di ruolo per 7-Mode:
+
** "api-*": utilizzare questa opzione per consentire a OnCommand Insight di eseguire tutti i comandi API di storage NetApp .
** "login-http-admin": utilizzare questa opzione per consentire a OnCommand Insight di connettersi allo storage NetApp tramite HTTP.
** "security-api-vfiler": utilizzare questa opzione per consentire a OnCommand Insight di eseguire i comandi API di archiviazione NetApp per recuperare le informazioni sull'unità vFiler.
** "cli-options": utilizzare per leggere le opzioni del sistema di archiviazione.
** "cli-lun": accedi a questi comandi per gestire i LUN.  Visualizza lo stato (percorso LUN, dimensione, stato online/offline e stato condiviso) del LUN specificato o della classe di LUN.
** "cli-df": utilizzare per visualizzare lo spazio libero su disco.
** "cli-ifconfig": utilizzare per visualizzare le interfacce e gli indirizzi IP.






== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo del sistema di archiviazione | Indirizzo IP o nome di dominio completo per il sistema di archiviazione NetApp 


| Nome utente | Nome utente per il sistema di archiviazione NetApp 


| Password | Password per il sistema di archiviazione NetApp 


| Indirizzo del partner HA nel cluster | Indirizzo IP o nome di dominio completo per il partner HA 


| Nome utente del partner HA nel cluster | Nome utente per il partner HA 


| Password del file partner HA nel cluster | Password per il partner HA 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 20 minuti. 


| Tipo di connessione | HTTPS o HTTP, visualizza anche la porta predefinita 


| Sostituisci porta di connessione | Se vuoto, utilizzare la porta predefinita nel campo Tipo di connessione, altrimenti immettere la porta di connessione da utilizzare 


| Intervallo di sondaggio sulle prestazioni (sec) | Intervallo tra i sondaggi sulle prestazioni. Il valore predefinito è 300 secondi. 
|===


== Collegamento dei sistemi di stoccaggio

In alternativa all'utilizzo dell'utente amministrativo predefinito per questo raccoglitore dati, è possibile configurare un utente con diritti amministrativi direttamente sui sistemi di archiviazione NetApp , in modo che questo raccoglitore dati possa acquisire dati dai sistemi di archiviazione NetApp .

Per connettersi ai sistemi di storage NetApp è necessario che l'utente specificato al momento dell'acquisizione del pfiler principale (su cui esiste il sistema di storage) soddisfi le seguenti condizioni:

* L'utente deve essere su vfiler0 (root filer/pfiler).
+
I sistemi di stoccaggio vengono acquisiti al momento dell'acquisizione del pfiler principale.

* I seguenti comandi definiscono le capacità del ruolo utente:
+
** "api-*": utilizzare questa opzione per consentire a Data Infrastructure Insights di eseguire tutti i comandi API di storage NetApp .
+
Questo comando è necessario per utilizzare ZAPI.

** "login-http-admin": utilizzare questa opzione per consentire a Data Infrastructure Insights di connettersi allo storage NetApp tramite HTTP.  Questo comando è necessario per utilizzare ZAPI.
** "security-api-vfiler": utilizzare questa opzione per consentire a Data Infrastructure Insights di eseguire comandi API di storage NetApp per recuperare le informazioni sull'unità vFiler.
** "cli-options": per il comando "options" e utilizzato per l'IP del partner e le licenze abilitate.
** "cli-lun": accedi a questi comandi per gestire i LUN.  Visualizza lo stato (percorso LUN, dimensione, stato online/offline e stato condiviso) del LUN specificato o della classe di LUN.
** "cli-df": per i comandi "df -s", "df -r", "df -A -r" e utilizzato per visualizzare lo spazio libero.
** "cli-ifconfig": per il comando "ifconfig -a" e utilizzato per ottenere l'indirizzo IP del filer.
** "cli-rdfile": per il comando "rdfile /etc/netgroup" e utilizzato per ottenere i netgroup.
** "cli-date": per il comando "date" e utilizzato per ottenere la data completa per ottenere copie Snapshot.
** "cli-snap": per il comando "snap list" e utilizzato per ottenere copie Snapshot.




Se non vengono fornite le autorizzazioni cli-date o cli-snap, l'acquisizione può essere completata, ma le copie Snapshot non vengono segnalate.

Per acquisire correttamente una sorgente dati 7-Mode e non generare avvisi sul sistema di archiviazione, è necessario utilizzare una delle seguenti stringhe di comando per definire i ruoli utente.  La seconda stringa elencata qui è una versione semplificata della prima:

* login-http-admin,api-*,security-api-vfile,cli-rdfile,cli-options,cli-df,cli-lun,cli-ifconfig,cli-date,cli-snap,_
* login-http-admin,api-* ,security-api-vfile,cli-




== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova questo: 


| Ricevi la risposta HTTP 401 o il codice di errore ZAPI 13003 e ZAPI restituisce "Privilegi insufficienti" o "non autorizzato per questo comando" | Controllare nome utente, password e privilegi/permessi dell'utente. 


| Errore "Impossibile eseguire il comando" | Verificare se l'utente dispone delle seguenti autorizzazioni sul dispositivo: • api-* • cli-date • cli-df • cli-ifconfig • cli-lun • cli-operations • cli-rdfile • cli-snap • login-http-admin • security-api-vfiler Verificare inoltre se la versione ONTAP è supportata da Data Infrastructure Insights e verificare se le credenziali utilizzate corrispondono alle credenziali del dispositivo 


| La versione del cluster è < 8.1 | La versione minima supportata dal cluster è 8.1.  Aggiorna alla versione minima supportata. 


| ZAPI restituisce "il ruolo del cluster non è cluster_mgmt LIF" | L'AU deve comunicare con l'IP di gestione del cluster.  Controllare l'IP e, se necessario, cambiarlo con un IP diverso 


| Errore: "I filtri in modalità 7 non sono supportati" | Ciò può accadere se si utilizza questo raccoglitore di dati per scoprire il filtro in modalità 7.  Cambiare l'IP in modo che punti al filer cdot. 


| Il comando ZAPI fallisce dopo il nuovo tentativo | L'AU ha problemi di comunicazione con il cluster.  Controllare la rete, il numero di porta e l'indirizzo IP.  L'utente dovrebbe anche provare a eseguire un comando dalla riga di comando della macchina AU. 


| AU non è riuscito a connettersi a ZAPI | Verificare la connettività IP/porta e verificare la configurazione ZAPI. 


| AU non è riuscito a connettersi a ZAPI tramite HTTP | Verificare se la porta ZAPI accetta testo in chiaro.  Se AU tenta di inviare testo in chiaro a un socket SSL, la comunicazione fallisce. 


| La comunicazione fallisce con SSLException | AU sta tentando di inviare SSL a una porta in chiaro su un filer.  Verificare se la porta ZAPI accetta SSL oppure utilizzare una porta diversa. 


| Errori di connessione aggiuntivi: la risposta ZAPI ha il codice di errore 13001, "database non aperto". Il codice di errore ZAPI è 60 e la risposta contiene "API non completata in tempo". La risposta ZAPI contiene "initialize_session() ha restituito ambiente NULL". Il codice di errore ZAPI è 14007 e la risposta contiene "Nodo non funzionante". | Controllare la rete, il numero di porta e l'indirizzo IP.  L'utente dovrebbe anche provare a eseguire un comando dalla riga di comando della macchina AU. 


| Errore di timeout del socket con ZAPI | Controllare la connettività del filer e/o aumentare il timeout. 


| Errore "I cluster in modalità C non sono supportati dalla sorgente dati in modalità 7" | Controllare l'IP e modificarlo in un cluster in modalità 7. 


| Errore "Impossibile connettersi a vFiler" | Verificare che le capacità di acquisizione dell'utente includano almeno quanto segue: api-* security-api-vfiler login-http-admin Verificare che il filer esegua almeno la versione ONTAPI 1.7. 
|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
