---
sidebar: sidebar 
permalink: task_defining_annotations.html 
keywords: annotations, monitor, notes, tags 
summary: Tenere traccia dei dati utilizzando le annotazioni. 
---
= Definizione delle annotazioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante la personalizzazione di Data Infrastructure Insights per il monitoraggio dei dati per i tuoi requisiti aziendali, puoi definire note specializzate, denominate annotazioni e assegnarle alle tue risorse.

È possibile assegnare annotazioni alle risorse con informazioni quali fine del ciclo di vita delle risorse, data center, posizione dell'edificio, Tier di storage o livello di servizio del volume.

L'utilizzo delle annotazioni per il monitoraggio dell'ambiente include le seguenti attività di alto livello:

* Creazione o modifica delle definizioni per tutti i tipi di annotazione.
* Visualizzazione delle pagine delle risorse e associazione di ciascuna risorsa a una o più annotazioni.
+
Ad esempio, se una risorsa viene affittata e il leasing scade entro due mesi, potrebbe essere necessario applicare un'annotazione di fine ciclo di vita alla risorsa. In questo modo si impedisce ad altri di utilizzare tale risorsa per un periodo di tempo prolungato.

* Creazione di regole per applicare automaticamente le annotazioni a più risorse dello stesso tipo.
* Filtrare le risorse in base alle annotazioni.




== Guardalo in azione

link:https://media.netapp.com/video-detail/248621bd-6619-5dc8-9718-5d78d0fd21da["Annotazioni e regole di annotazione (video),window=read-later"]



== Tipi di annotazione predefiniti

Data Infrastructure Insights fornisce alcuni tipi di annotazioni predefinite. Queste annotazioni possono essere utilizzate per filtrare o raggruppare i dati.

È possibile associare le risorse ai tipi di annotazione predefiniti, ad esempio:

* Ciclo di vita delle risorse, ad esempio compleanno, tramonto o fine vita
* Informazioni sulla posizione di un dispositivo, ad esempio data center, edificio o piano
* Classificazione delle risorse, ad esempio per qualità (Tier), per dispositivi connessi (livello di switch) o per livello di servizio
* Stato, ad esempio hot (utilizzo elevato)


La tabella seguente elenca i tipi di annotazioni forniti da Data Infrastructure Insights.

[cols="30,53, 16"]
|===


| Tipi di annotazione | Descrizione | Tipo 


| Alias | Nome intuitivo per una risorsa | Testo 


| Gruppo di risorse di calcolo | Assegnazione del gruppo utilizzata dal data collector host e VM Filesystems | Elenco 


| Data center | Ubicazione fisica | Elenco 


| Caldo | Dispositivi che utilizzano in modo intensivo su base regolare o alla soglia di capacità | Booleano 


| Nota | Commenti associati a una risorsa | Test 


| Livello di servizio | Un insieme di livelli di servizio supportati che è possibile assegnare alle risorse. Fornisce un elenco di opzioni ordinate per volumi interni, qtree e volumi. Modificare i livelli di servizio per impostare le policy di performance per diversi livelli. | Elenco 


| Tramonto | Soglia impostata dopo la quale non è possibile assegnare nuove allocazioni a quel dispositivo. Utile per migrazioni pianificate e altre modifiche di rete in sospeso. | Data 


| Livello switch | Opzioni predefinite per l'impostazione delle categorie per gli switch. In genere, queste designazioni rimangono valide per la durata del dispositivo, anche se è possibile modificarle. Disponibile solo per gli switch. | Elenco 


| Tier | Può essere utilizzato per definire diversi livelli di servizio all'interno del proprio ambiente. I Tier possono definire il tipo di livello, ad esempio la velocità necessaria (ad esempio, oro o argento). Questa funzione è disponibile solo su volumi interni, qtree, storage array, storage pool e volumi. | Elenco 


| Severità della violazione | Classificazione (ad esempio, maggiore) di una violazione (ad esempio, porte host mancanti o ridondanza mancante), in una gerarchia di importanza da massima a minima. | Elenco 
|===

NOTE: Alias, data center, hot, livello di servizio, Sunset, Switch Level (livello switch), Tier (livello) e Violation Severity (gravità violazione) sono annotazioni a livello di sistema che non è possibile eliminare o rinominare; è possibile modificare solo i valori assegnati.



== Creazione di annotazioni personalizzate

Utilizzando le annotazioni, è possibile aggiungere dati personalizzati specifici del business che corrispondano alle esigenze del business alle risorse. Sebbene Data Infrastructure Insights fornisca una serie di annotazioni predefinite, è possibile che si desideri visualizzare i dati in altri modi. I dati contenuti nelle annotazioni personalizzate integrano i dati dei dispositivi già raccolti, ad esempio produttore dello storage, volumi numerici e statistiche delle performance. I dati aggiunti mediante le annotazioni non vengono rilevati da Data Infrastructure Insights.

.Fasi
. Nel menu Data Infrastructure Insights, fare clic su *Manage > Annotations* (Gestione > Annotazioni*).
+
La pagina Annotazioni visualizza l'elenco delle annotazioni.

. Fare clic su *+Aggiungi*
. Inserire *Nome* e *Descrizione* dell'annotazione.
+
È possibile inserire fino a 255 caratteri in questi campi.

. Fare clic su *Type* (tipo), quindi selezionare una delle seguenti opzioni che rappresentano il tipo di dati consentiti in questa annotazione:


.Tipi di annotazione
Boolean: Crea un elenco a discesa con le opzioni yes e no. Ad esempio, l'annotazione "Direct Attached" è Boolean. Data: Consente di creare un campo che contiene una data. Ad esempio, se l'annotazione sarà una data, selezionare questa opzione. List (elenco): Crea una delle seguenti opzioni: * Un elenco a discesa fisso

+ quando altri assegnano questo tipo di annotazione su un dispositivo, non possono aggiungere altri valori all'elenco. * Un elenco a discesa flessibile

+ se si seleziona l'opzione Aggiungi nuovi valori al volo quando si crea questo elenco, quando altri assegnano questo tipo di annotazione su un dispositivo, possono aggiungere altri valori all'elenco.

Numero: Consente di creare un campo in cui l'utente che assegna l'annotazione può immettere un numero. Ad esempio, se il tipo di annotazione è "Floor" (piano), l'utente può selezionare il tipo di valore "Number" (numero) e inserire il numero di piano.

Testo: Consente di creare un campo che consenta il testo in formato libero. Ad esempio, è possibile inserire "Lingua" come tipo di annotazione, selezionare "testo" come tipo di valore e immettere una lingua come valore.


NOTE: Dopo aver impostato il tipo e salvato le modifiche, non è possibile modificare il tipo di annotazione. Se è necessario modificare il tipo, eliminare l'annotazione e crearne una nuova.

. Se si seleziona Elenca come tipo di annotazione, procedere come segue:
+
.. Selezionare *Add new values on the fly* (Aggiungi nuovi valori in tempo reale) se si desidera aggiungere altri valori all'annotazione quando ci si trova in una pagina di risorse, che crea un elenco flessibile.
+
Si supponga, ad esempio, di trovarsi in una pagina di risorse e di avere l'annotazione City (Città) con i valori Detroit, Tampa e Boston. Se è stata selezionata l'opzione *Aggiungi nuovi valori al volo*, è possibile aggiungere valori aggiuntivi a Città come San Francisco e Chicago direttamente nella pagina delle risorse, invece di andare alla pagina Annotazioni per aggiungerli. Se non si sceglie questa opzione, non è possibile aggiungere nuovi valori di annotazione quando si applica l'annotazione; in questo modo si crea un elenco fisso.

.. Immettere un valore e una descrizione nei campi *valore* e *Descrizione*.
.. Fare clic su *+Aggiungi+* per aggiungere altri valori.
.. Fare clic sull'icona Cestino per eliminare un valore.


. Fare clic su *Save* (Salva)
+
Le annotazioni vengono visualizzate nell'elenco della pagina Annotazioni.



.Al termine
Nell'interfaccia utente, l'annotazione è immediatamente disponibile per l'utilizzo.
