---
sidebar: sidebar 
permalink: task_dc_ms_anf.html 
keywords: data collector, azure, Netapp files, anf 
summary: Configurazione del raccoglitore dati Azure NetApp Files . 
---
= Configurazione del raccoglitore dati Azure NetApp Files
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza il raccoglitore dati Azure NetApp Files per acquisire dati di inventario e prestazioni.



== Requisiti

Per configurare questo raccoglitore dati sono necessarie le seguenti informazioni.

* Requisito porta: 443 HTTPS
* IP REST di gestione di Azure (management.azure.com)
* ID client dell'entità servizio di Azure (account utente)
* Chiave di autenticazione dell'entità servizio di Azure (password utente)
* È necessario configurare un account Azure per l'individuazione di Data Infrastructure Insights .
+
Una volta configurato correttamente l'account e registrata l'applicazione in Azure, si avranno le credenziali necessarie per individuare l'istanza di Azure con Data Infrastructure Insights.  Il seguente link descrive come impostare l'account per la scoperta:



https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[]



== Configurazione

Inserire i dati nei campi del raccoglitore dati secondo la tabella seguente:

[cols="2*"]
|===
| Campo | Descrizione 


| ID client dell'entità servizio di Azure | ID di accesso ad Azure 


| ID tenant di Azure | ID tenant di Azure 


| Chiave di autenticazione dell'entità servizio di Azure | Chiave di autenticazione di accesso 


| Capisco che Microsoft mi fattura le richieste API | Seleziona questa casella per verificare di aver compreso che Microsoft ti addebita le richieste API effettuate tramite polling di Insight. 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 60 
|===


== Risoluzione dei problemi

* Le credenziali utilizzate dal raccoglitore dati ANF devono avere accesso a tutte le sottoscrizioni di Azure che contengono volumi ANF.
* Se l'accesso come lettore causa il fallimento della raccolta delle prestazioni, provare a concedere l'accesso come collaboratore a livello di gruppo di risorse.


Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
