---
sidebar: sidebar 
permalink: task_modify_delete_query.html 
summary: Modifica le query esistenti cambiando criteri e colonne, con opzioni di salvataggio flessibili per aggiornare, rinominare o creare nuove versioni, oltre alla possibilità di eliminare le query quando non sono più necessarie. 
keywords: query, queries, modify, edit, delete, remove 
---
= Modifica o eliminazione di una query
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Gestisci le tue query in modo efficace modificando i criteri di ricerca, aggiungendo o rimuovendo colonne e scegliendo tra opzioni di salvataggio flessibili. Aggiorna le query esistenti, crea nuove versioni o elimina query che non sono più necessarie per mantenere la tua libreria di query organizzata e aggiornata.



[[modifying-a-query]]
== Modifica di una query

.Passi
. Fare clic su *Esplora* e selezionare *Tutte le query metriche*.
+
Viene visualizzata la pagina Query.

. Fare clic sul nome della query
. Per aggiungere un criterio alla query, fare clic sull'icona Colonne e selezionare una metrica o un attributo dall'elenco.


Dopo aver apportato tutte le modifiche necessarie, procedere in uno dei seguenti modi:

* Fare clic sul pulsante *Salva* per salvare la query con il nome utilizzato inizialmente.
* Fare clic sul menu a discesa accanto al pulsante *Salva* e selezionare *Salva con nome* per salvare la query con un altro nome.  Ciò non sovrascrive la query originale.
* Fare clic sul menu a discesa accanto al pulsante *Salva* e selezionare *Rinomina* per modificare il nome della query utilizzato inizialmente.  Ciò sovrascrive la query originale.
* Fare clic sul menu a discesa accanto al pulsante *Salva* e selezionare *Ignora modifiche* per ripristinare la query alle ultime modifiche salvate.




[[deleting-a-query]]
== Eliminazione di una query

Per eliminare una query, fare clic su *Query* e selezionare *Mostra tutte le query*, quindi eseguire una delle seguenti operazioni:

. Fare clic sul menu "tre punti" a destra della query e fare clic su *Elimina*.
. Fare clic sul nome della query e selezionare *Elimina* dal menu a discesa *Salva*.

