---
sidebar: sidebar 
permalink: task_dc_ibm_svc.html 
keywords: IBM, SVC,SAN 
summary: Configurazione di IBM SAN Volume Controller Data Collector. 
---
= Configurazione di IBM SAN Volume Controller Data Collector
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Il data collector IBM SAN Volume Controller (SVC) raccoglie i dati di inventario e performance utilizzando SSH, supportando una varietà di dispositivi che eseguono il sistema operativo SVC.

L'elenco dei dispositivi supportati include modelli come SVC, v7000, v5000 e v3700. Fare riferimento alla matrice di supporto Data Infrastructure Insights per i modelli e le versioni firmware supportati.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal data collector IBM SVC. Per ogni tipo di asset acquisito da Data Infrastructure Insights viene visualizzata la terminologia più comune utilizzata per questa risorsa. Durante la visualizzazione o la risoluzione dei problemi di questo data collector, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Vendor/modello | Termine di approfondimento sull'infrastruttura dati 


| Disco | Disco 


| Cluster | Storage 


| Nodo | Nodo di storage 


| Gruppo Mdisk | Pool di storage 


| Disco virtuale | Volume 


| Mdisk | LUN e percorsi back-end 
|===
Nota: Si tratta solo di mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo data collector.



=== Requisiti di inventario

* Indirizzo IP di ciascun cluster SVC
* Porta 22 disponibile
* Nome utente e password di sola lettura




=== Requisiti relativi alle performance

* SVC Console, obbligatoria per qualsiasi cluster SVC e richiesta per il pacchetto di base Discovery SVC.
* Le credenziali richiedono un livello di accesso amministrativo solo per copiare i file delle prestazioni dai nodi del cluster al nodo di configurazione.
* Abilitare la raccolta dati connettendosi al cluster SVC tramite SSH ed eseguendo: _Svctask startstats -interval 1_
+
Nota: In alternativa, abilitare la raccolta dati utilizzando l'interfaccia utente di gestione SVC.





== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzi IP del cluster | Indirizzi IP o nomi di dominio pienamente qualificati dello storage SVC 


| Nome utente inventario | Nome utente per la CLI SVC 


| Password inventario | Password per la CLI SVC 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo polling inventario (min) | Intervallo tra i sondaggi di inventario. L'impostazione predefinita è 40 minuti. 


| Intervallo di polling delle performance (sec) | Intervallo tra i sondaggi delle performance. Il valore predefinito è 300 secondi. 


| Per ripulire i file stats scaricati | Selezionare questa casella di controllo per eliminare i file di statistiche scaricati 
|===


== Risoluzione dei problemi

Alcune operazioni da eseguire in caso di problemi con questo data collector:

[cols="2*"]
|===
| Problema: | Prova: 


| Errore: "Impossibile avviare il comando perché non è stato eseguito sul nodo di configurazione." | Il comando deve essere eseguito sul nodo di configurazione. 
|===
Alcune operazioni da eseguire in caso di problemi con questo data collector:

[cols="2*"]
|===
| Problema: | Prova: 


| Errore: "Impossibile avviare il comando perché non è stato eseguito sul nodo di configurazione." | Il comando deve essere eseguito sul nodo di configurazione. 
|===
Ulteriori informazioni su questo Data Collector sono disponibili nella link:concept_requesting_support.html["Supporto"]pagina o nella link:reference_data_collector_support_matrix.html["Matrice di supporto Data Collector"].
