---
sidebar: sidebar 
permalink: task_dc_ibm_ds4000.html 
keywords: data collector, IBM, DS4000 
summary: Data collector IBM TotalStorage DS4000 
---
= Data collector IBM TotalStorage DS4000
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Questo data collector acquisisce le informazioni di inventario e performance dal sistema storage IBM DS4000. Esistono due configurazioni possibili (firmware 6.x e firmware 7.x+), entrambe con gli stessi valori.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal data collector IBM DS4000. Per ogni tipo di risorsa acquisita, viene visualizzata la terminologia più comune utilizzata per questa risorsa. Durante la visualizzazione o la risoluzione dei problemi di questo data collector, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Vendor/modello | Termine di approfondimento sull'infrastruttura dati 


| Disco | Disco 


| Gruppo di volumi | Gruppo di dischi 


| Array di storage | Storage 


| Controller | Nodo di storage 


| Gruppo di volumi | Pool di storage 


| Volume | Volume 
|===
Nota: Si tratta solo di mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo data collector.



== Requisiti

* Indirizzo IP di ciascun array DS5 o FAStT
* Convalida dell'accesso tramite ping dell'indirizzo IP di entrambi i controller sull'array
* Requisiti di porta: 2463




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Elenco separato da virgole degli IP controller SANtricity array | Indirizzi IP e/o nomi di dominio pienamente qualificati per i controller degli array 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo polling inventario (min) | Il valore predefinito è 30 minuti 


| Intervallo di polling delle performance fino a 3600 secondi | Il valore predefinito è 300 secondi 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector sono disponibili nella link:concept_requesting_support.html["Supporto"]pagina o nella link:reference_data_collector_support_matrix.html["Matrice di supporto Data Collector"].
