---
sidebar: sidebar 
permalink: task_dc_redhat_virtualization.html 
keywords: data collector, Red Hat Virtualization 
summary: Configurazione del raccoglitore dati di Red Hat Virtualization. 
---
= Raccoglitore dati di Red Hat Virtualization
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il raccoglitore di dati DII per Red Hat Virtualization supporta anche il progetto open source oVirt, e Oracle Linux Virtualization Manager. Questo raccoglitore di dati comunica tramite REST API con l'interfaccia HTTPS sulla stazione di gestione.



== Terminologia

Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per la risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Disco | Disco virtuale 


| Ospite | Ospite 


| Macchina virtuale | Macchina virtuale 


| Dominio di archiviazione | Archivio dati 


| Unità logica | LUN 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

* Indirizzo IP/nome host del server RHV/oVirt/OLVM sulla porta 443 tramite API REST
* Nome utente e password di sola lettura
* RHV Version 3.0+/Ovirt 4.0+/OLVM 4.0+




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP del server RHV/Ovirt/OLVM | Indirizzo IP della stazione di gestione 


| Nome utente | Nome utente 


| Password | Password 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Porta di comunicazione HTTPS | Porta utilizzata per la comunicazione HTTPS con RHEV 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 20 minuti. 


| Prestazioni della VM | Abilita la raccolta delle prestazioni 


| Intervallo di rilevamento delle prestazioni (sec) | Il valore predefinito è 900 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
