---
sidebar: sidebar 
permalink: task_dc_brocade_rest.html 
keywords: data collector, Brocade, FC switch, FOS, Rest 
summary: Configurazione del raccoglitore dati REST FOS Brocade . 
---
= Brocade FOS REST Data Collector
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza il raccoglitore REST Brocade FOS per scoprire l'inventario e le prestazioni dei dispositivi switch Brocade che eseguono il firmware FabricOS (FOS) 8.2 e versioni successive.  Si prega di notare che le prime versioni 8.2 FOS potrebbero presentare bug nell'API REST; si consiglia vivamente di eseguire l'ultima versione FOS supportata dalla piattaforma.

Nota: il livello "utente" predefinito di FOS non è sufficientemente potente per consentire a Data Infrastructure Insights di visualizzare tutti gli aspetti logici di un dispositivo. È necessario un account utente con il "Ruolo chassis" abilitato, nonché autorizzazioni su tutti i Virtual Fabric configurati su uno switch.

Ecco un esempio di come creare un account utente con "privilegi minimi" per l'utilizzo di Data Infrastructure Insights in una sessione SSH su un dispositivo FOS:

userConfig --add NetAppCIUser -r utente -l 1-128 -c utente -p Qwerty!

Verrà creato un utente "NetAppCIUser" con password "Qwerty!".  Questo utente ha il ruolo "utente" (-r) in tutti i 128 possibili fabric virtuali (-l).  Questo utente ha inoltre il ruolo "Chassis" richiesto (-c) con accesso a livello utente assegnato.

Per impostazione predefinita, questo collector tenterà di rilevare tutti i dispositivi FOS che fanno parte di tutti i fabric di cui fa parte lo switch.

Nota: l'utente di sola lettura predefinito di FOS, "user", NON dispone di autorizzazioni di visualizzazione su tutti i Virtual Fabric, né di autorizzazioni di "ruolo chassis".  Ciò significa che le probabilità di successo saranno basse utilizzando "user" con Data Infrastructure Insights, che deve comprendere sia la configurazione fisica che quella logica del dispositivo FOS.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati Brocade FOS REST.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Interruttore | Interruttore 


| Porta | Porta 


| Tessuto virtuale, tessuto fisico | Tessuto 


| Zona | Zona 


| Interruttore logico | Interruttore logico 


| Zona LSAN | Zona IVR 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

* Deve esserci connettività TCP su tutti gli switch nel fabric.  Questo tipo di raccoglitore di dati proverà senza problemi sia HTTP che HTTPS per ogni dispositivo nel fabric.  Se selezioni la casella di controllo _Scopri tutti gli switch nel fabric_, Data Infrastructure Insights identifica tutti gli switch nel fabric; tuttavia, necessita della connettività TCP a questi switch aggiuntivi per rilevarli.
* È necessario lo stesso account a livello globale su tutti gli switch del fabric.  È possibile utilizzare l'interfaccia Web del dispositivo per confermare l'accesso.




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Cambia IP | Indirizzo IP o nome di dominio completo dello switch FOS 


| Nome utente | Nome utente per lo switch 


| Password | Password per lo switch 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Dispositivi esclusi | Elenco separato da virgole degli indirizzi IPv4 dei dispositivi da escludere dal polling. 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario.  Il valore predefinito è 60. 


| Scopri tutti gli interruttori nel tessuto | Seleziona per scoprire tutti gli switch nel fabric. 


| Scegli di preferire HBA rispetto agli alias di zona | Scegliere se privilegiare HBA o alias di zona. 


| Tipo di connessione | HTTP o HTTPS. 


| Si noti che questa impostazione modifica solo il protocollo che CI tenta di utilizzare per primo per dispositivo: CI tenterà automaticamente il protocollo opposto se il valore predefinito fallisce. | Sostituisci porta TCP 


| Specificare una porta se non si utilizza quella predefinita. | Intervallo di sondaggio sulle prestazioni (sec) 
|===


== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova questo: 


| La funzione Test mi avvisa che un protocollo non è accessibile | Un dato dispositivo Brocade FOS 8.2+ vorrà comunicare solo tramite HTTP o HTTPS: se uno switch ha un certificato digitale installato, genererà errori HTTP se si tenta di comunicare con esso tramite HTTP non crittografato anziché HTTPS.  La funzione di test tenta la comunicazione sia con HTTP che con HTTPS: se il test indica che un protocollo funziona, è possibile salvare in sicurezza il collettore e non preoccuparsi che l'altro protocollo non abbia avuto successo: il collettore tenterà entrambi i protocolli durante la raccolta e fallirà solo se nessuno dei due funziona. 


| Errore: l'inventario fallisce con 401 Non autorizzato...Chiave di sessione non valida... | Si tratta di un bug specifico presente in alcune delle prime versioni 8.2 FOS, come la 8.2.1c, che NON supportano correttamente l'autenticazione di base HTTP.  Aggiorna a una versione successiva 8.2 o 9.* 


| Errore: "Data Infrastructure Insights ha ricevuto un ruolo chassis non valido" | Verificare che all'utente configurato in questa origine dati sia stata concessa l'autorizzazione al ruolo chassis. 


| Errore: "Indirizzo IP dello chassis non corrispondente" | Modificare la configurazione dell'origine dati per utilizzare l'indirizzo IP dello chassis. 


| L'inventario fallisce con un errore 403 Forbidden | Potrebbe trattarsi semplicemente di credenziali errate oppure potrebbe indicare che si sta tentando di utilizzare un ruolo non sufficientemente potente. Ricordare che gli utenti di livello "utente" NON hanno il diritto "Ruolo chassis" richiesto né l'accesso alla visualizzazione di Virtual Fabric non predefiniti. 
|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
