---
sidebar: sidebar 
permalink: task_dc_aws_s3.html 
keywords: data collector, S3, Storage 
summary: Configurazione di AWS S3 come raccoglitore di dati di archiviazione. 
---
= Configurazione di AWS S3 come raccoglitore di dati di archiviazione
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza AWS S3 come raccoglitore di dati di archiviazione per acquisire dati di inventario e prestazioni dalle istanze AWS S3.



== Requisiti

Per raccogliere dati da AWS S3 come dispositivi di archiviazione, è necessario disporre delle seguenti informazioni:

* Devi avere uno dei seguenti requisiti:
+
** Il *ruolo IAM* per il tuo account cloud AWS, se utilizzi l'autenticazione del ruolo IAM.  Il ruolo IAM si applica solo se l'unità di acquisizione è installata su un'istanza AWS.
** ID *Chiave di accesso IAM* e chiave di accesso segreta per il tuo account cloud AWS, se utilizzi l'autenticazione con chiave di accesso IAM.


* Devi avere il privilegio "organizzazione elenco"
* Porta 443 HTTPS
* Le istanze AWS S3 possono essere segnalate come macchine virtuali o (in modo meno naturale) come host.  I volumi EBS possono essere segnalati sia come VirtualDisk utilizzato dalla VM, sia come DataStore che fornisce la capacità per VirtualDisk.


Le chiavi di accesso sono costituite da un ID chiave di accesso (ad esempio, AKIAIOSFODNN7EXAMPLE) e da una chiave di accesso segreta (ad esempio, wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY).  Le chiavi di accesso vengono utilizzate per firmare le richieste programmatiche inviate ad AWS se si utilizzano gli SDK AWS, REST o le operazioni API di query.  Queste chiavi sono fornite insieme al contratto Amazon.



== Configurazione

Inserire i dati nei campi del raccoglitore dati secondo la tabella seguente:

[cols="2*"]
|===
| Campo | Descrizione 


| Regione AWS | Scegli la regione AWS 


| Ruolo IAM | Da utilizzare solo se acquisito su un'AU in AWS.  Vedi sotto per maggiori informazioni su<<iam-role,Ruolo IAM>> . 


| ID chiave di accesso AWS IAM | Inserisci l'ID della chiave di accesso AWS IAM.  Obbligatorio se non si utilizza il ruolo IAM. 


| Chiave di accesso segreta AWS IAM | Inserisci la chiave di accesso segreta AWS IAM.  Obbligatorio se non si utilizza il ruolo IAM. 


| Capisco che AWS mi fattura le richieste API | Seleziona questa opzione per verificare di aver compreso che AWS ti fattura le richieste API effettuate tramite polling di Data Infrastructure Insights . 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Ruolo multiaccount | Ruolo per l'accesso alle risorse in diversi account AWS. 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 60 


| Scegli "Escludi" o "Includi" per applicare il filtro alle VM in base ai tag | Specificare se includere o escludere le VM tramite tag durante la raccolta dei dati.  Se è selezionato "Includi", il campo Chiave tag non può essere vuoto. 


| Intervallo di sondaggio sulle prestazioni (sec) | Il valore predefinito è 1800 
|===


== Chiave di accesso IAM

Le chiavi di accesso sono credenziali a lungo termine per un utente IAM o per l'utente root dell'account AWS.  Le chiavi di accesso vengono utilizzate per firmare richieste programmatiche all'AWS CLI o all'AWS API (direttamente o tramite l'AWS SDK).

Le chiavi di accesso sono composte da due parti: un ID della chiave di accesso e una chiave di accesso segreta.  Quando si utilizza l'autenticazione _IAM Access Key_ (anziché l'autenticazione _IAM Role_), è necessario utilizzare sia l'ID della chiave di accesso che la chiave di accesso segreta insieme per l'autenticazione delle richieste.  Per maggiori informazioni, consulta la documentazione di Amazon sulink:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html["Chiavi di accesso"] .



== Ruolo IAM

Quando si utilizza l'autenticazione _IAM Role_ (anziché l'autenticazione IAM Access Key), è necessario assicurarsi che il ruolo creato o specificato disponga delle autorizzazioni appropriate necessarie per accedere alle risorse.

Ad esempio, se si crea un ruolo IAM denominato _InstanceS3ReadOnly_, è necessario impostare il criterio per concedere l'autorizzazione di accesso all'elenco di sola lettura S3 a tutte le risorse S3 per questo ruolo IAM.  Inoltre, è necessario concedere l'accesso STS (Security Token Service) affinché questo ruolo possa assumere ruoli in più account.

Dopo aver creato un ruolo IAM, puoi allegarlo quando crei una nuova istanza S3 o un'istanza S3 esistente.

Dopo aver associato il ruolo IAM _InstanceS3ReadOnly_ a un'istanza S3, sarà possibile recuperare le credenziali temporanee tramite i metadati dell'istanza in base al nome del ruolo IAM e utilizzarle per accedere alle risorse AWS da parte di qualsiasi applicazione in esecuzione su questa istanza S3.

Per maggiori informazioni consulta la documentazione di Amazon sulink:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html["Ruoli IAM"] .

Nota: il ruolo IAM può essere utilizzato solo quando l'unità di acquisizione è in esecuzione in un'istanza AWS.



== Mappatura dei tag Amazon alle annotazioni Data Infrastructure Insights

Il raccoglitore dati AWS S3 as Storage include un'opzione che consente di popolare le annotazioni di Data Infrastructure Insights con tag configurati su S3.  Le annotazioni devono essere denominate esattamente come i tag AWS.  Data Infrastructure Insights popolerà sempre le annotazioni di tipo testo con lo stesso nome e farà un "miglior tentativo" per popolare le annotazioni di altri tipi (numero, valore booleano, ecc.).  Se l'annotazione è di un tipo diverso e il raccoglitore dati non riesce a popolarla, potrebbe essere necessario rimuovere l'annotazione e ricrearla come tipo di testo.

Si noti che AWS distingue tra maiuscole e minuscole, mentre Data Infrastructure Insights non distingue tra maiuscole e minuscole.  Pertanto, se si crea un'annotazione denominata "OWNER" in Data Infrastructure Insights e tag denominati "OWNER", "Owner" e "owner" in S3, tutte le varianti di "owner" in S3 verranno mappate all'annotazione "OWNER" di Cloud Insight.



== Raccolta da account figlio AWS

Data Infrastructure Insights supporta la raccolta di account figlio per AWS all'interno di un singolo raccoglitore dati AWS.  La configurazione per questa raccolta viene eseguita nell'ambiente AWS:

* È necessario configurare ogni account figlio in modo che disponga di un ruolo AWS che consenta all'ID dell'account principale di accedere ai dettagli S3 dall'account figlio.
* Ogni account figlio deve avere il nome del ruolo configurato come la stessa stringa.
* Inserisci questa stringa del nome del ruolo nella sezione *Configurazione avanzata* di Data Infrastructure Insights AWS Data Collector, nel campo *Ruolo tra account*.
* L'account in cui è installato il collector deve disporre dei privilegi di _amministratore di accesso delegato_.  Vedi illink:https://docs.aws.amazon.com/accounts/latest/reference/using-orgs-delegated-admin.html["Documentazione AWS"] per maggiori informazioni.


Best Practice: si consiglia vivamente di assegnare la policy predefinita AWS _AmazonS3ReadOnlyAccess_ all'account principale S3.  Inoltre, all'utente configurato nell'origine dati deve essere assegnata almeno la policy predefinita _AWSOrganizationsReadOnlyAccess_ per poter interrogare AWS.

Per informazioni sulla configurazione dell'ambiente per consentire a Data Infrastructure Insights di raccogliere dati dagli account figlio AWS, consultare quanto segue:

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html["Tutorial: delegare l'accesso tra account AWS utilizzando i ruoli IAM"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html["Configurazione AWS: fornire l'accesso a un utente IAM in un altro account AWS di tua proprietà"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["Creazione di un ruolo per delegare le autorizzazioni a un utente IAM"]



== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
