---
sidebar: sidebar 
permalink: task_dc_na_amazon_fsx.html 
keywords: 'data collector, stout, fsx, fsx-netapp, Amazon, AWS, cluster, volume, share, LUN"' 
summary: Amazon FSX per NetApp ONTAP Data Collector 
---
= Amazon FSX per NetApp ONTAP data collector
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Questo data collector acquisisce i dati di inventario e performance da Amazon FSX per NetApp ONTAP. Questo data collector sarà reso disponibile in modo incrementale in tutte le aree del servizio Data Infrastructure Insights. Se non viene visualizzata l'icona di questo raccoglitore nell'ambiente Data Infrastructure Insights, contattare il rappresentante delle vendite.


NOTE: Questo raccoglitore di informazioni sull'infrastruttura dati richiede un utente ONTAP con un ruolo _filesystem-scoped_. Consulta la link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/roles-and-users.html["Ruoli e regole"]documentazione di AWS per scoprire le opzioni disponibili. Attualmente AWS supporta solo un tipo di ruolo utente con ambito filesystem, che è _fsxadmin_. Questo è il ruolo appropriato da utilizzare per il collettore di informazioni sull'infrastruttura dati. All'utente dovrebbero essere assegnate anche tutte e tre le seguenti applicazioni: http, ontapi, ssh.



== Terminologia

Data Infrastructure Insights acquisisce i dati di inventario e delle prestazioni dal data collector FSX-NetApp. Per ogni tipo di risorsa acquisita, viene visualizzata la terminologia più comune utilizzata per la risorsa. Durante la visualizzazione o la risoluzione dei problemi di questo data collector, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Vendor/modello | Termine di approfondimento sull'infrastruttura dati 


| Cluster | Storage 


| LUN | Volume 


| Volume | Volume interno 
|===


== Terminologia FSX-NetApp

I seguenti termini si applicano agli oggetti o ai riferimenti presenti nelle landing page delle risorse di storage FSX-NetApp. Molti di questi termini si applicano anche ad altri data collezionisti.



=== Storage

* Modello – un elenco delimitato da virgole dei nomi di modelli univoci e discreti all'interno di questo cluster.
* Vendor – AWS
* Serial Number (numero di serie): Il numero di serie dell'array.
* IP (IP): Generalmente corrisponde agli IP o ai nomi host configurati nell'origine dati.
* Raw Capacity (capacità raw): Somma di base 2 di tutto lo storage SSD assegnato al file system FSX.
* Latenza: Una rappresentazione di ciò che stanno sperimentando i carichi di lavoro dell'host, sia in lettura che in scrittura. Idealmente, Data Infrastructure Insights sta reperendo questo valore direttamente, ma spesso non è così. Al posto dell'array che lo offre, Data Infrastructure Insights sta generalmente eseguendo un calcolo ponderato in IOPS derivato dalle statistiche dei singoli volumi interni.
* Throughput: Aggregato da volumi interni. Gestione – può contenere un collegamento ipertestuale per l'interfaccia di gestione del dispositivo. Creato a livello di codice dall'origine dati Data Infrastructure Insights come parte del reporting di inventario.




=== Pool di storage

* Storage: Su quale array di storage vive questo pool. Obbligatorio.
* Type (tipo) – un valore descrittivo da un elenco di possibilità enumerate. La maggior parte dei casi sarà "aggregato" o "RAID Group".
* Capacity (capacità): I valori qui riportati sono la capacità logica utilizzata, la capacità utilizzabile e la capacità logica totale, nonché la percentuale utilizzata in tali valori.
* IOPS: La somma degli IOPS di tutti i volumi allocati in questo pool di storage.
* Throughput (throughput): La somma del throughput di tutti i volumi allocati in questo pool di storage.




== Requisiti

Di seguito sono riportati i requisiti per configurare e utilizzare questo data collector:

* È necessario avere accesso a un account con il ruolo "fsxadmin", con tre applicazioni assegnate - ssh, ontapi, http
* I dettagli dell'account includono nome utente e password.
* Requisiti di porta: 443




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| IP di gestione NetApp | Indirizzo IP o nome di dominio completo del cluster NetApp 


| Nome utente | Nome utente del cluster NetApp 


| Password | Password per il cluster NetApp 
|===


== Metriche avanzate

Questo data collector raccoglie le seguenti metriche avanzate da FSX per lo storage NetApp ONTAP:

* fpolicy
* nfsv3
* nfsv3:nodo
* nfsv4
* nfsv4_1
* nfsv4_1:nodo
* nfsv4:nodo
* policy_group
* qtree
* volume
* workload_volume


Si noti che i comandi CLI e API di FSX recuperano alcuni valori di capacità che Data Infrastructure Insights ZAPI non raccoglie, pertanto alcuni valori di capacità (come quelli per i pool di storage) potrebbero essere diversi in Data Infrastructure Insights rispetto a FSX stesso.



== Risoluzione dei problemi

Alcune operazioni da eseguire in caso di problemi con questo data collector:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova: 


| Ricevi una risposta HTTP 401 o un codice di errore ZAPI 13003 e ZAPI restituisce "privilegi insufficienti" o "non autorizzati per questo comando" | Controllare nome utente e password e privilegi/permessi dell'utente. 


| ZAPI restituisce "il ruolo del cluster non è cluster_mgmt LIF" | L'AU deve comunicare con l'IP di gestione del cluster. Controllare l'IP e, se necessario, modificarlo 


| Il comando ZAPI non riesce dopo il tentativo | Au ha problemi di comunicazione con il cluster. Controllare la rete, il numero di porta e l'indirizzo IP. L'utente dovrebbe anche provare ad eseguire un comando dalla riga di comando dalla macchina AU. 


| L'AU non è riuscito a connettersi a ZAPI tramite HTTP | Controllare se la porta ZAPI accetta testo non crittografato. Se AU tenta di inviare testo non crittografato a un socket SSL, la comunicazione non riesce. 


| Comunicazione non riuscita con SSLException | AU sta tentando di inviare SSL a una porta di testo normale su un filer. Controllare se la porta ZAPI accetta SSL o utilizza una porta diversa. 


| Ulteriori errori di connessione: La risposta ZAPI ha il codice di errore 13001, il codice di errore "database non aperto" ZAPI è 60 e la risposta contiene "API non è stata completata in tempo" la risposta ZAPI contiene "initialize_session() ha restituito l'ambiente NULL" il codice di errore ZAPI è 14007 e la risposta contiene "nodo non è integro" | Controllare la rete, il numero di porta e l'indirizzo IP. L'utente dovrebbe anche provare ad eseguire un comando dalla riga di comando dalla macchina AU. 
|===
Ulteriori informazioni sono disponibili nella link:concept_requesting_support.html["Supporto"]pagina o nella link:reference_data_collector_support_matrix.html["Matrice di supporto Data Collector"].
