---
sidebar: sidebar 
permalink: task_modify_delete_query.html 
summary: Modifica o eliminazione di una query 
keywords: query, queries, modify, edit, delete, remove 
---
= Modifica o eliminazione di una query
:hardbreaks:
:allow-uri-read: 


[role="lead"]
È possibile modificare i criteri associati a una query quando si desidera modificare i criteri di ricerca per le risorse su cui si sta eseguendo la query.



== Modifica di una query

.Passi
. Fare clic su *Esplora* e selezionare *Tutte le query metriche*.
+
Viene visualizzata la pagina Query.

. Fare clic sul nome della query
. Per aggiungere un criterio alla query, fare clic sull'icona Colonne e selezionare una metrica o un attributo dall'elenco.


Dopo aver apportato tutte le modifiche necessarie, procedere in uno dei seguenti modi:

* Fare clic sul pulsante *Salva* per salvare la query con il nome utilizzato inizialmente.
* Fare clic sul menu a discesa accanto al pulsante *Salva* e selezionare *Salva con nome* per salvare la query con un altro nome.  Ciò non sovrascrive la query originale.
* Fare clic sul menu a discesa accanto al pulsante *Salva* e selezionare *Rinomina* per modificare il nome della query utilizzato inizialmente.  Ciò sovrascrive la query originale.
* Fare clic sul menu a discesa accanto al pulsante *Salva* e selezionare *Ignora modifiche* per ripristinare la query alle ultime modifiche salvate.




== Eliminazione di una query

Per eliminare una query, fare clic su *Query* e selezionare *Mostra tutte le query*, quindi eseguire una delle seguenti operazioni:

. Fare clic sul menu "tre punti" a destra della query e fare clic su *Elimina*.
. Fare clic sul nome della query e selezionare *Elimina* dal menu a discesa *Salva*.

