---
sidebar: sidebar 
permalink: task_dc_redhat_openshift_virtualization.html 
keywords: data collector, Red Hat OpenShift Virtualization 
summary: Configurazione del raccoglitore dati di Red Hat OpenShift Virtualization. 
---
= Red Hat OpenShift Virtualization raccoglitore dati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il collector DII Red Hat OpenShift Virtualization tenterà di rilevare i carichi di lavoro di elaborazione OSV in esecuzione su un ambiente OpenShift Virtualization - questo collector non rileverà tutti i pod OpenShift. Si tratta di un collector basato su API REST HTTPS. Si consiglia di creare un collector per cluster OSV.

L'approccio di autenticazione per questo collector è un token di autenticazione associato a un account di servizio. Per creare sia l'account utente che il token:

....
oc create sa acq-readonly-cluster-user -n default
oc adm policy add-cluster-role-to-user cluster-reader -z acq-readonly-cluster-user --rolebinding-name acq-readonly-cluster-user-binding
oc adm policy add-cluster-role-to-user cluster-monitoring-view -z acq-readonly-cluster-user --rolebinding-name acq-readonly-cluster-monitor-user-binding
....
Esegui questi 3 comandi e verifica la presenza di eventuali errori.

Quando i comandi sono completati:

 oc sa new-token acq-readonly-cluster-user
Questo creerà un token associato al tuo utente.

Infine, potresti anche voler far eseguire al tuo amministratore OSV:

 oc cluster-info
Questo restituirà il nome host/indirizzo IP per la gestione. Ogni collector DII OSV deve essere indirizzato all'IP/nome host per la gestione OSV.



== Terminologia

Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per la risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Disco | Disco virtuale 


| Ospite | Ospite 


| Macchina virtuale | Macchina virtuale 


| Dominio di archiviazione | Archivio dati 


| Unità logica | LUN 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

* Indirizzo IP del server Red Hat OpenShift Virtualization sulla porta 443 tramite REST API
* Nome utente e password di sola lettura
* RHEV versione 3.0+




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP del server RHEV | Indirizzo IP del sistema di archiviazione 


| Nome utente | Nome utente con privilegi di amministratore 


| Password per l'account con privilegi di amministratore | Password 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Porta di comunicazione HTTPS | Porta utilizzata per la comunicazione HTTPS con RHOV 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 20 minuti. 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
