---
sidebar: sidebar 
permalink: task_dc_lenovo.html 
keywords: data collector,Lenovo, HX Series 
summary: Configurazione del raccoglitore dati Lenovo. 
---
= Raccoglitore dati Lenovo
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza il raccoglitore dati Lenovo per scoprire dati di inventario e prestazioni per i sistemi di storage Lenovo HX.

Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

* Indirizzo IP esterno Prism
* Nome utente e password dell'amministratore
* Porta TCP richiesta: 9440




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP esterno Prism | L'indirizzo IP dei servizi dati esterni per il cluster 


| Nome utente | Nome utente per l'account amministratore 


| Password | Password per l'account amministratore 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| porta TCP | Porta TCP utilizzata per connettersi all'array.  Il valore predefinito è 9440. 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 60 minuti. 


| Intervallo di sondaggio delle prestazioni (sec) | Intervallo tra i sondaggi sulle prestazioni. Il valore predefinito è 300 secondi. 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
