---
sidebar: sidebar 
permalink: task_config_telegraf_consul.html 
keywords: telegraf, installation, install, consul 
summary: Configurazione del raccoglitore dati del console 
---
= Consul Data Collector
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza questo strumento di raccolta dati per raccogliere metriche da Consul.



== Installazione

. Da *Osservabilità > Collettori*, fare clic su *+Collettore dati*.  Scegli Console.
+
Se non hai configurato un agente per la raccolta, ti verrà richiesto dilink:task_config_telegraf_agent.html["installare un agente"] sul tuo inquilino.

+
Se hai già configurato un agente, seleziona il sistema operativo o la piattaforma appropriati e fai clic su *Continua*.

. Seguire le istruzioni nella schermata Configurazione del Consul per configurare il raccoglitore dati.  Le istruzioni variano a seconda del tipo di sistema operativo o piattaforma utilizzata per raccogliere i dati.




== Impostare

Le informazioni possono essere trovate nellink:https://www.consul.io/docs/index.html["Documentazione del console"] .



== Oggetti e contatori per console

Vengono raccolti i seguenti oggetti e i relativi contatori:

[cols="<.<,<.<,<.<,<.<"]
|===
| Oggetto: | Identificatori: | Attributi: | Punti dati: 


| Console | Nodo del servizio ID di controllo dello spazio dei nomi | IP del nodo Sistema operativo del nodo UUID del nodo Nome del nodo Nome del servizio Controlla nome ID del servizio Stato | Avviso di sorpasso critico 
|===


== Risoluzione dei problemi

Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina.
