---
sidebar: sidebar 
permalink: task_identify_inactive_devices.html 
keywords: inactive, device, remove, removing, identify, identifying 
summary: 'L"identificazione dei dispositivi inattivi consente di scegliere se eliminarli o assegnarli a un ruolo attivo.' 
---
= Identificazione dei dispositivi inattivi
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Identificare le risorse di cui si dispone e chi le utilizza è fondamentale per "dimensionarle correttamente" e liberare infrastrutture inutilizzate.  È possibile riassegnare o dismettere facilmente le risorse sottoutilizzate ed evitare acquisti non necessari.

Per identificare le risorse inattive, attenersi alla seguente procedura.

.Passi
* Vai su *Osservabilità > Esplora -> +Nuova query metrica*.
* Selezionare _Archiviazione_ dal menu a discesa.
* Fare clic sull'ingranaggio e aggiungere _isActive_ come colonna.
+
Le righe che mostrano un segno di spunta sono attive.  "X" indica i dispositivi inattivi.



Per rimuovere i dispositivi inattivi, seleziona semplicemente i dispositivi da rimuovere e nel menu a discesa *Azioni in blocco* seleziona _Elimina dispositivi inattivi_.
