---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: Configurare il raccoglitore dati NetApp StorageGRID 
keywords: data collector, queries, create, storagegrid 
---
= Raccoglitore dati NetApp StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il raccoglitore dati NetApp StorageGRID supporta la raccolta di inventario e prestazioni dalle configurazioni StorageGRID .

[NOTE]
====
Per garantire una misurazione coerente dei diritti DII su tutti i sistemi StorageGRID , indipendentemente dalla topologia e dalla configurazione hardware sottostante, Data Infrastructure Insights utilizza la capacità totale disponibile (storagegrid_storage_utilization_total_space_bytes), anziché la capacità RAW basata sul layout del disco fisico.

Per i clienti che utilizzano il modello di licenza basato sulla capacità, StorageGRID viene misurato come storage "Oggetto".

Per i clienti che utilizzano il modello di licenza legacy (MU), StorageGRID viene misurato come storage secondario, a una velocità di 40 TiB per 1 MU.

====


== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore NetApp StorageGRID .  Per ogni tipologia di asset acquisito viene mostrata la terminologia più comune utilizzata per tale asset.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| StorageGRID | Magazzinaggio 


| Nodo | Nodo 


| Inquilino | Pool di archiviazione 


| Secchio | Volume interno 
|===


== Requisiti

Di seguito sono riportati i requisiti per la configurazione di questa origine dati:

* Indirizzo IP host StorageGRID
* Un nome utente e una password per un utente a cui sono stati assegnati i ruoli Metric Query e Tenant Access
* Porta 443 (o 8443 se configurato)




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP host StorageGRID | Indirizzo IP di gestione di StorageGRID (Grid Manager) 


| Nome utente | Nome utilizzato per accedere a StorageGRID (Grid Manager) 


| Password | Password utilizzata per accedere a StorageGRID (Grid Manager) 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 60 minuti 


| Intervallo di sondaggio delle prestazioni (sec) | Il valore predefinito è 900 secondi 
|===


== Accesso singolo (SSO)

ILlink:https://docs.netapp.com/sgws-112/index.jsp["StorageGRID"] Le versioni del firmware hanno le corrispondenti versioni API; l'API 3.0 e le versioni più recenti supportano l'accesso Single Sign-On (SSO).

|===


| Versione del firmware | Versione API | Supporta l'accesso singolo (SSO) 


| 11,1 | 2 | NO 


| 11,2 | 3,0 | SÌ 


| 11,5 | 3,3 | SÌ 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
