---
sidebar: sidebar 
permalink: task_cs_add_collector_ontap.html 
keywords: data collector, ONTAP, SVM 
summary: Aggiunta di collettori di dati 
---
= Configurazione del raccoglitore dati NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Workload Security utilizza i collettori di dati per raccogliere dati sui file e sugli accessi degli utenti dai dispositivi.  I dati vengono forniti a Workload Security per l'analisi.

.Prima di iniziare
Per configurare questo raccoglitore dati sono necessarie le seguenti informazioni:

* Un agente deve essere configurato per raccogliere dati
* L'indirizzo IP di gestione SVM
* Un nome utente per accedere all'SVM
* La password per accedere all'SVM


.Passaggi per la configurazione
. Accedi come amministratore o proprietario dell'account al tuo ambiente Workload Security.
. Fare clic su *Osservabilità > Collettori > +Collettori dati*
+
Il sistema visualizza i Data Collector disponibili.

. Fare clic su *+Monitoraggio* nel riquadro NetApp ONTAP .
+
Il sistema visualizza la pagina di configurazione Aggiungi Data Collector: Ontap SVM.

. Inserisci un nome univoco per il collezionista
. Seleziona l'agente che raccoglierà i dati
. Immettere l'indirizzo IP di gestione SVM
. Inserisci il nome utente per accedere all'SVM
. Inserisci la password per accedere all'SVM
. Fai clic su *+Aggiungi collezionista*


.Dopo aver finito
* Fare clic su *Sicurezza del carico di lavoro > Collettori* per verificare lo stato del collettore configurato.
+
Solitamente c'è un ritardo prima che venga visualizzato lo stato del collettore.


