---
sidebar: sidebar 
permalink: task_dc_emc_xio.html 
keywords: data collector, XtremeIO, EMC 
summary: Configurazione del raccoglitore dati XtremeIO. 
---
= Raccoglitore dati Dell EMC XtremeIO
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il raccoglitore dati EMC XtremIO acquisisce dati di inventario e prestazioni dal sistema di storage EMC XtremIO.



== Requisiti

Per configurare il raccoglitore dati EMC XtremIO (HTTP), è necessario disporre di:

* Indirizzo host del server di gestione XtremIO (XMS)
* Un account con privilegi di amministratore
* Accesso alla porta 443 (HTTPS)




== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati EMC XtremIO.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema relativo a questa origine dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Disco (SSD) | Disco 


| Grappolo | Magazzinaggio 


| Controllore | Nodo di archiviazione 


| Volume | Volume 


| Mappa LUN | Mappa del volume 


| Iniziatore FC target | Maschera del volume 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questa fonte dati.



== Requisiti

* Indirizzo IP dell'host del server di gestione XtremIO (XMS)
* Nome utente e password dell'amministratore per XtremIO




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Host XMS | Indirizzo IP o nome di dominio completo del server di gestione XtremIO 


| Nome utente | Nome utente per XtremIO Management Server 


| Password | Password per il server di gestione XtremIO 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| porta TCP | Porta TCP utilizzata per connettersi al server di gestione XTremIO.  Il valore predefinito è 443. 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 60 minuti. 


| Intervallo di sondaggio delle prestazioni (sec) | Intervallo tra i sondaggi sulle prestazioni. Il valore predefinito è 300 secondi. 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
