---
sidebar: sidebar 
permalink: task_create_annotation_rules.html 
summary: È possibile creare regole di annotazione per applicare automaticamente annotazioni a più risorse. 
keywords: annotate, annotation, rules 
---
= Creazione di regole di annotazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare le regole di annotazione per applicare automaticamente annotazioni a più risorse in base ai criteri definiti.  Data Infrastructure Insights assegna le annotazioni alle risorse in base a queste regole.  Le annotazioni impostate manualmente sulle singole pagine delle risorse hanno la precedenza sulle annotazioni basate su regole quando Cloud Insight valuta le regole di annotazione.

.Prima di iniziare
Devi aver creato una query per la regola di annotazione.

.Passi
. Nel menu Data Infrastructure Insights fare clic su *Gestisci > Regole di annotazione*.
. Fare clic su *+ Regola* per aggiungere una nuova regola di annotazione.
+
Viene visualizzata la finestra di dialogo Aggiungi regola.

. Procedi come segue:
+
.. Nella casella *Nome*, immettere un nome univoco che descriva la regola.
+
Il nome appare nella pagina Regole di annotazione.

.. Fare clic su *Query* e selezionare la query che Data Infrastructure Insights utilizza per identificare le risorse a cui si applica l'annotazione.
.. Fare clic su *Annotazione* e selezionare l'annotazione che si desidera applicare.
.. Fare clic su *Valore* e selezionare un valore per l'annotazione.
+
Ad esempio, se si sceglie Compleanno come annotazione, si specifica una data per il valore.

.. Fai clic su *Salva*
.. Fare clic su *Esegui tutte le regole* se si desidera eseguire tutte le regole immediatamente; in caso contrario, le regole vengono eseguite a intervalli regolari pianificati.
+

NOTE: In un ambiente Data Infrastructure Insights di grandi dimensioni, potresti notare che l'esecuzione delle regole di annotazione sembra richiedere un po' di tempo per essere completata.  Ciò avviene perché l'indicizzatore viene eseguito per primo e deve essere completato prima di eseguire le regole.  L'indicizzatore è ciò che consente a Data Infrastructure Insights di cercare o filtrare oggetti e contatori nuovi o aggiornati nei dati.  Il motore delle regole attende che l'indicizzatore completi l'aggiornamento prima di applicare le regole.







== Modifica delle regole di annotazione

È possibile modificare una regola di annotazione per cambiare il nome della regola, la sua annotazione, il valore dell'annotazione o la query associata alla regola.

.Passi
. Nel menu Data Infrastructure Insights , fare clic su *Gestisci > Regole di annotazione*.
+
La pagina Regole di annotazione visualizza l'elenco delle regole di annotazione esistenti.

. Individua la regola di annotazione che desideri modificare.
+
È possibile filtrare le regole di annotazione inserendo un valore nella casella del filtro oppure facendo clic su un numero di pagina per sfogliare le regole di annotazione per pagina.

. Fare clic sull'icona del menu relativa alla regola che si desidera modificare.
. Fai clic su *Modifica*
+
Viene visualizzata la finestra di dialogo Modifica regola.

. Modificare il nome, l'annotazione, il valore o la query della regola di annotazione.




== Cambiare l'ordine delle regole

Le regole di annotazione vengono elaborate dall'alto verso il basso nell'elenco delle regole.  Per modificare l'ordine in cui viene elaborata una regola, procedere come segue:

.Passi
. Fare clic sull'icona del menu relativa alla regola che si desidera spostare.
. Fare clic su *Sposta su* o *Sposta giù*, a seconda delle necessità, finché la regola non viene visualizzata nella posizione desiderata.


Tieni presente che quando si eseguono più regole che aggiornano la stessa annotazione su una risorsa, la prima regola (eseguita dall'alto verso il basso) applica l'annotazione e aggiorna la risorsa, quindi si applica la seconda regola ma non modifica alcuna annotazione già impostata dalla regola precedente.



== Eliminazione delle regole di annotazione

Potresti voler eliminare le regole di annotazione che non vengono più utilizzate.

.Passi
. Nel menu Data Infrastructure Insights , fare clic su *Gestisci > Regole di annotazione*.
+
La pagina Regole di annotazione visualizza l'elenco delle regole di annotazione esistenti.

. Individua la regola di annotazione che desideri eliminare.
+
È possibile filtrare le regole di annotazione inserendo un valore nella casella del filtro oppure facendo clic su un numero di pagina per sfogliare le regole di annotazione per pagina.

. Fare clic sull'icona del menu relativa alla regola che si desidera eliminare.
. Fai clic su *Elimina*
+
Viene visualizzato un messaggio di conferma che chiede se si desidera eliminare la regola.

. Fare clic su *OK*

