---
sidebar: sidebar 
permalink: task_dc_cohesity_smartfiles.html 
keywords: data collector, cohesity 
summary: Configurazione del raccoglitore dati Cohesity SmartFiles. 
---
= Raccoglitore dati Cohesity SmartFiles
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Questo collettore basato su API REST acquisirà un cluster Cohesity, scoprendo le "Visualizzazioni" (come volumi interni Data Infrastructure Insights ), i vari nodi e raccogliendo metriche sulle prestazioni.



== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| IP del cluster Cohesity | Indirizzo IP del cluster Cohesity 


| Nome utente | Nome utente per il cluster Cohesity 


| Password | Password utilizzata per il cluster Cohesity 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Porta TCP | Porta utilizzata per la comunicazione TCP con il cluster Cohesity 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 60 minuti. 


| Intervallo di sondaggio sulle prestazioni (min) | Intervallo tra i sondaggi sulle prestazioni. Il valore predefinito è 900 secondi. 
|===


== Risoluzione dei problemi

Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
