---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: Configurazione di ECS data collector. 
---
= Configurazione del data collector EMC ECS
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Questo data collector acquisisce i dati di inventario e performance dai sistemi storage EMC ECS. Per la configurazione, il data collector richiede un indirizzo IP o un nome host del cluster ECS e un nome utente e una password.


NOTE: Dell EMC ECS viene misurato a un tasso diverso da TB raw a unità gestite. Ogni 40 TB di capacità ECS non formattata viene caricata come 1 link:concept_subscribing_to_cloud_insights.html#pricing["Unità gestita (MU)"].



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal data collector ECS. Per ogni tipo di risorsa acquisita, viene visualizzata la terminologia più comune utilizzata per questa risorsa. Durante la visualizzazione o la risoluzione dei problemi di questo data collector, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Vendor/modello | Termine di approfondimento sull'infrastruttura dati 


| Cluster | Storage 


| Tenant | Pool di storage 


| Bucket | Volume interno 


| Disco | Disco 
|===
Nota: Si tratta solo di mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo data collector.



== Requisiti

* Un indirizzo IP o un nome host del cluster ECS
* Un nome utente e una password per il sistema ECS
* Porta 4443 (HTTPS). Richiede la connettività in uscita alla porta TCP 4443 sul sistema ECS.




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Host ECS | Indirizzo IP o nome di dominio completo del sistema ECS 


| Porta host ECS | Porta utilizzata per la comunicazione con l'host ECS 


| ID utente ECS | ID utente per ECS 


| Password | Password utilizzata per ECS 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo polling inventario (min) | L'impostazione predefinita è 360 minuti. 
|===


== Risoluzione dei problemi

Alcune operazioni da eseguire in caso di problemi con questo data collector:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova: 


| Errore: Autenticazione dell'utente non riuscita. | Assicurarsi che le credenziali per questa periferica siano corrette. 
|===


=== Performance

[cols="2*"]
|===
| Problema: | Prova: 


| Errore: Dati non raccolti a sufficienza. | * Controllare il timestamp della raccolta nel file di registro e modificare di conseguenza l'intervallo di polling * Attendere un tempo più lungo 


| Errore: L'intervallo di polling delle prestazioni è troppo grande. | Controllare la data e l'ora di raccolta nel file di registro{logfile} e modificare di conseguenza l'intervallo di polling 
|===
Ulteriori informazioni sono disponibili nella link:concept_requesting_support.html["Supporto"]pagina o nella link:reference_data_collector_support_matrix.html["Matrice di supporto Data Collector"].
