---
sidebar: sidebar 
permalink: task_dc_hds_hcp.html 
keywords: data collector, Hitachi HDS, HCP 
summary: Configurazione del raccoglitore dati HDS. 
---
= Raccoglitore dati Hitachi HCP
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Questo raccoglitore di dati supporta Hitachi Content Platform (HCP) tramite l'API di gestione HCP.


NOTE: Hitachi Content Platform è misurata in base a una tariffa diversa per Raw TB e Managed Unit.  Ogni 40 TB di capacità HCP non formattata viene addebitato come 1link:concept_subscribing_to_cloud_insights.html#pricing["Unità gestita (MU)"] .



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati Hitachi HCP.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Cluster HCP | Magazzinaggio 


| Inquilino | Pool di archiviazione 


|  | Spazio dei nomi 


| Volume interno | Nodo 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti di inventario

Per raccogliere i dati di inventario è necessario disporre di quanto segue:

* Indirizzo IP del server HCP
* Nome utente e password di sola lettura per il software HCP e privilegi peer




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| HCP Host | Indirizzo IP o nome di dominio completo dell'host HCP 


| Porta HCP | Il valore predefinito è 9090 


| ID utente HCP | Nome utente per l'host HCP. 


| Password HCP | Password utilizzata per l'host HCP. 


| Tipo di autenticazione HCP | Scegli HCP_LOCAL o ACTIVE_DIRECTORY 
|===


== Configurazione avanzata

|===


| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario.  Il valore predefinito è 60. 


| Intervallo di sondaggio sulle prestazioni (sec) | Intervallo tra i sondaggi sulle prestazioni.  Il valore predefinito è 900. 
|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
