---
sidebar: sidebar 
permalink: task_config_telegraf_kubernetes.html 
keywords: telegraf 
summary: Raccoglitore di dati per Kubernetes 
---
= Raccolta dati: Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights utilizza questo raccoglitore di dati per raccogliere le metriche di Kubernetes Pod, Node e Container.



== Installazione

Per le istruzioni di installazione di Kubernetes, consultarelink:task_config_telegraf_agent_k8s.html["Operatore di monitoraggio Kubernetes"] pagina.



== Informazioni su Kube-state-metrics

Kubernetes Monitoring Operator installa automaticamente kube-state-metrics; non è richiesta alcuna interazione da parte dell'utente.



=== Contatori Kube-state-metrics

L'operatore di monitoraggio NetApp Kubernetes estrae i contatori kube-state-metrics elencati di seguito.  Maggiori dettagli su ogni contatore sono disponibili qui: https://github.com/kubernetes/kube-state-metrics/tree/main/docs#exposed-metrics[] .

. Metriche DaemonSet
. Metriche di distribuzione
. Metriche dello spazio dei nomi
. Metriche dei nodi
. Metriche del volume persistenti
. Metriche di richiesta di volume persistente
. Metriche del pod
. Metriche ReplicaSet
. Metriche di servizio
. Metriche StatefulSet
. Metriche di Horizontal Pod AutoScaler
. Metriche Cronjob
. Metriche di lavoro
. Metriche delle quote delle risorse

