---
sidebar: sidebar 
permalink: task_dc_emc_vnx_block.html 
keywords: data collector, EMC, clariion, VNX block 
summary: 'Configurazione DELLO storage a blocchi DELL EMC VNX (in precedenza CLARiiON).' 
---
= Data collector Dell EMC VNX Block Storage (navicli)
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza il data collector (precedentemente CLARiiON) di Dell EMC VNX Block Storage (NaviSec) per acquisire dati di inventario e prestazioni.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal collettore di dati dello storage a blocchi EMC VNX. Per ogni tipo di asset acquisito da Data Infrastructure Insights viene visualizzata la terminologia più comune utilizzata per questa risorsa. Durante la visualizzazione o la risoluzione dei problemi di questo data collector, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Vendor/modello | Termine di approfondimento sull'infrastruttura dati 


| Disco | Disco 


| Storage | Storage 


| Processore per lo storage | Nodo di storage 


| Questo pool, gruppo RAID | Pool di storage 


| LUN | Volume 
|===
Nota: Si tratta solo di mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questa origine dati.



== Requisiti

Per raccogliere i dati, è necessario soddisfare i seguenti requisiti:

* Un indirizzo IP di ciascun processore di storage a blocchi VNX
* Nome utente e password Navisphere di sola lettura per gli array di storage a blocchi VNX
* NaviSecCli deve essere installato sull'AU di Data Infrastructure Insights
* Convalida dell'accesso: Eseguire NaviSecCLI dall'AU di Data Infrastructure Insights a ciascun array utilizzando il nome utente e la password.
* Requisiti delle porte: 80, 443
* La versione di NaviSecCLI deve corrispondere al codice FLARE più recente sull'array
* Per le performance, è necessario attivare la registrazione delle statistiche.




== Sintassi dell'interfaccia della riga di comando di Navisphere

naviseccli.exe -h <IP address> -user <user> -password <password> -scope <scope,use 0 for global scope> -port comando <use 443 by default>



== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP dello storage a blocchi VNX | Indirizzo IP o nome di dominio completo dello storage a blocchi VNX 


| Nome utente | Nome utilizzato per accedere al dispositivo di storage a blocchi VNX. 


| Password | Password utilizzata per accedere al dispositivo di storage a blocchi VNX. 


| Percorso CLI a naviseccli.exe | Percorso completo della cartella contenente l'eseguibile _navigeccli.exe_ 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo polling inventario (min) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 40 minuti. 


| Scopo | L'ambito del client sicuro. L'impostazione predefinita è Globale. 


| Intervallo di polling delle performance (sec) | Intervallo tra i sondaggi delle performance. Il valore predefinito è 300 secondi. 
|===


== Risoluzione dei problemi

Alcune operazioni da eseguire in caso di problemi con questo data collector:



=== Inventario

[cols="2a, 2a"]
|===
| Problema: | Prova: 


 a| 
Errore:

* Agente non in esecuzione
* Impossibile trovare naviseccli
* Impossibile eseguire qualsiasi comando

 a| 
* Verificare che Navisphere CLI sia installato sull'unità di acquisizione di Cloud Insight
* Non è stata selezionata l'opzione "Use Secure client" (Usa client protetto) nella configurazione guidata di raccolta dati e non è stata installata una versione non protetta di Naviphere CLI.
* Verificare che la directory di installazione della CLI Navisphere sia corretta nella configurazione del data collector
* Verificare che l'IP dello storage a blocchi VNX sia corretto nella configurazione del data Collector:
* Dall'unità di acquisizione di Data Infrastructure Insights:
+
** Aprire un CMD.
** Modificare la directory nella directory di installazione configurata
** Provare a stabilire una connessione con il dispositivo di storage a blocchi VNX digitando "navicli -h {ip} getAgent" (sostituire il {ip} con l'IP effettivo).






 a| 
Errore: 4.29 emc235848 emc241018 getall Impossibile analizzare le informazioni alias host
 a| 
Questo è probabilmente causato da un problema DI corruzione FLARE 29 del database iniziatore host sull'array stesso. Consulta gli articoli della Knowledge base EMC: Emc235848, emc241018. È anche possibile controllare https://now.netapp.com/Knowledgebase/solutionarea.asp?id=kb58128[]



 a| 
Errore: Impossibile recuperare i Meta LUN. Errore durante l'esecuzione di java -jar navicli.jar
 a| 
* Modificare la configurazione del data collector per utilizzare il client protetto (consigliato)
* Installare navicli.jar nel percorso CLI a navicli.exe O naviseccli.exe
* Nota: navicli.jar è obsoleto a partire da EMC Navisphere versione 6,26
* navicli.jar potrebbe essere disponibile su \http://powerlink.emc.com




 a| 
Errore: I pool di storage non riportano i dischi sul Service Processor all'indirizzo IP configurato
 a| 
Configurare il data collector con entrambi gli IP del Service Processor, separati da una virgola



 a| 
Errore: Errore di mancata corrispondenza della revisione
 a| 
* Questo problema è in genere causato dall'aggiornamento del firmware sul dispositivo di storage a blocchi VNX, ma non dall'aggiornamento dell'installazione di navicli.exe. Questo potrebbe essere causato anche dalla presenza di dispositivi diversi con firmware diversi, ma solo una CLI installata (con una versione firmware diversa).
* Verificare che la periferica e l'host eseguano entrambe versioni identiche del software:
+
** Dall'unità di acquisizione di Data Infrastructure Insights, aprire una finestra a riga di comando
** Modificare la directory nella directory di installazione configurata
** Stabilire una connessione con il dispositivo CLARiiON digitando “navicli -h <ip> getagent”.
** Cercare il numero di versione sulla prima coppia di righe. Esempio: "Rev. Agente: 6.16.2 (0,1)"
** Cercare e confrontare la versione sulla prima riga. Esempio: "Navisphere CLI Revisione 6.07.00.04.07"






 a| 
Errore: Configurazione non supportata - Nessuna porta Fibre Channel
 a| 
Il dispositivo non è configurato con porte Fibre Channel. Attualmente, sono supportate solo le configurazioni FC. Verificare che questa versione/firmware sia supportata.

|===
Ulteriori informazioni sono disponibili nella link:concept_requesting_support.html["Supporto"]pagina o nella link:reference_data_collector_support_matrix.html["Matrice di supporto Data Collector"].
