---
sidebar: sidebar 
permalink: task_identify_inactive_devices.html 
keywords: inactive, device, remove, removing, identify, identifying 
summary: 'L"identificazione dei dispositivi inattivi consente di scegliere se eliminarli o assegnarli a un ruolo attivo.' 
---
= Identificazione dei dispositivi inattivi
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Identificare le risorse di cui disponi e chi le utilizza è fondamentale per il "dimensionamento corretto" e liberare l'infrastruttura inutilizzata. Puoi riallocare o decommissionare facilmente le risorse sottoutilizzate ed evitare acquisti non necessari.

Per identificare le risorse inattive, procedere come segue.

.Fasi
* Selezionare *osservabilità > Esplora -> +Nuova query metrica*.
* Selezionate _Storage_ dal menu a discesa.
* Fate clic sull'ingranaggio e aggiungete _isActive_ come colonna.
+
Le righe con un segno di spunta sono attive. "X" indica dispositivi inattivi.



Per rimuovere i dispositivi inattivi, seleziona i dispositivi da rimuovere e nel menu a discesa *azioni in blocco* seleziona _Elimina dispositivi inattivi_.
