---
sidebar: sidebar 
permalink: task_dc_na_cdot.html 
keywords: data collector, ontap, ontap, CDOT 
summary: Raccoglitore dati ONTAP 
---
= Software di gestione dati NetApp ONTAP, raccoglitore di dati
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Questo raccoglitore di dati acquisisce dati di inventario e prestazioni dai sistemi di archiviazione che eseguono ONTAP utilizzando chiamate API di sola lettura da un account ONTAP .  Questo raccoglitore di dati crea anche un record nel registro delle applicazioni del cluster per accelerare il supporto.



== Terminologia

Data Infrastructure Insights acquisisce dati di inventario e prestazioni dal raccoglitore dati ONTAP .  Per ogni tipologia di asset acquisito viene mostrata la terminologia più comune utilizzata per l'asset.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Disco | Disco 


| Gruppo di incursione | Gruppo di dischi 


| Grappolo | Magazzinaggio 


| Nodo | Nodo di archiviazione 


| Aggregato | Pool di archiviazione 


| LUN | Volume 


| Volume | Volume interno 
|===


== Terminologia di gestione dei dati ONTAP

I seguenti termini si applicano agli oggetti o ai riferimenti che potresti trovare nelle pagine di destinazione delle risorse di archiviazione ONTAP Data Management.  Molti di questi termini si applicano anche ad altri raccoglitori di dati.



=== Magazzinaggio

* Modello: elenco delimitato da virgole dei nomi univoci e discreti dei modelli di nodi all'interno di questo cluster.  Se tutti i nodi nei cluster sono dello stesso tipo di modello, verrà visualizzato un solo nome di modello.
* Fornitore: lo stesso nome del fornitore che vedresti se stessi configurando una nuova origine dati.
* Numero di serie: il numero di serie dell'array.  Nei sistemi di archiviazione con architettura cluster come ONTAP Data Management, questo numero di serie potrebbe essere meno utile dei numeri di serie dei singoli "Storage Nodes".
* IP: in genere saranno gli IP o i nomi host configurati nell'origine dati.
* Versione del microcodice – firmware.
* Capacità grezza: somma di base 2 di tutti i dischi fisici nel sistema, indipendentemente dal loro ruolo.
* Latenza: rappresentazione di ciò che sta sperimentando l'host sottoposto a carichi di lavoro, sia in lettura che in scrittura.  Idealmente, Data Infrastructure Insights reperirebbe questo valore direttamente, ma spesso non è così.  Invece dell'array che offre questa funzionalità, Data Infrastructure Insights esegue in genere un calcolo ponderato in base agli IOPS derivato dalle statistiche dei singoli volumi interni.
* Capacità di elaborazione: aggregata dai volumi interni.  Gestione: può contenere un collegamento ipertestuale all'interfaccia di gestione del dispositivo.  Creato a livello di programmazione dalla fonte dati Data Infrastructure Insights come parte della reportistica di inventario.




=== Pool di archiviazione

* Archiviazione: su quale array di archiviazione risiede questo pool.  Obbligatorio.
* Tipo: un valore descrittivo da un elenco di possibilità enumerate.  Nella maggior parte dei casi sarà "Aggregato" o "Gruppo RAID".
* Nodo: se l'architettura di questo array di archiviazione è tale che i pool appartengono a un nodo di archiviazione specifico, il suo nome verrà visualizzato qui come collegamento ipertestuale alla relativa landing page.
* Utilizza Flash Pool – Valore Sì/No – questo pool basato su SATA/SAS ha SSD utilizzati per l'accelerazione della memorizzazione nella cache?
* Ridondanza: livello RAID o schema di protezione.  RAID_DP è a doppia parità, RAID_TP è a tripla parità.
* Capacità: i valori qui indicati sono la capacità logica utilizzata, la capacità utilizzabile e la capacità logica totale, nonché la percentuale utilizzata tra queste.
* Capacità sovraimpegnata: se utilizzando tecnologie di efficienza è stata assegnata una somma totale di volume o capacità di volume interno superiore alla capacità logica del pool di archiviazione, il valore percentuale sarà maggiore dello 0%.
* Snapshot: capacità di snapshot utilizzate e totali, se l'architettura del pool di archiviazione dedica parte della sua capacità ad aree di segmenti esclusivamente per gli snapshot.  È probabile che le configurazioni ONTAP in MetroCluster presentino questo fenomeno, mentre altre configurazioni ONTAP lo presentano in misura minore.
* Utilizzo: valore percentuale che indica la percentuale più alta di disco occupato tra tutti i dischi che contribuiscono alla capacità di questo pool di archiviazione.  L'utilizzo del disco non ha necessariamente una forte correlazione con le prestazioni dell'array: l'utilizzo può essere elevato a causa di ricostruzioni del disco, attività di deduplicazione, ecc. in assenza di carichi di lavoro gestiti dall'host.  Inoltre, molte implementazioni di replicazione degli array possono aumentare l'utilizzo del disco senza essere visualizzate come volume interno o carico di lavoro del volume.
* IOPS: la somma degli IOPS di tutti i dischi che contribuiscono alla capacità di questo pool di archiviazione.  Throughput: la somma del throughput di tutti i dischi che contribuiscono alla capacità di questo pool di archiviazione.




=== Nodo di archiviazione

* Archiviazione: di quale array di archiviazione fa parte questo nodo.  Obbligatorio.
* Partner HA: sulle piattaforme in cui un nodo esegue il failover su un solo altro nodo, in genere verrà visualizzato qui.
* Stato: salute del nodo.  Disponibile solo quando l'array è sufficientemente integro da poter essere inventariato da una fonte dati.
* Modello: nome del modello del nodo.
* Versione: nome della versione del dispositivo.
* Numero di serie: il numero di serie del nodo.
* Memoria: memoria base 2 se disponibile.
* Utilizzo: su ONTAP, si tratta di un indice di stress del controller derivante da un algoritmo proprietario.  A ogni sondaggio sulle prestazioni verrà segnalato un numero compreso tra 0 e 100%, che rappresenta il valore più alto tra la contesa del disco WAFL o l'utilizzo medio della CPU.  Se si osservano valori sostenuti > 50%, ciò è indicativo di sottodimensionamento, ovvero un controller/nodo non sufficientemente grande o un numero insufficiente di dischi rotanti per assorbire il carico di lavoro di scrittura.
* IOPS – Derivato direttamente dalle chiamate ONTAP ZAPI sull'oggetto nodo.
* Latenza: derivata direttamente dalle chiamate ONTAP ZAPI sull'oggetto nodo.
* Throughput: derivato direttamente dalle chiamate ONTAP ZAPI sull'oggetto nodo.
* Processori: numero di CPU.




== Requisiti

Di seguito sono riportati i requisiti per configurare e utilizzare questo raccoglitore dati:

* È necessario disporre dell'accesso a un account amministratore configurato per le chiamate API di sola lettura.
* I dettagli dell'account includono nome utente e password.
* Requisiti della porta: 80 o 443
* Autorizzazioni dell'account:
+
** Nome del ruolo di sola lettura per l'applicazione ontapi sul Vserver predefinito
** Potrebbero essere necessari permessi di scrittura facoltativi aggiuntivi.  Vedere la Nota sulle autorizzazioni qui sotto.


* Requisiti per la licenza ONTAP :
+
** Licenza FCP e volumi mappati/mascherati richiesti per la scoperta del canale in fibra






=== Requisiti di autorizzazione per la raccolta delle metriche dello switch ONTAP

Data Infrastructure Insights ha la capacità di raccogliere dati sullo switch del cluster ONTAP come opzione nel collettore<<advanced-configuration,Configurazione avanzata>> impostazioni.  Oltre ad abilitare questa funzionalità sul raccoglitore Data Infrastructure Insights , è necessario anche *configurare il sistema ONTAP * stesso per fornirelink:https://docs.netapp.com/us-en/ontap-cli-98/system-switch-ethernet-create.html["informazioni sullo switch"] e garantire la corretta<<a-note-about-permissions,permessi>> sono impostati per consentire l'invio dei dati dello switch a Data Infrastructure Insights.



== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| IP di gestione NetApp | Indirizzo IP o nome di dominio completo del cluster NetApp 


| Nome utente | Nome utente per il cluster NetApp 


| Password | Password per il cluster NetApp 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Tipo di connessione | Scegli HTTP (porta predefinita 80) o HTTPS (porta predefinita 443).  L'impostazione predefinita è HTTPS 


| Sostituisci porta di comunicazione | Specificare una porta diversa se non si desidera utilizzare quella predefinita 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 60 minuti. 


| Per TLS per HTTPS | Consenti TLS come protocollo solo quando si utilizza HTTPS 


| Ricerca automatica dei netgroup | Abilita le ricerche automatiche di netgroup per le regole dei criteri di esportazione 


| Espansione di Netgroup | Strategia di espansione di Netgroup.  Scegli _file_ o _shell_.  L'impostazione predefinita è _shell_. 


| Timeout di lettura HTTP in secondi | Il valore predefinito è 30 


| Forza le risposte come UTF-8 | Forza il codice del raccoglitore dati a interpretare le risposte dalla CLI come se fossero in UTF-8 


| Intervallo di sondaggio sulle prestazioni (sec) | Il valore predefinito è 900 secondi. 


| Raccolta dati avanzata del contatore | Abilita l'integrazione ONTAP .  Selezionare questa opzione per includere i dati del contatore avanzato ONTAP nei sondaggi.  Selezionare i contatori desiderati dall'elenco. 


| Metriche di commutazione del cluster | Consenti a Data Infrastructure Insights di raccogliere i dati dello switch del cluster.  Si noti che oltre ad abilitare questa funzionalità sul lato Data Infrastructure Insights , è necessario configurare anche il sistema ONTAP per fornirelink:https://docs.netapp.com/us-en/ontap-cli-98/system-switch-ethernet-create.html["informazioni sullo switch"] e garantire la corretta<<a-note-about-permissions,permessi>> sono impostati per consentire l'invio dei dati dello switch a Data Infrastructure Insights.  Vedere "Nota sulle autorizzazioni" di seguito. 
|===


== Metriche di potenza ONTAP

Diversi modelli ONTAP forniscono metriche di potenza per Data Infrastructure Insights che possono essere utilizzate per il monitoraggio o l'invio di avvisi.


NOTE: Questi elenchi non sono esaustivi e sono soggetti a modifiche.  In generale, se un modello appartiene alla stessa famiglia di un altro nell'elenco, il supporto dovrebbe essere lo stesso, ma non è garantito che lo sia.  Se non sei sicuro che il tuo modello supporti le metriche di potenza, contatta l'assistenza ONTAP .

Modelli supportati:

A200 A220 A250 A300 A320 A400 A700 A700s A800 A900 C190 FAS2240-4 FAS2552 FAS2650 FAS2720 FAS2750 FAS8200 FAS8300 FAS8700 FAS9000

Modelli non supportati:

FAS2620 FAS3250 FAS3270 FAS500f FAS6280 FAS/ AFF 8020 FAS/ AFF 8040 FAS/ AFF 8060 FAS/ AFF 8080



== Una nota sui permessi

Poiché numerose dashboard ONTAP di Data Infrastructure Insights si basano su contatori ONTAP avanzati, è necessario abilitare la *Raccolta dati contatore avanzata* nella sezione Configurazione avanzata del raccoglitore dati.

È inoltre necessario assicurarsi che sia abilitata l'autorizzazione di scrittura per l'API ONTAP .  In genere è necessario un account a livello di cluster con le autorizzazioni necessarie.

Per creare un account locale per Data Infrastructure Insights a livello di cluster, accedere a ONTAP con il nome utente/password dell'amministratore di gestione del cluster ed eseguire i seguenti comandi sul server ONTAP :

. Prima di iniziare, è necessario aver effettuato l'accesso a ONTAP con un account _Amministratore_ e i _comandi a livello diagnostico_ devono essere abilitati.
. Creare un ruolo di sola lettura utilizzando i seguenti comandi.
+
....
security login role create -role ci_readonly -cmddirname DEFAULT -access readonly
security login role create -role ci_readonly -cmddirname security -access readonly
security login role create -role ci_readonly -access all -cmddirname {cluster application-record create}
....
. Creare l'utente di sola lettura utilizzando il seguente comando.  Dopo aver eseguito il comando create, ti verrà chiesto di immettere una password per questo utente.
+
 security login create -username ci_user -application ontapi -authentication-method password -role ci_readonly


Se viene utilizzato un account AD/LDAP, il comando deve essere

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application ontapi -authentication-method domain -role ci_readonly
Se si raccolgono dati sullo switch del cluster:

....
security login rest-role create -role ci_readonly_rest -api /api/network/ethernet -access readonly
security login create -user-or-group-name ci_user -application http -authmethod password -role ci_readonly_rest
....
Il ruolo risultante e l'accesso utente saranno simili ai seguenti.  Il risultato effettivo potrebbe variare:

....
Role Command/ Access
Vserver Name Directory Query Level
---------- ------------- --------- ------------------ --------
cluster1 ci_readonly DEFAULT read only
cluster1 ci_readonly security readonly
....
....
cluster1:security login> show
Vserver: cluster1
Authentication Acct
UserName    Application   Method      Role Name      Locked
---------   -------      ----------- -------------- --------
ci_user     ontapi      password    ci_readonly   no
....

NOTE: Se il controllo di accesso ONTAP non è impostato correttamente, le chiamate REST Data Infrastructure Insights potrebbero non riuscire, causando lacune nei dati per il dispositivo.  Ad esempio, se è stato abilitato sul raccoglitore Data Infrastructure Insights ma non sono state configurate le autorizzazioni su ONTAP, l'acquisizione non andrà a buon fine.  Inoltre, se il ruolo è stato precedentemente definito ONTAP e si stanno aggiungendo le funzionalità dell'API REST, assicurarsi che _http_ sia aggiunto al ruolo.



== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova questo: 


| Ricevi la risposta HTTP 401 o il codice di errore ZAPI 13003 e ZAPI restituisce "Privilegi insufficienti" o "non autorizzato per questo comando" | Controllare nome utente, password e privilegi/permessi dell'utente. 


| La versione del cluster è < 8.1 | La versione minima supportata dal cluster è 8.1.  Aggiorna alla versione minima supportata. 


| ZAPI restituisce "il ruolo del cluster non è cluster_mgmt LIF" | L'AU deve comunicare con l'IP di gestione del cluster.  Controllare l'IP e, se necessario, cambiarlo con un IP diverso 


| Errore: "I filtri in modalità 7 non sono supportati" | Ciò può accadere se si utilizza questo raccoglitore di dati per scoprire il filtro in modalità 7.  Cambiare l'IP in modo che punti al cluster cdot. 


| Il comando ZAPI fallisce dopo il nuovo tentativo | L'AU ha problemi di comunicazione con il cluster.  Controllare la rete, il numero di porta e l'indirizzo IP.  L'utente dovrebbe anche provare a eseguire un comando dalla riga di comando della macchina AU. 


| AU non è riuscito a connettersi a ZAPI tramite HTTP | Verificare se la porta ZAPI accetta testo in chiaro.  Se AU tenta di inviare testo in chiaro a un socket SSL, la comunicazione fallisce. 


| La comunicazione fallisce con SSLException | AU sta tentando di inviare SSL a una porta in chiaro su un filer.  Verificare se la porta ZAPI accetta SSL oppure utilizzare una porta diversa. 


| Errori di connessione aggiuntivi: la risposta ZAPI ha il codice di errore 13001, "database non aperto". Il codice di errore ZAPI è 60 e la risposta contiene "API non completata in tempo". La risposta ZAPI contiene "initialize_session() ha restituito ambiente NULL". Il codice di errore ZAPI è 14007 e la risposta contiene "Nodo non funzionante". | Controllare la rete, il numero di porta e l'indirizzo IP.  L'utente dovrebbe anche provare a eseguire un comando dalla riga di comando della macchina AU. 
|===


=== Prestazione

[cols="2*"]
|===
| Problema: | Prova questo: 


| Errore "Impossibile raccogliere le prestazioni da ZAPI" | Di solito ciò è dovuto al fatto che la statistica delle prestazioni non è in esecuzione.  Prova il seguente comando su ciascun nodo: > _system node systemshell -node * -command “spmctl -h cmd –stop; spmctl -h cmd –exec”_ 
|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
