---
sidebar: sidebar 
permalink: task_dc_emc_unity.html 
keywords: data collector, VNXe, EMC, Unity 
summary: Configurazione del raccoglitore dati VNXe. 
---
= Configurazione del raccoglitore dati EMC Unity
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il raccoglitore dati DELL EMC Unity (in precedenza VNXe) fornisce supporto di inventario per gli array di storage unificati VNXe.  Data Infrastructure Insights supporta attualmente i protocolli iSCSI e NAS.



== Requisiti

* Il data collector Unity è basato sulla CLI; è necessario installare Unisphere per Unity CLI (uemcli.exe) sull'unità di acquisizione in cui risiede il data collector VNXe.
* uemcli.exe utilizza HTTPS come protocollo di trasporto, pertanto l'unità di acquisizione dovrà essere in grado di avviare connessioni HTTPS a Unity.
* Indirizzo IP o nome di dominio completo del dispositivo Unity
* Per l'utilizzo da parte del raccoglitore dati è necessario disporre almeno di un utente con privilegi di sola lettura.
* È richiesto HTTPS sulla porta 443
* Il data collector EMC Unity fornisce supporto NAS e iSCSI per l'inventario; i volumi Fibre Channel verranno rilevati, ma Data Infrastructure Insights non fornisce report sulla mappatura FC, sul mascheramento o sulle porte di archiviazione.




== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati Unity.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Disco | Disco 


| Array di archiviazione | Magazzinaggio 


| Processore | Nodo di archiviazione 


| Pool di archiviazione | Pool di archiviazione 


| Informazioni generali sul blocco iSCSI, VMware VMFS | Condividere 


| Sistema remoto di replicazione | Sincronizzazione 


| Nodo iSCSI | Nodo di destinazione iSCSI 


| Iniziatore iSCSI | Iniziatore di destinazione iSCSI 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questa fonte dati.



== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Unity Storage | Indirizzo IP o nome di dominio completo del dispositivo Unity 


| Nome utente | Nome utente per il dispositivo Unity 


| Password | Password per il dispositivo Unity 


| Percorso completo dell'eseguibile UEMCLI | Percorso completo della cartella contenente l'eseguibile _uemcli.exe_ 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario.  Il valore predefinito è 40 minuti 


| Porta CLI Unity | Porta utilizzata per Unity CLI 


| Intervallo di sondaggio delle prestazioni (sec) | Il valore predefinito è 300. 
|===


== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova questo: 


| "Impossibile eseguire l'utilità esterna" con messaggi di errore "Impossibile trovare l'eseguibile Unisphere uemcli" | * Verificare la correttezza dell'indirizzo IP, del nome utente e della password. * Confermare che Unisphere CLI sia installato sull'unità di acquisizione Data Infrastructure Insights. * Confermare che la directory di installazione di Unisphere CLI sia corretta nella configurazione dell'origine dati. * Confermare che l'IP del VNXe sia corretto nella configurazione dell'origine dati.  Dall'unità di acquisizione Data Infrastructure Insights , aprire un CMD e passare alla directory di installazione configurata: ${INSTALLDIR.  Prova a stabilire una connessione con il dispositivo VNXe digitando: uemcli -d <Il tuo IP> -u <Il tuo ID> /sys/general show 
|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
