---
sidebar: sidebar 
permalink: task_dc_ms_hyperv.html 
keywords: data collector, Microsoft, Hyper-V 
summary: Configurazione del raccoglitore dati Microsoft Hyper-V. 
---
= Raccoglitore dati Microsoft Hyper-V
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il raccoglitore dati Microsoft Hyper-V acquisisce dati di inventario e prestazioni dall'ambiente di elaborazione del server virtualizzato.  Questo raccoglitore di dati può rilevare un host Hyper-V autonomo o un intero cluster: creare un raccoglitore per ogni host autonomo o cluster.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario da Microsoft Hyper-V (WMI).  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Disco rigido virtuale | Disco virtuale 


| Ospite | Ospite 


| Macchina virtuale | Macchina virtuale 


| Cluster Shared Volumes (CSV), Volume di partizione | Archivio dati 


| Dispositivo SCSI Internet, LUN SCSI multipercorso | LUN 


| Porta Fibre Channel | Porta 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

Per configurare questo raccoglitore dati sono necessari i seguenti elementi:

* Hyper-V richiede l'apertura della porta 5985 per la raccolta dati e l'accesso/gestione remota.
* Indirizzo IP o FQDN del cluster o dell'hypervisor autonomo.  Utilizzare il nome host o l'IP del cluster mobile è probabilmente l'approccio più affidabile rispetto all'indirizzare il collettore a un solo nodo specifico in un cluster.
* Account utente di livello amministrativo che funziona su tutti gli hypervisor del cluster.
* WinRM deve essere abilitato e in ascolto su tutti gli hypervisor
* Requisiti delle porte: porta 135 tramite WMI e porte TCP dinamiche assegnate 1024-65535 per Windows 2003 e versioni precedenti e 49152-65535 per Windows 2008.
* La risoluzione DNS deve riuscire, anche se il raccoglitore dati è puntato solo a un indirizzo IP
* Ogni hypervisor Hyper-V deve avere la funzione "Resource Metering" attivata per ogni VM, su ogni host.  Ciò consente a ciascun hypervisor di avere a disposizione più dati per Data Infrastructure Insights su ciascun guest.  Se questa opzione non viene impostata, per ogni ospite vengono acquisite meno metriche sulle prestazioni.  Ulteriori informazioni sulla misurazione delle risorse sono disponibili nella documentazione Microsoft:
+
link:https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831661(v=ws.11)["Panoramica sulla misurazione delle risorse di Hyper-V"]

+
link:https://docs.microsoft.com/en-us/powershell/module/hyper-v/enable-vmresourcemetering?view=win10-ps["Abilita-VMResourceMetering"]




NOTE: Il raccoglitore dati Hyper-V richiede una Windows Acquisition Unit.



== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP del cluster o FQDN del cluster mobile | L'indirizzo IP o il nome di dominio completo per il cluster o un hypervisor autonomo e non in cluster 


| Nome utente | Nome utente amministratore per l'hypervisor 


| Password | Password per l'hypervisor 


| Suffisso di dominio DNS | Il suffisso del nome host che si combina con il nome host semplice per rendere l'FQDN di un hypervisor 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 20 minuti. 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
