---
sidebar: sidebar 
permalink: task_research_failed_collector.html 
keywords: data collector, changes, failures 
summary: Errori del raccoglitore dati 
---
= Ricerca di un raccoglitore di dati fallito
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Se un raccoglitore dati presenta un messaggio di errore e un impatto elevato o medio, è necessario analizzare il problema utilizzando la pagina di riepilogo del raccoglitore dati con le relative informazioni collegate.

Per determinare la causa del mancato funzionamento dei raccoglitori dati, attenersi alla seguente procedura.  I messaggi di errore del Data Collector vengono visualizzati nel menu *Amministrazione* e nella pagina *Data Collector installati*.

.Passi
. Fare clic su *Amministrazione* > *Raccolta dati* > *Raccolta dati installati*.
. Fare clic sul nome collegato del raccoglitore dati non riuscito per aprire la pagina Riepilogo.
. Nella pagina Riepilogo, controlla l'area Commenti per leggere eventuali note lasciate da un altro tecnico che potrebbe stare indagando su questo guasto.
. Annotare eventuali messaggi sulle prestazioni.
. Sposta il puntatore del mouse sui segmenti del grafico della cronologia degli eventi per visualizzare informazioni aggiuntive.
. Selezionare un messaggio di errore per un dispositivo visualizzato sotto la cronologia degli eventi e fare clic sull'icona Dettagli errore visualizzata a destra del messaggio.
+
I dettagli dell'errore includono il testo del messaggio di errore, le cause più probabili, le informazioni in uso e i suggerimenti su cosa si può fare per correggere il problema.

. Nell'area Dispositivi segnalati da questo raccoglitore dati, è possibile filtrare l'elenco per visualizzare solo i dispositivi di interesse e fare clic sul *Nome* collegato di un dispositivo per visualizzare la pagina delle risorse per quel dispositivo.
. Quando torni alla pagina di riepilogo del raccoglitore dati, controlla l'area *Mostra modifiche recenti* in fondo alla pagina per verificare se le modifiche recenti potrebbero aver causato il problema.

