---
sidebar: sidebar 
permalink: task_cs_delete_agent.html 
keywords: agent, Workload Security, delete agent, Cloud Secure 
summary: Eliminazione degli agenti di sicurezza del carico di lavoro 
---
= Eliminazione di un agente di sicurezza del carico di lavoro
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Quando si elimina un Workload Security Agent, è necessario eliminare prima tutti i raccoglitori di dati associati all'agente.



== Eliminazione di un agente


IMPORTANT: L'eliminazione di un agente comporta l'eliminazione di tutti i Data Collector associati all'agente.  Se si prevede di configurare i raccoglitori dati con un agente diverso, è necessario creare un backup delle configurazioni del raccoglitore dati prima di eliminare l'agente.

.Prima di iniziare
. Assicurarsi che tutti i raccoglitori di dati associati all'agente vengano eliminati dal portale Workload Security.
+
Nota: ignorare questo passaggio se tutti i collettori associati sono nello stato STOPPED.



.Passaggi per eliminare un agente:
. Accedi tramite SSH alla VM dell'agente ed esegui il seguente comando.  Quando richiesto, immettere "y" per continuare.
+
....
sudo /opt/netapp/cloudsecure/agent/install/cloudsecure-agent-uninstall.sh
Uninstall CloudSecure Agent? [y|N]:
....
. Fare clic su *Sicurezza del carico di lavoro > Collettori > Agenti*
+
Il sistema visualizza l'elenco degli agenti configurati.

. Fare clic sul menu delle opzioni per l'agente che si desidera eliminare.
. Fare clic su *Elimina*.
+
Il sistema visualizza la pagina *Elimina agente*.

. Fare clic su *Elimina* per confermare l'eliminazione.

