---
sidebar: sidebar 
permalink: task_query_copy_table_values.html 
summary: È possibile copiare i valori da una tabella negli appunti per utilizzarli in altre applicazioni. 
keywords: query, queries, copy, values, clipboard 
---
= Copia dei valori della tabella
:hardbreaks:
:allow-uri-read: 


[role="lead"]
È possibile copiare i valori delle tabelle negli appunti per utilizzarli nelle caselle di ricerca o in altre applicazioni.

.Informazioni su questo compito
Esistono due metodi per copiare i valori dalle tabelle o i risultati delle query negli appunti.

.Passi
. Metodo 1: evidenziare il testo desiderato con il mouse, copiarlo e incollarlo nei campi di ricerca o in altre applicazioni.
. Metodo 2: per i campi a valore singolo, passa il mouse sopra il campo e fai clic sull'icona degli appunti che appare.  Il valore viene copiato negli appunti per essere utilizzato nei campi di ricerca o in altre applicazioni.
+
Si noti che con questo metodo è possibile copiare solo i valori che sono collegamenti ad asset.  Solo i campi che includono valori singoli (ad esempio quelli non elencati) hanno l'icona di copia.


