---
sidebar: sidebar 
permalink: task_config_cs_incloud.html 
keywords: Cloud, Storage, AWS, Cloud Volumes, Cloud ONTAP, firewall, VPC, Subnet,  cloud secure 
summary: Workload Security utilizza i collettori di dati per raccogliere dati sui file e sugli accessi degli utenti dai dispositivi. 
---
= Configurazione di Cloud Volumes ONTAP e Amazon FSx for NetApp ONTAP
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Workload Security utilizza i collettori di dati per raccogliere dati sui file e sugli accessi degli utenti dai dispositivi.



== Configurazione di archiviazione Cloud Volumes ONTAP

Consultare la documentazione di OnCommand Cloud Volumes ONTAP per configurare un'istanza AWS a nodo singolo/HA per ospitare Workload Security Agent:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html[]

Una volta completata la configurazione, segui i passaggi per impostare la tua SVM:https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html[]



== Piattaforme supportate

* Cloud Volumes ONTAP, supportato da tutti i provider di servizi cloud disponibili, ove disponibili.  Ad esempio: Amazon, Azure, Google Cloud.
* ONTAP Amazon FSx




== Configurazione della macchina agente

La macchina agente deve essere configurata nelle rispettive subnet dei provider di servizi cloud.  Per ulteriori informazioni sull'accesso alla rete, consultare [Requisiti dell'agente].

Di seguito sono riportati i passaggi per l'installazione dell'agente in AWS.  Per l'installazione, è possibile seguire passaggi equivalenti, a seconda del provider di servizi cloud, in Azure o Google Cloud.

In AWS, attenersi alla seguente procedura per configurare la macchina da utilizzare come agente di sicurezza del carico di lavoro:

Per configurare la macchina da utilizzare come Workload Security Agent, attenersi alla seguente procedura:

.Passi
. Accedi alla console AWS, vai alla pagina EC2-Instances e seleziona _Avvia istanza_.
. Selezionare un'AMI RHEL o CentOS con la versione appropriata come indicato in questa pagina:https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html[]
. Selezionare la VPC e la subnet in cui risiede l'istanza Cloud ONTAP .
. Selezionare _t2.xlarge_ (4 vCPU e 16 GB di RAM) come risorse allocate.
+
.. Creare l'istanza EC2.


. Installare i pacchetti Linux richiesti utilizzando il gestore pacchetti YUM:
+
.. Installa i pacchetti Linux nativi _wget_ e _unzip_.






== Installare l'agente di sicurezza del carico di lavoro

. Accedi come amministratore o proprietario dell'account al tuo ambiente Data Infrastructure Insights .
. Passare a *Collectors* di Workload Security e fare clic sulla scheda *Agents*.
. Fare clic su *+Agente* e specificare RHEL come piattaforma di destinazione.
. Copiare il comando Installazione agente.
. Incolla il comando Agent Installation nell'istanza RHEL EC2 a cui hai effettuato l'accesso.  Questo installa l'agente Workload Security, fornendo tutti ilink:concept_cs_agent_requirements.html["Prerequisiti dell'agente"] sono soddisfatte.


Per i passaggi dettagliati, fare riferimento a questo collegamento: https://docs.netapp.com/us-en/cloudinsights/task_cs_add_agent.html#steps-to-install-agent



== Risoluzione dei problemi

Nella tabella seguente sono descritti i problemi noti e le relative soluzioni.

|===


| Problema | Risoluzione 


| Il Data Collector mostra l'errore "Sicurezza del carico di lavoro: impossibile determinare il tipo di ONTAP per il raccoglitore dati Amazon FxSN".  Il cliente non è in grado di aggiungere un nuovo raccoglitore dati Amazon FSxN in Workload Security.  La connessione al cluster FSxN sulla porta 443 dall'agente è in timeout.  Il firewall e i gruppi di sicurezza AWS hanno le regole necessarie abilitate per consentire la comunicazione.  Un agente è già distribuito e si trova anche nello stesso account AWS.  Questo stesso agente viene utilizzato per connettere e monitorare i restanti dispositivi NetApp (e tutti funzionano). | Risolvi questo problema aggiungendo il segmento di rete LIF di fsxadmin alla regola di sicurezza dell'agente.  Se non sei sicuro delle porte, consenti tutte le porte. 
|===