---
sidebar: sidebar 
permalink: task_dc_hpe_nimble.html 
keywords: data collector, HP Nimble, HP, HPE, Alletra 6000 
summary: 'Configurazione del raccoglitore dati HP Enterprise Alletra 6000 (in precedenza Nimble).' 
---
= Raccoglitore dati HPE Alletra 6000
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il raccoglitore dati HP Enterprise Alletra 6000 (in precedenza Nimble) supporta i dati di inventario e prestazioni per gli array di storage Alletra 6000.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario da questo raccoglitore.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Vettore | Magazzinaggio 


| Disco | Disco 


| Volume | Volume 


| Piscina | Pool di archiviazione 


| Iniziatore | Alias host di archiviazione 


| Controllore | Nodo di archiviazione 


| Interfaccia Fibre Channel | Controllore 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

Per raccogliere dati di inventario e configurazione dall'array di archiviazione, è necessario disporre di quanto segue:

* L'array deve essere installato e configurato e raggiungibile dal client tramite il suo nome di dominio completo (FQDN) o l'indirizzo IP di gestione dell'array.
* L'array deve eseguire NimbleOS 2.3.x o versione successiva.
* È necessario disporre di un nome utente e di una password validi per l'array con almeno il ruolo di livello "Operatore".  Il ruolo "Ospite" non ha accesso sufficiente per comprendere le configurazioni dell'iniziatore.
* La porta 5392 deve essere aperta sull'array.


Per raccogliere dati sulle prestazioni dall'array di archiviazione è necessario disporre di quanto segue:

* L'array deve eseguire NimbleOS 4.0.0 o versione successiva
* L'array deve avere volumi configurati.  L'unica API di prestazioni di NimbleOS è per i volumi e tutte le statistiche dei report di Data Infrastructure Insights derivano dalle statistiche sui volumi




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP di gestione dell'array | Nome di dominio completo (FQDN) o indirizzo IP di gestione dell'array. 


| Nome utente | Nome utente per l'array 


| Password | Password per l'array 
|===


== Configurazione avanzata

|===


| Campo | Descrizione 


| Porta | Porta utilizzata da Nimble REST API.  Il valore predefinito è 5392. 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 60 minuti. 
|===
Nota: l'intervallo di polling delle prestazioni predefinito è di 300 secondi e non può essere modificato.  Questo è l'unico intervallo supportato da HPE Alletra 6000.
