---
sidebar: sidebar 
permalink: task_dc_hds_nas.html 
keywords: data collector, HDS HNAS, HDS NAS 
summary: 'Configurazione del raccoglitore dati HDS NAS (HNAS).' 
---
= Configurazione del raccoglitore dati NAS Hitachi Vantara
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il raccoglitore dati Hitachi Vantara NAS è un raccoglitore dati di inventario e configurazione che supporta l'individuazione dei cluster NAS HDS.  Data Infrastructure Insights supporta l'individuazione di condivisioni NFS e CIFS, file system (volumi interni) e span (pool di archiviazione).



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati HNAS.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Livello | Gruppo di dischi 


| Grappolo | Magazzinaggio 


| Nodo | Nodo di archiviazione 


| Span | Pool di archiviazione 


| Unità di sistema | Backend Lun 


| Sistema di file | Volume interno 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

* Indirizzo IP del dispositivo
* Porta 22, protocollo SSH
* Nome utente e password - livello di privilegio: Supervisore
* Nota: questo raccoglitore di dati è basato su SSH, quindi l'AU che lo ospita deve essere in grado di avviare sessioni SSH su TCP 22 sull'HNAS stesso o sulla Systems Management Unit (SMU) a cui è connesso il cluster.




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Ospite HNAS | Indirizzo IP o nome di dominio completo dell'host di gestione HNAS 


| Nome utente | Nome utente per HNAS CLI 


| Password | Password utilizzata per HNAS CLI 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 30 minuti. 
|===


== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova questo: 


| "Errore di connessione" con messaggi di errore "Errore durante la configurazione del canale shell:" o "Errore durante l'apertura del canale shell" | Probabilmente causato da problemi di connettività di rete o da una configurazione errata di SSH.  Conferma la connessione con il client SSH alternativo 


| "Timeout" o "Errore nel recupero dei dati" con messaggi di errore "Comando: XXX è scaduto." | * Prova il comando con un client SSH alternativo * Aumenta il timeout 


| "Errore di connessione" o "Credenziali di accesso non valide" con messaggi di errore "Impossibile comunicare con il dispositivo:" | * Controlla l'indirizzo IP * Controlla il nome utente e la password * Conferma la connessione con un client SSH alternativo 
|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
