---
sidebar: sidebar 
permalink: task_dc_emc_scaleio.html 
keywords: data collector, scaleIO, PowerFlex EMC, DELL 
summary: Configurazione del raccoglitore dati DELL EMC ScaleIO/PowerFlex. 
---
= Raccoglitore dati DELL EMC ScaleIO / PowerFlex
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il raccoglitore dati ScaleIO/PowerFlex raccoglie informazioni di inventario dallo storage ScaleIO e PowerFlex.  Per la configurazione, questo raccoglitore dati richiede l'indirizzo del gateway ScaleIO/PowerFlex e un nome utente e una password amministratore.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati ScaleIO/PowerFlex.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Cluster MDM (Meta Data Manager) | Magazzinaggio 


| SDS (server dati ScaleIO/PowerFlex) | Nodo di archiviazione 


| Pool di archiviazione | Pool di archiviazione 


| Volume | Volume 


| Dispositivo | Disco 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

* Accesso di sola lettura all'account utente amministratore
* Requisito porta: Porta HTTPS 443




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Gateway ScaleIO/PowerFlex | Indirizzi IP o FQDN dei gateway ScaleIO/PowerFlex, separati da virgola (,) o punto e virgola (;) 


| Nome utente | Nome utente amministratore utilizzato per accedere al dispositivo ScaleIO/PowerFlex 


| Password | Password utilizzata per accedere al dispositivo ScaleIO/PowerFlex 
|===


== Configurazione avanzata

Fare clic sulla casella di controllo Inventario per abilitare la raccolta dell'inventario.

[cols="2*"]
|===
| Campo | Descrizione 


| Porta HTTPS | 443 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 60. 


| Timeout di connessione (sec) | Il valore predefinito è 60. 
|===


== Risoluzione dei problemi

Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
