---
sidebar: sidebar 
permalink: task_dc_ibm_cs.html 
keywords: data collector, IBM CS, CS Series 
summary: Configurazione del raccoglitore dati IBM CS. 
---
= Raccoglitore dati IBM CS
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza questo strumento di raccolta dati per scoprire dati di inventario e prestazioni per i sistemi di storage IBM CS.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati IBM CS.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Pool di archiviazione | Pool di archiviazione 


| Contenitore | Volume interno 


| Contenitore | Condivisione file 


| Condivisione NFS | Condividere 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



== Requisiti

* L'indirizzo IP dei servizi dati esterni per il cluster
* Nome utente e password dell'amministratore
* Porta 9440




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP esterno Prism | L'indirizzo IP dei servizi dati esterni per il cluster 


| Nome utente | Nome utente per l'account amministratore 


| Password | Password per l'account amministratore 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| porta TCP | Porta TCP utilizzata per connettersi all'array IBM CS.  Il valore predefinito è 9440. 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 60 minuti. 


| Intervallo di sondaggio delle prestazioni (sec) | Intervallo tra i sondaggi sulle prestazioni. Il valore predefinito è 300 secondi. 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
