---
sidebar: sidebar 
permalink: task_dc_huawei_oceanstor.html 
keywords: data collector, Huawei, OceanStor, Dorado 
summary: 'Configurazione del raccoglitore dati Huawei OceanStor (REST/HTTPS).' 
---
= Raccoglitore dati Huawei OceanStor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza il raccoglitore di dati Huawei OceanStor (REST/HTTPS) per scoprire l'inventario e le prestazioni per lo storage Huawei OceanStor e OceanStor Dorado.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni sull'inventario e sulle prestazioni da Huawei OceanStor.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Pool di archiviazione | Pool di archiviazione 


| Sistema di file | Volume interno 


| Controllore | Nodo di archiviazione 


| Porta FC (Mappata) | Mappa del volume 


| Iniziatore FC host (mappato) | Maschera del volume 


| Condivisione NFS/CIFS | Condividere 


| Destinazione collegamento iSCSI | Nodo di destinazione iSCSI 


| Iniziatore di collegamento iSCSI | Nodo iniziatore iSCSI 


| Disco | Disco 


| LUN | Volume 
|===


== Requisiti

Per configurare questo raccoglitore dati sono richiesti i seguenti requisiti:

* Indirizzo IP del dispositivo
* Credenziali per accedere al gestore dispositivi OceanStor
* La porta 8088 deve essere disponibile




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP host OceanStor | Indirizzo IP o nome di dominio completo di OceanStor Device Manager 


| Nome utente | Nome utilizzato per accedere a OceanStor Device Manager 


| Password | Password utilizzata per accedere a OceanStor Device Manager 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Porta TCP | Porta TCP utilizzata per connettersi a OceanStor Device Manager.  Il valore predefinito è 8088. 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 60 minuti. 


| Intervallo di sondaggio delle prestazioni (sec). | Il valore predefinito è 300 secondi. 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
