---
sidebar: sidebar 
permalink: task_dc_oracle_zfs.html 
keywords: data collector, Oracle, ZFS, storage applicance 
summary: Configurazione del raccoglitore dati Oracle ZFS. 
---
= Raccoglitore dati Oracle ZFS Storage Appliance
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilizza il raccoglitore dati Oracle ZFS Storage Appliance per raccogliere dati di inventario e prestazioni.



== Terminologia

Data Infrastructure Insights acquisisce informazioni di inventario con il raccoglitore dati Oracle ZFS.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Disco (SSD) | Disco 


| Grappolo | Magazzinaggio 


| Controllore | Nodo di archiviazione 


| LUN | Volume 


| Mappa LUN | Mappa del volume 


| Iniziatore, bersaglio | Maschera del volume 


| Condividere | Volume interno 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questa fonte dati.



== Requisiti

* Nomi host per ZFS Controller-1 e ZFS Controller-2
* Nome utente e password dell'amministratore
* Requisito porta: 215 HTTP/HTTPS




== Metriche di prestazione richieste

Gli appliance Oracle ZFS offrono agli amministratori di storage un'ampia flessibilità nell'acquisizione di statistiche sulle prestazioni.  Data Infrastructure Insights prevede che ogni controller in una coppia ad alta disponibilità sia configurato per acquisire le seguenti metriche:

* smb2.ops[condividi]
* nfs3.ops[condividi]
* nfs4.ops[condividi]
* nfs4-1.ops[condividi]


Se il controller non acquisisce uno o tutti questi dati, probabilmente Data Infrastructure Insights non avrà o segnalerà in modo insufficiente il carico di lavoro sui "Volumi interni".



== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Nome host del controller ZFS-1 | Nome host per il controller di archiviazione 1 


| Nome host del controller ZFS-2 | Nome host per il controller di archiviazione 2 


| Nome utente | Nome utente per l'account utente dell'amministratore del sistema di archiviazione 


| Password | Password per l'account utente amministratore 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Tipo di connessione | HTTPS o HTTP, visualizza anche la porta predefinita 


| Sostituisci porta di connessione | Se vuoto, utilizzare la porta predefinita nel campo Tipo di connessione, altrimenti immettere la porta di connessione da utilizzare 


| Intervallo di sondaggio dell'inventario | Il valore predefinito è 60 secondi 


| Intervallo di sondaggio sulle prestazioni (sec) | Il valore predefinito è 300. 
|===


== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:



=== Inventario

[cols="2a, 2a"]
|===
| Problema: | Prova questo: 


 a| 
"Credenziali di accesso non valide"
 a| 
convalidare l'account utente e la password di Zfs



 a| 
"Richiesta fallita con stato 404 \https://.....:215/api/access/v1"
 a| 
Il tuo array ZFS potrebbe essere troppo vecchio per supportare l'API REST.  AK 2013.1.3.0 è stata la prima versione del sistema operativo ZFS compatibile con REST API e non tutti gli appliance ZFS possono essere aggiornati a questa versione.



 a| 
"Errore di configurazione" con messaggio di errore "Il servizio REST è disabilitato"
 a| 
Verificare che il servizio REST sia abilitato su questo dispositivo.



 a| 
"Errore di configurazione" con messaggio di errore "Utente non autorizzato per il comando"
 a| 
Questo errore è probabilmente dovuto al fatto che alcuni ruoli (ad esempio, 'advanced_analytics') non sono inclusi per l'utente configurato.

L'applicazione dell'ambito Analytics all'utente con ruolo di sola lettura potrebbe eliminare l'errore. Segui questi passaggi:

. Nel sistema ZFs, dalla schermata Configurazione -> Utenti, sposta il mouse sul ruolo e fai doppio clic per consentire la modifica
. Selezionare "Analisi" dal menu a discesa Ambito.  Viene visualizzato un elenco delle possibili proprietà.
. Fare clic sulla casella di controllo più in alto per selezionare tutte e tre le proprietà.
. Fare clic sul pulsante Aggiungi sul lato destro.
. Fare clic sul pulsante Applica in alto a destra della finestra pop-up.  La finestra pop-up si chiuderà.


|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
