---
sidebar: sidebar 
permalink: task_dc_infinidat_infinibox.html 
keywords: data collector, infinidat, InfiniBox 
summary: Configurazione del raccoglitore dati Infinidat InfiniBox. 
---
= Raccoglitore dati Infinidat InfiniBox
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il raccoglitore dati Infinidat InfiniBox (HTTP) viene utilizzato per raccogliere informazioni di inventario dal sistema di archiviazione Infinidat InfiniBox.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati Infinidat InfiniBox.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Pool di archiviazione | Pool di archiviazione 


| Nodo | Controllore 


| File system | Volume interno 


| File system | Condivisione file 


| Esportazioni del file system | Condividere 
|===


== Requisiti

Di seguito sono riportati i requisiti per la configurazione di questo raccoglitore dati.

* Indirizzo IP o FQDN del nodo di gestione InfiniBox
* ID utente e password amministratore
* Porta 443 tramite API REST




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Host InfiniBox | Indirizzo IP o nome di dominio completo del nodo di gestione InfiniBox 


| Nome utente | Nome utente per il nodo di gestione InfiniBox 


| Password | Password per il nodo di gestione InfiniBox 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Porta TCP | Porta TCP utilizzata per connettersi al server InfiniBox.  Il valore predefinito è 443. 


| Intervallo di sondaggio dell'inventario | Intervallo tra i sondaggi di inventario. Il valore predefinito è 60 minuti. 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
