---
sidebar: sidebar 
permalink: task_cloud_insights_onboarding_1.html 
summary: Iscrizione a Data Infrastructure Insights e creazione del tenant. 
keywords: onboarding, new user 
---
= Onboarding Data Infrastructure Insights
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Prima di poter iniziare a lavorare con Data Infrastructure Insights, è necessario registrarsi sul portale * NetApp Console*.  Se disponi già di un accesso NetApp Console , puoi iniziare una prova gratuita di Data Infrastructure Insights con pochi rapidi passaggi.



== Creazione dell'account NetApp Console

Per iniziare a utilizzare i servizi cloud di NetApp, vai alink:https://console.netapp.com/["* NetApp Console*"^] e clicca su *Inizia*.

* Se non ti sei ancora registrato, seleziona *Registrati*
* Inserisci un indirizzo email aziendale valido e scegli una password.
* Inserisci il nome della tua azienda e il tuo nome completo.
* Accetta i termini e le condizioni e seleziona *Continua*.
* La console ti guiderà passo passo nelle fasi iniziali.




=== Cosa succede se ho già un accesso NetApp Console ?

Una volta che hai un account NetApp Console , seleziona semplicemente *Accedi* sulink:https://console.netapp.com/["* NetApp Console*"^] pagina del portale.

Inserisci il tuo indirizzo email e la password.  Verrai quindi indirizzato alla pagina delle offerte cloud di NetApp.

Vai su *Analisi e controllo > Osservabilità* per saperne di più su Data Infrastructure Insights e/o richiedere una demo.



== Inizio della prova gratuita Data Infrastructure Insights

Se è la prima volta che accedi a Data Infrastructure Insights, scopri tutto ciò che Data Infrastructure Insights ha da offrire e, quando sei _Pronto per iniziare_, fai clic su *Richiedi prova* e compila le tue informazioni.

Durante la configurazione del tenant di prova, dovrai scegliere la regione in cui ospitarlo e se preferisci che sia su AWS o Azure.

Una volta completata la creazione del tenant, utilizza le credenziali della console per accedere e iniziare la prova gratuita di 30 giorni di Data Infrastructure Insights.  Durante questa prova potrai esplorare le funzionalità offerte da Data Infrastructure Insights .

Durante la prova gratuita, puoilink:concept_subscribing_to_cloud_insights.html["inizia il tuo abbonamento"] a Data Infrastructure Insights in qualsiasi momento.  Una volta sottoscritto l'abbonamento, puoi utilizzare le funzionalità di Data Infrastructure Insights in base al tuo abbonamento attuale.



== Sign in e vai

Una volta creato il tenant, in qualsiasi momento puoi semplicemente accedere al portale NetApp Console e passare allalink:https://services.cloud.netapp.com["Servizi cloud"] pagina e seleziona *Vai a Data Infrastructure Insights*.

Puoi anche aprire un browser direttamente all'URL del tenant Data Infrastructure Insights , ad esempio:

 \https://<tenant-prefix>.c01.cloudinsights.netapp.com/
L'URL verrà inoltre incluso nell'e-mail di invito di ciascun utente per facilitarne l'accesso e l'aggiunta ai preferiti.  Se l'utente non ha ancora effettuato l'accesso alla Console, gli verrà richiesto di effettuare l'accesso.


NOTE: I nuovi utenti devono comunque registrarsi per accedere alla Console prima di poter accedere all'URL del loro tenant.

La prima volta che accedi a un nuovo tenant, verrai guidato attraverso la configurazione dilink:task_getting_started_with_cloud_insights.html["*inizia a raccogliere dati*"] .



== Disconnessione

Per uscire da Data Infrastructure Insights, fai clic sul tuo *Nome utente* e seleziona *Disconnetti*.  Verrai reindirizzato alla schermata di accesso della Console.


NOTE: La disconnessione da Data Infrastructure Insights comporta l'uscita dalla Console.  Verrai disconnesso anche dagli altri servizi NetApp Cloud che utilizzano l'accesso alla Console.



=== Timeout di inattività

Per impostazione predefinita, la console disconnetterà un utente se non vi è alcuna attività per sei ore (360 minuti).  Indipendentemente dall'attività, gli utenti verranno disconnessi dopo sette giorni.
