---
sidebar: sidebar 
permalink: task_config_telegraf_kubernetes.html 
keywords: telegraf 
summary: Raccolta di dati per Kubernetes 
---
= Data Collector: Kubernetes
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights utilizza questo data collector per raccogliere le metriche di Pod, nodo e container Kubernetes.



== Installazione

Per le istruzioni di installazione di Kubernetes, consulta la link:task_config_telegraf_agent_k8s.html["Operatore di monitoring Kubernetes"]pagina.



== A proposito di Kube-state-metrics

Il Kubernetes Monitoring Operator installa automaticamente le metriche dello stato di kube; non è necessaria alcuna interazione da parte dell'utente.



=== Contatori Kube-state-metering

L'operatore di monitoraggio Kubernetes NetApp estrae i contatori delle metriche stato-kube elencati di seguito. Ulteriori dettagli su ciascun contatore sono disponibili all'indirizzo: https://github.com/kubernetes/kube-state-metrics/tree/main/docs#exposed-metrics[].

. Metriche DemonSet
. Metriche di implementazione
. Metriche dello spazio dei nomi
. Metriche del nodo
. Metriche di volume persistenti
. Metriche di richiesta di volume persistente
. Metriche pod
. Metriche ReplicaSet
. Metriche del servizio
. Metriche StatefulSet

