---
sidebar: sidebar 
permalink: task_query_copy_table_values.html 
summary: Copia i valori delle tabelle negli appunti tramite selezione del testo o copia con un clic per un trasferimento efficiente dei dati ai campi di ricerca e alle applicazioni esterne. 
keywords: query, queries, copy, values, clipboard 
---
= Copia dei valori della tabella
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ottimizza il tuo flusso di lavoro copiando i valori delle tabelle direttamente negli appunti per usarli nelle ricerche o in applicazioni esterne. Scegli tra la selezione manuale del testo o la comoda copia con un clic per i campi a valore singolo con asset link.

.Informazioni su questo compito
Esistono due metodi per copiare i valori dalle tabelle o i risultati delle query negli appunti.

.Passi
. Metodo 1: evidenziare il testo desiderato con il mouse, copiarlo e incollarlo nei campi di ricerca o in altre applicazioni.
. Metodo 2: per i campi a valore singolo, passa il mouse sopra il campo e fai clic sull'icona degli appunti che appare.  Il valore viene copiato negli appunti per essere utilizzato nei campi di ricerca o in altre applicazioni.
+
Si noti che con questo metodo è possibile copiare solo i valori che sono collegamenti ad asset.  Solo i campi che includono valori singoli (ad esempio quelli non elencati) hanno l'icona di copia.


