---
sidebar: sidebar 
permalink: task_dc_hds_commandsuite.html 
keywords: data collector, Hitachi Vantara Command Suite, Hitachi 
summary: Configurazione del raccoglitore dati di HDS Command Suite Device Manager. 
---
= Raccoglitore dati Hitachi Vantara Command Suite
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il raccoglitore dati Hitachi Vantara Command Suite supporta il server HiCommand Device Manager.  Data Infrastructure Insights comunica con il server HiCommand Device Manager tramite l'API HiCommand standard.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati Hitachi Vantara Command Suite.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| PDEV | Disco 


| Raccolta di riviste | Gruppo di dischi 


| Array di archiviazione | Magazzinaggio 


| Controllore di porta | Nodo di archiviazione 


| Gruppo di array, pool HDS | Pool di archiviazione 


| Unità logica, LDEV | Volume 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



=== Magazzinaggio

I seguenti termini si applicano agli oggetti o ai riferimenti che potresti trovare nelle landing page delle risorse di archiviazione HDS.  Molti di questi termini si applicano anche ad altri raccoglitori di dati.

* Nome: proviene direttamente dall'attributo "nome" di HDS HiCommand Device Manager tramite la chiamata API XML GetStorageArray
* Modello: proviene direttamente dall'attributo "arrayType" di HDS HiCommand Device Manager tramite la chiamata API XML GetStorageArray
* Fornitore – HDS
* Famiglia: proviene direttamente dall'attributo "arrayFamily" di HDS HiCommand Device Manager tramite la chiamata API XML GetStorageArray
* IP: questo è l'indirizzo IP di gestione dell'array, non un elenco esaustivo di tutti gli indirizzi IP sull'array
* Capacità grezza: valore base2 che rappresenta la somma della capacità totale di tutti i dischi in questo sistema, indipendentemente dal ruolo del disco.




=== Pool di archiviazione

I seguenti termini si applicano agli oggetti o ai riferimenti che potresti trovare nelle pagine di destinazione delle risorse del pool di archiviazione HDS.  Molti di questi termini si applicano anche ad altri raccoglitori di dati.

* Tipo: Il valore qui sarà uno dei seguenti:
+
** RISERVATO – se questo pool è dedicato a scopi diversi dai volumi di dati, ad esempio journaling, snapshot
** Thin Provisioning: se si tratta di un pool HDP
** Gruppo Raid: probabilmente non li vedrai per alcuni motivi:
+
Data Infrastructure Insights adotta una posizione ferma per evitare a tutti i costi il ​​doppio conteggio della capacità.  Su HDS, in genere è necessario creare gruppi Raid da dischi, creare volumi pool su tali gruppi Raid e costruire pool (spesso HDP, ma potrebbero essere per scopi speciali) da tali volumi pool.  Se Data Infrastructure Insights segnalasse sia i gruppi Raid sottostanti così come sono, sia i pool, la somma della loro capacità grezza supererebbe di gran lunga la somma dei dischi.

+
Al contrario, il raccoglitore dati HDS Command Suite di Data Infrastructure Insights riduce arbitrariamente le dimensioni dei gruppi Raid in base alla capacità dei volumi del pool.  Ciò potrebbe comportare che Data Infrastructure Insights non segnali affatto il gruppo Raid.  Inoltre, tutti i gruppi Raid risultanti vengono contrassegnati in modo tale da non essere visibili nella WebUI Data Infrastructure Insights , ma confluiscono nel Data Warehouse (DWH) di Data Data Infrastructure Insights .  Lo scopo di queste decisioni è quello di evitare di sovraccaricare l'interfaccia utente con elementi che non interessano alla maggior parte degli utenti: se il tuo array HDS ha gruppi Raid con 50 MB liberi, probabilmente non potrai utilizzare quello spazio libero per alcun risultato significativo.



* Nodo - N/D, poiché i pool HDS non sono vincolati a nessun nodo specifico
* Ridondanza: il livello RAID del pool.  Possibili valori multipli per un pool HDP composto da più tipi RAID
* Capacità %: la percentuale utilizzata del pool per l'utilizzo dei dati, con i GB utilizzati e la dimensione totale in GB logici del pool
* Capacità sovraimpegnata: un valore derivato che indica che "la capacità logica di questo pool è sovrascritta di questa percentuale in virtù della somma dei volumi logici che superano la capacità logica del pool di questa percentuale"
* Snapshot: mostra la capacità riservata per l'utilizzo degli snapshot su questo pool




=== Nodo di archiviazione

I seguenti termini si applicano agli oggetti o ai riferimenti che potresti trovare nelle pagine di destinazione delle risorse dei nodi di archiviazione HDS.  Molti di questi termini si applicano anche ad altri raccoglitori di dati.

* Nome: il nome del Front-end Director (FED) o del Channel Adapter su array monolitici, oppure il nome del controller su un array modulare.  Un dato array HDS avrà 2 o più nodi di archiviazione
* Volumi: la tabella Volume mostrerà qualsiasi volume mappato a qualsiasi porta di proprietà di questo nodo di archiviazione




== Requisiti di inventario

Per raccogliere i dati di inventario è necessario disporre di quanto segue:

* Indirizzo IP del server HiCommand Device Manager
* Nome utente e password di sola lettura per il software HiCommand Device Manager e privilegi peer
* Requisiti porta: 2001 (http) o 2443 (https)
* Accedi al software HiCommand Device Manager utilizzando nome utente e password
* Verificare l'accesso a HiCommand Device Manager \http://<HiCommand_Device_Manager_IP>:2001/service/StorageManager




== Requisiti di prestazione

Per raccogliere dati sulle prestazioni è necessario soddisfare i seguenti requisiti:

* Prestazioni HDS USP, USP V e VSP
+
** Performance Monitor deve essere dotato di licenza.
** L'interruttore di monitoraggio deve essere abilitato.
** Lo strumento di esportazione (Export.exe) deve essere copiato in Data Infrastructure Insights AU.
** La versione dello strumento di esportazione deve corrispondere alla versione del microcodice dell'array di destinazione.


* Prestazioni AMS:
+
** NetApp consiglia vivamente di creare un account di servizio dedicato sugli array AMS affinché Data Infrastructure Insights possa utilizzarlo per recuperare i dati sulle prestazioni.  Storage Navigator consente a un account utente un solo accesso simultaneo all'array.  Se Data Infrastructure Insights utilizza lo stesso account utente degli script di gestione o di HiCommand , Data Infrastructure Insights, gli script di gestione o HiCommand potrebbero non essere in grado di comunicare con l'array a causa del limite di un account utente contemporaneamente.
** Performance Monitor deve essere dotato di licenza.
** L'utilità Storage Navigator Modular 2 (SNM2) CLI deve essere installata su Data Infrastructure Insights AU.






== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Server HiCommand | Indirizzo IP o nome di dominio completo del server HiCommand Device Manager 


| Nome utente | Nome utente per il server HiCommand Device Manager. 


| Password | Password utilizzata per il server HiCommand Device Manager. 


| Dispositivi - Archiviazioni VSP G1000 (R800), VSP (R700), HUS VM (HM700) e USP | Elenco dispositivi per gli storage VSP G1000 (R800), VSP (R700), HUS VM (HM700) e USP.  Ogni storage richiede: * IP dell'array: indirizzo IP dello storage * Nome utente: nome utente per lo storage * Password: password per lo storage * Cartella contenente i file JAR dell'utilità di esportazione 


| SNM2Devices - Archiviazione WMS/SMS/AMS | Elenco dispositivi per archivi WMS/SMS/AMS.  Ogni storage richiede: * IP dell'array: indirizzo IP dello storage * Percorso CLI di Storage Navigator: percorso CLI SNM2 * Autenticazione account valida: selezionare per scegliere un'autenticazione account valida * Nome utente: nome utente per lo storage * Password: password per lo storage 


| Scegli Tuning Manager per le prestazioni | Ignora altre opzioni di prestazioni 


| Host del gestore di ottimizzazione | Indirizzo IP o nome di dominio completo del gestore di ottimizzazione 


| Sostituisci la porta del gestore di ottimizzazione | Se vuoto, utilizzare la porta predefinita nel campo Scegli Tuning Manager per le prestazioni, altrimenti immettere la porta da utilizzare 


| Nome utente del responsabile della messa a punto | Nome utente per Tuning Manager 


| Password del gestore di ottimizzazione | Password per Tuning Manager 
|===
Nota: in HDS USP, USP V e VSP, qualsiasi disco può appartenere a più di un gruppo di array.



== Configurazione avanzata

|===


| Campo | Descrizione 


| Tipo di connessione | HTTPS o HTTP, visualizza anche la porta predefinita 


| Porta del server HiCommand | Porta utilizzata per HiCommand Device Manager 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario.  Il valore predefinito è 40. 


| Selezionare "Escludi" o "Includi" per specificare un elenco | Specificare se includere o escludere l'elenco di array sottostante durante la raccolta dei dati. 


| Elenco dispositivi filtro | Elenco separato da virgole dei numeri di serie dei dispositivi da includere o escludere 


| Intervallo di sondaggio sulle prestazioni (sec) | Intervallo tra i sondaggi sulle prestazioni.  Il valore predefinito è 300. 


| Timeout di esportazione in secondi | Timeout dell'utilità di esportazione.  Il valore predefinito è 300. 
|===


== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova questo: 


| Errore: l'utente non ha autorizzazioni sufficienti | Utilizzare un account utente diverso con maggiori privilegi o aumentare i privilegi dell'account utente configurato nel raccoglitore dati 


| Errore: l'elenco degli archivi è vuoto.  O i dispositivi non sono configurati o l'utente non ha autorizzazioni sufficienti | * Utilizzare DeviceManager per verificare se i dispositivi sono configurati.  * Utilizzare un account utente diverso con più privilegi o aumentare i privilegi dell'account utente 


| Errore: l'array di archiviazione HDS non è stato aggiornato per alcuni giorni | Scopri perché questo array non viene aggiornato in HDS HiCommand. 
|===


=== Prestazione

[cols="2*"]
|===
| Problema: | Prova questo: 


| Errore: * Errore durante l'esecuzione dell'utilità di esportazione * Errore durante l'esecuzione del comando esterno | * Verificare che Export Utility sia installato sull'unità di acquisizione Data Infrastructure Insights * Verificare che la posizione di Export Utility sia corretta nella configurazione del data collector * Verificare che l'IP dell'array USP/R600 sia corretto nella configurazione del data collector * Verificare che il nome utente e la password siano corretti nella configurazione del data collector * Verificare che la versione di Export Utility sia compatibile con la versione del microcodice dell'array di archiviazione * Dall'unità di acquisizione Data Infrastructure Insights , aprire un prompt CMD ed effettuare le seguenti operazioni: - Cambiare la directory nella directory di installazione configurata - Provare a stabilire una connessione con l'array di archiviazione configurato eseguendo il file batch runWin.bat 


| Errore: accesso allo strumento di esportazione non riuscito per l'IP di destinazione | * Conferma che il nome utente/password siano corretti * Crea un ID utente principalmente per questo raccoglitore dati HDS * Conferma che nessun altro raccoglitore dati sia configurato per acquisire questo array 


| Errore: gli strumenti di esportazione hanno registrato "Impossibile ottenere l'intervallo di tempo per il monitoraggio". | * Verificare che il monitoraggio delle prestazioni sia abilitato sulla matrice.  * Provare a richiamare gli strumenti di esportazione al di fuori di Data Infrastructure Insights per confermare che il problema si trova al di fuori di Data Infrastructure Insights. 


| Errore: * Errore di configurazione: Storage Array non supportato da Export Utility * Errore di configurazione: Storage Array non supportato da Storage Navigator Modular CLI | * Configurare solo gli array di archiviazione supportati.  * Utilizzare "Filtra elenco dispositivi" per escludere array di archiviazione non supportati. 


| Errore: * Errore durante l'esecuzione del comando esterno * Errore di configurazione: Array di archiviazione non segnalato da Inventory * Errore di configurazione: la cartella di esportazione non contiene file jar | * Controllare la posizione dell'utilità di esportazione.  * Verificare se l'array di archiviazione in questione è configurato nel server HiCommand. * Impostare l'intervallo di polling delle prestazioni come multiplo di 60 secondi. 


| Errore: * Errore Storage Navigator CLI * Errore durante l'esecuzione del comando auperform * Errore durante l'esecuzione del comando esterno | * Verificare che Storage Navigator Modular CLI sia installato sull'unità di acquisizione Data Infrastructure Insights * Verificare che la posizione di Storage Navigator Modular CLI sia corretta nella configurazione del data collector * Verificare che l'IP dell'array WMS/SMS/SMS sia corretto nella configurazione del data collector * Verificare che la versione di Storage Navigator Modular CLI sia compatibile con la versione del microcodice dell'array di archiviazione configurato nel data collector * Dall'unità di acquisizione Data Infrastructure Insights , aprire un prompt CMD ed effettuare le seguenti operazioni: - Cambiare la directory nella directory di installazione configurata - Provare a stabilire una connessione con l'array di archiviazione configurato eseguendo il seguente comando "auunitref.exe" 


| Errore: Errore di configurazione: Array di archiviazione non segnalato dall'inventario | Verificare se l'array di archiviazione in questione è configurato nel server HiCommand 


| Errore: * Nessun array registrato con Storage Navigator Modular 2 CLI * Array non registrato con Storage Navigator Modular 2 CLI * Errore di configurazione: Storage Array non registrato con StorageNavigator Modular CLI | * Aprire il prompt dei comandi e cambiare directory nel percorso configurato. * Eseguire il comando “set=STONAVM_HOME=.”  * Eseguire il comando "auunitref" * Verificare che l'output del comando contenga i dettagli dell'array con IP * Se l'output non contiene i dettagli dell'array, registrare l'array con Storage Navigator CLI: - Aprire il prompt dei comandi e cambiare directory nel percorso configurato - Eseguire il comando "set=STONAVM_HOME=."  - Eseguire il comando “auunitaddauto -ip <ip>”.  Sostituisci <ip> con l'IP corretto. 
|===
Ulteriori informazioni possono essere trovate pressolink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
