---
sidebar: sidebar 
permalink: task_dc_emc_vnx_unified.html 
keywords: data collector, VNX, EMC, Dell 
summary: Configurazione del raccoglitore dati VNX. 
---
= Configurazione del data collector Dell EMC VNX Unified
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Per la configurazione, il data collector Dell EMC VNX Unified (SSH) richiede l'indirizzo IP della Control Station e un nome utente e una password di sola lettura.



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario da questo raccoglitore di dati.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Disco | Disco 


| Cartella del disco | Gruppo di dischi 


| Sistema di file | Volume interno 


| Magazzinaggio | Magazzinaggio 


| Processore di archiviazione | Nodo di archiviazione 


| Pool di archiviazione, gruppo RAID | Pool di archiviazione 


| LUN | Volume 


| Spostamento dati | Controllore 


| File System montato su un data mover | Condivisione file 


| Esportazioni CIFS e NFS | Condividere 


| Volume del disco | LUN di backend 
|===


== Requisiti

Per configurare il raccoglitore dati VNX (SSH) è necessario quanto segue:

* Indirizzo IP VNX e credenziali per la stazione di controllo Celerra.
* Nome utente e password di sola lettura.
* Il raccoglitore di dati è in grado di eseguire comandi NaviCLI/NaviSecCLI sull'array backend utilizzando le testine NAS del sistema operativo DART




== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP VNX | Indirizzo IP o nome di dominio completo della stazione di controllo VNX 


| Nome utente | Nome utente per la stazione di controllo VNX 


| Password | Password per la stazione di controllo VNX 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 40 minuti. 


| Intervallo di sondaggio sulle prestazioni (sec). | Intervallo tra i sondaggi sulle prestazioni. Il valore predefinito è 300 secondi. 
|===


== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
