---
sidebar: sidebar 
permalink: task_dc_promox_ve.html 
keywords: data collector, Promox VirtVirtual Environmentalization 
summary: Configurare il raccoglitore di dati di Promox Virtual Environment. 
---
= Red Hat OpenShift Virtualization raccoglitore dati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il collector DII Promox Virtual Environment raccoglierà i dati di inventario. Questo è un collector basato su API REST HTTPS.



[[terminology]]
== Terminologia

Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per la risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="50,50"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Disco | Disco virtuale 


| Ospite | Ospite 


| Macchina virtuale | Macchina virtuale 


| Dominio di archiviazione | Archivio dati 


| Unità logica | LUN 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



[[configuration]]
== Configurazione

[cols="50,50"]
|===
| Campo | Descrizione 


| Nome host o indirizzo IP | Nome host Indirizzo IP del sistema storage 


| ID token API | Token API necessario per l'accesso 


| Segreto del token API | Segreto per il token sopra 
|===


[[advanced-configuration]]
== Configurazione avanzata

[cols="50,50"]
|===
| Campo | Descrizione 


| Porta di comunicazione HTTPS | Porta utilizzata per la comunicazione HTTPS (predefinita 8006) 


| Intervallo di sondaggio dell'inventario (min) | Il valore predefinito è 20 minuti. 
|===


[[troubleshooting]]
== Risoluzione dei problemi

Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
