---
sidebar: sidebar 
permalink: task_create_annotation.html 
keywords: annotations, annotation rules, manual annotations, 
summary: 'Come creare un"annotazione.' 
---
= Utilizzo delle annotazioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puoi creare annotazioni e assegnarle alle risorse che monitori.  Le annotazioni sono note che forniscono informazioni su una risorsa, ad esempio la posizione fisica, la fine del ciclo di vita, il livello di archiviazione o i livelli di servizio del volume.



== Definizione delle annotazioni

Utilizzando le annotazioni, puoi aggiungere alle risorse dati aziendali personalizzati e specifici che corrispondono alle tue esigenze aziendali.  Sebbene Data Infrastructure Insights fornisca una serie di annotazioni predefinite, come il ciclo di vita delle risorse (data di nascita o fine vita), l'ubicazione dell'edificio o del data center e il livello, potresti voler visualizzare i dati in altri modi.

I dati nelle annotazioni personalizzate integrano i dati del dispositivo già raccolti, come il produttore dello switch, il numero di porte e le statistiche sulle prestazioni.  I dati aggiunti tramite annotazioni non vengono rilevati da Data Infrastructure Insights.

.Prima di iniziare
* Elencare qualsiasi terminologia del settore a cui devono essere associati i dati ambientali.
* Elencare la terminologia aziendale a cui devono essere associati i dati ambientali.
* Identifica i tipi di annotazione predefiniti che potresti essere in grado di utilizzare.
* Identifica quali annotazioni personalizzate devi creare.  È necessario creare l'annotazione prima di poterla assegnare a una risorsa.


Per creare un'annotazione, attenersi alla seguente procedura.

.Passi
. Nel menu Data Infrastructure Insights , fare clic su *Osservabilità > Arricchisci > Annotazioni*
. Fare clic su *+ Annotazione* per creare una nuova annotazione.
. Inserisci un nome, una descrizione e un tipo per la nuova annotazione.
+
Ad esempio, immettere quanto segue per creare un'annotazione di testo che definisca la posizione fisica di una risorsa nel Data Center 4:

+
** Inserisci un nome per l'annotazione, ad esempio "Posizione"
** Inserisci una descrizione di ciò che l'annotazione descrive, ad esempio "La posizione fisica è il Data Center 4"
** Inserisci il "tipo" di annotazione, ad esempio "Testo".






== Assegnazione manuale di annotazioni alle risorse

L'assegnazione di annotazioni alle risorse ti aiuta a ordinare, raggruppare e creare report sulle risorse in modi pertinenti alla tua attività.  Sebbene sia possibile assegnare automaticamente annotazioni a risorse di un tipo specifico utilizzando le regole di annotazione, è possibile assegnare annotazioni a una singola risorsa utilizzando la relativa pagina delle risorse.

.Prima di iniziare
* Devi aver creato l'annotazione che vuoi assegnare.


.Passi
. Accedi al tuo ambiente Data Infrastructure Insights .
. Individua la risorsa a cui desideri applicare l'annotazione.
+
** È possibile individuare le risorse tramite query, selezionandole da un widget del dashboard o tramite ricerca.  Una volta individuata la risorsa desiderata, clicca sul link per aprire la landing page della risorsa.


. Nella pagina delle risorse, nella sezione Dati utente, fare clic su *+ Annotazione*.
. Viene visualizzata la finestra di dialogo Aggiungi annotazione.
. Seleziona un'annotazione dall'elenco.
. Fare clic su Valore ed effettuare una delle seguenti operazioni, a seconda del tipo di annotazione selezionato:
+
** Se il tipo di annotazione è elenco, data o booleano, selezionare un valore dall'elenco.
** Se il tipo di annotazione è testo, digitare un valore.


. Fare clic su *Salva*.


Se si desidera modificare il valore dell'annotazione dopo averla assegnata, fare clic sul campo dell'annotazione e selezionare un valore diverso.  Se l'annotazione è di tipo elenco per cui è selezionata l'opzione _Aggiungi nuovi valori al volo_, è possibile digitare un nuovo valore oltre a selezionare un valore esistente.



== Assegnazione di annotazioni utilizzando le regole di annotazione

Per assegnare automaticamente annotazioni alle risorse in base ai criteri definiti, è possibile configurare le regole di annotazione.  Data Infrastructure Insights assegna le annotazioni alle risorse in base a queste regole.  Data Infrastructure Insights fornisce anche due regole di annotazione predefinite, che puoi modificare in base alle tue esigenze o rimuovere se non desideri utilizzarle.



=== Creazione di regole di annotazione

In alternativa all'applicazione manuale delle annotazioni alle singole risorse, è possibile applicare automaticamente le annotazioni a più risorse utilizzando le regole di annotazione.  Le annotazioni impostate manualmente sulle singole pagine delle risorse hanno la precedenza sulle annotazioni basate su regole quando Insight valuta le regole di annotazione.

.Prima di iniziare
Devi aver creato una query per la regola di annotazione.

.Informazioni su questo compito
Sebbene sia possibile modificare i tipi di annotazione durante la creazione delle regole, è opportuno definire i tipi in anticipo.

.Passi
. Fare clic su *Gestisci > Regole di annotazione*
+
La pagina Regole di annotazione visualizza l'elenco delle regole di annotazione esistenti.

. Fare clic su *+ Aggiungi*.
. Procedi come segue:
+
.. Nella casella *Nome*, immettere un nome univoco che descriva la regola.
+
Questo nome apparirà nella pagina Regole di annotazione.

.. Fare clic su *Query* e selezionare la query utilizzata per applicare l'annotazione alle risorse.
.. Fare clic su *Annotazione* e selezionare l'annotazione che si desidera applicare.
.. Fare clic su *Valore* e selezionare un valore per l'annotazione.
+
Ad esempio, se si sceglie Compleanno come annotazione, si specifica una data per il valore.

.. Fai clic su *Salva*
.. Fare clic su *Esegui tutte le regole* se si desidera eseguire tutte le regole immediatamente; in caso contrario, le regole vengono eseguite a intervalli regolari pianificati.



