---
sidebar: sidebar 
permalink: task_create_application.html 
summary: Definisci le applicazioni che poi applicherai alle risorse del tuo tenant in base alle necessità. 
keywords: application, create application, 
---
= Creazione di applicazioni
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Per tenere traccia dei dati associati ad applicazioni specifiche in esecuzione sul tuo tenant, puoi definire le applicazioni in Data Infrastructure Insights.

.Informazioni su questo compito
Data Infrastructure Insights consente di monitorare i dati provenienti dalle risorse associate alle applicazioni per scopi quali la rendicontazione dell'utilizzo o dei costi.

.Passi
. Nel menu Data Infrastructure Insights , fare clic su *Osservabilità > Arricchisci > Applicazioni*.  Selezionare
+
Viene visualizzata la finestra di dialogo Aggiungi applicazione.

. Inserisci un nome univoco per l'applicazione.
. Seleziona una priorità per l'applicazione.
. Fare clic su *Salva*.


Dopo aver definito un'applicazione, è possibile assegnarla alle risorse.



== Assegnazione delle applicazioni alle risorse

Questa procedura assegna l'applicazione a un host come esempio.  È possibile assegnare host, macchine virtuali, volumi o volumi interni a un'applicazione.

.Passi
. Individua la risorsa a cui vuoi assegnare l'applicazione:
. Fare clic su *Query > +Nuova query* e cercare Host.
. Fare clic sulla casella di controllo a sinistra dell'host che si desidera associare all'applicazione.
. Fare clic su *Azioni in blocco > Aggiungi applicazione*.
. Seleziona l'applicazione a cui vuoi assegnare la risorsa.


Tutte le nuove applicazioni assegnate sovrascrivono tutte le applicazioni sulla risorsa derivate da un'altra risorsa.  Ad esempio, i volumi ereditano le applicazioni dagli host e quando a un volume vengono assegnate nuove applicazioni, la nuova applicazione ha la precedenza sull'applicazione derivata.


NOTE: Per ambienti con grandi quantità di risorse correlate, l'ereditarietà delle assegnazioni delle applicazioni a tali risorse potrebbe richiedere diversi minuti.  Se si hanno molti beni correlati, si prega di attendere più tempo affinché l'eredità avvenga.

.Dopo aver finito
Dopo aver assegnato l'host all'applicazione, è possibile assegnare le risorse rimanenti all'applicazione.  Per accedere alla landing page dell'applicazione, clicca su *Gestisci > Applicazione* e seleziona l'applicazione che hai creato.
