---
sidebar: sidebar 
permalink: task_dc_ibm_svc.html 
keywords: IBM, SVC,SAN 
summary: Configurazione del raccoglitore dati IBM SAN Volume Controller. 
---
= Configurazione del raccoglitore dati IBM SAN Volume Controller
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Il raccoglitore dati IBM SAN Volume Controller (SVC) raccoglie dati di inventario e prestazioni tramite SSH, supportando una varietà di dispositivi che eseguono il sistema operativo SVC.

L'elenco dei dispositivi supportati include modelli quali SVC, v7000, v5000 e v3700.  Per i modelli supportati e le versioni del firmware, fare riferimento alla matrice di supporto Data Infrastructure Insights .



== Terminologia

Data Infrastructure Insights acquisisce le seguenti informazioni di inventario dal raccoglitore dati IBM SVC.  Per ogni tipo di risorsa acquisita da Data Infrastructure Insights, viene mostrata la terminologia più comune utilizzata per tale risorsa.  Quando si visualizza o si risolve un problema con questo strumento di raccolta dati, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Termine del fornitore/modello | Termine Data Infrastructure Insights 


| Guidare | Disco 


| Grappolo | Magazzinaggio 


| Nodo | Nodo di archiviazione 


| Gruppo Mdisk | Pool di archiviazione 


| Vdisk | Volume 


| Mdisk | LUN e percorsi backend 
|===
Nota: queste sono solo mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questo raccoglitore di dati.



=== Requisiti di inventario

* Indirizzo IP di ciascun cluster SVC
* Porta 22 disponibile
* Nome utente e password di sola lettura




=== Requisiti di prestazione

* Console SVC, obbligatoria per qualsiasi cluster SVC e richiesta per il pacchetto SVC Discovery Foundation.
* Le credenziali richiederanno il livello di accesso amministrativo solo per copiare i file delle prestazioni dai nodi del cluster al nodo di configurazione.
* Abilita la raccolta dati connettendoti al cluster SVC tramite SSH ed eseguendo: _svctask startstats -interval 1_
+
Nota: in alternativa, abilitare la raccolta dati tramite l'interfaccia utente di gestione SVC.





== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzi IP del cluster | Indirizzi IP o nomi di dominio completi dell'archiviazione SVC 


| Nome utente inventario | Nome utente per la CLI SVC 


| Password di inventario | Password per la CLI SVC 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo di sondaggio dell'inventario (min) | Intervallo tra i sondaggi di inventario. Il valore predefinito è 40 minuti. 


| Intervallo di sondaggio sulle prestazioni (sec) | Intervallo tra i sondaggi sulle prestazioni. Il valore predefinito è 300 secondi. 


| Per ripulire i file delle statistiche scaricati | Seleziona questa casella di controllo per ripulire i file delle statistiche scaricate 
|===


== Risoluzione dei problemi

Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:

[cols="2*"]
|===
| Problema: | Prova questo: 


| Errore: "Impossibile avviare il comando perché non è stato eseguito sul nodo di configurazione." | Il comando deve essere eseguito sul nodo di configurazione. 
|===
Ecco alcune cose da provare se riscontri problemi con questo strumento di raccolta dati:

[cols="2*"]
|===
| Problema: | Prova questo: 


| Errore: "Impossibile avviare il comando perché non è stato eseguito sul nodo di configurazione." | Il comando deve essere eseguito sul nodo di configurazione. 
|===
Ulteriori informazioni su questo Data Collector possono essere trovate dalink:concept_requesting_support.html["Supporto"] pagina o nellalink:reference_data_collector_support_matrix.html["Matrice di supporto del raccoglitore dati"] .
